### ISSUE TITLE
"vagrant port" command

### ISSUE THREAD

**Issue by jordansissel** [mitchellh/vagrant#1415]
Vagrant's [port collision and correction](http://docs.vagrantup.com/v2/networking/forwarded_ports.html) feature is cool!

As a user, I would like to be able to figure out what the corrected port is.

Currently, I could do this:

* read the vbox uuid from the .vagrant file
* use VBoxManage showvminfo to find the host ports chosen

Example, to find what host port maps to guest port 5601:

```
% VBoxManage showvminfo 6bfdd751-bc20-48ae-b80f-20408086b82d | grep 'guest port = 5601'
NIC 1 Rule(1):   name = 5f1-16bq, protocol = tcp, host ip = , host port = 39290, guest ip = , guest port = 5601
```

More ideally, something like `vagrant port <port>` could output the host port which forwards to `<port>` on the guest vm.

**Comment by kuboj** [comment]
Since vagrant-port by @jordansissel is not longer being maintained, I implemented [vagrant-portinfo](https://github.com/kuboj/vagrant-portinfo) which is inspired by it and should be working. There is minor difference in manner how this command works - it prints all forwarded ports rather than querying for specific one.
Hope it helps somone.
