### ISSUE TITLE
Support Ansible “Local Playbooks”

### ISSUE THREAD

**Issue by mxey** [mitchellh/vagrant#2103]
At the moment, the Ansible provisioner only supports running Ansible running over SSH. IMHO, this complicates the setup and requires Ansible on the host system (unlike the Puppet provisioner, for example).

Ansible supports running playbooks on localhost: http://www.ansibleworks.com/docs/playbooks2.html#id20

**Comment by mkuzmin** [comment]
any progress?
As Ansible cannot be started from Windows hosts, this feature would greatly simplify playbook development and usage for developers working with Windows.

**Comment by gildegoma** [comment]
Sorry guys, I had lots of other (unexpected) things to do first. I resume my work in progress and give you some feedbacks asap.

**Comment by mkuzmin** [comment]
No need to excuse, that's open source after all. 
Let us know if you have something to test

**Comment by tuminoid** [comment]
:+1: for this work.

**Comment by gildegoma** [comment]
I'm closing some little issues and adding some test coverage. When done, I can start the work :)

**Comment by gildegoma** [comment]
Hello Guys! Please have a look at #5340, and let us know if it would meet your needs (or not) :smile:

**Comment by gildegoma** [comment]
Just a "collaboration workflow" precision, please put your comments here on #2103, so we can keep the discussion of #5340 focused on the PR review. Thanks!

**Comment by mkuzmin** [comment]
This is great news!
I've tested basic scenarios, and it works - Ansible runtime is installed, and basic playbooks are applied.
I'll continue my tests, and let you know on any issues.

Thank you for this work, that's really a big feature.

**Comment by geerlingguy** [comment]
This is looking awesome! I didn't have a chance to test locally yet, but glanced through the proposed workflow and it makes sense to me—I especially like that it basically mirrors Packer's usage/terminology, making the metal shift from Packer->Vagrant->Packer less annoying :)

**Comment by gildegoma** [comment]
@mkuzmin Thanks for jumping into testing it so quickly :) Please keep us informed if you hit any bug or trouble! Do you run it on Windows?

@geerlingguy Thanks for your vote for Packer's terminology! Please let us know if you do some beta testing as well :)

**Comment by mkuzmin** [comment]
Yes, I have Windows on a host, and Ubuntu inside a box.

**Comment by warrenseine** [comment]
I'm supporting PR mitchellh/vagrant/pull/5340, though I've got a simple question: why do we need a new provisioner? Can't we add a `local` option to the `ansible` provisioner?

**Comment by gildegoma** [comment]
@warrenseine asked:

> Can't we add a local option to the ansible provisioner?

Warren, thanks for asking. I also [initially thought about a single provisioner](https://github.com/mitchellh/vagrant/issues/2103#issuecomment-35861853). But while working further on this feature, it turns out that splitting in two provisioners was (certainly) the best approach. The first reasons that lead to this decision were purely technical. But from the end-user perspective, I think that it also makes sense since the location of the *Ansible control machine* implies different capabilities and constraints. Here are the main reasons for this design:

 - Unsupported options are automatically checked by the Vagrant plugin architecture (no additional code required). With a single provisioner approach, we should implement a set of ad-hoc validators to refuse invalid configurations (e.g. the `install` option could not be enabled in remote mode, etc.).
 - It *forces* to think carefully about the shared or specific functions. For instance, the upcoming support of WinRM for configuring Windows-based guests (#5086) will be added to `ansible` remote provisioner, but certainly not to the `ansible_local` provisioner.
 - Support of Puppet and Chef also provides multiple provisioners for similar reasons and with similar design (and documentation organization).
 - It mimics the current [Packer's naming](https://www.packer.io/docs/provisioners/ansible-local.html) and "kindly invite" the Vagrant user to decide where Ansible must be installed and executed.
 - Having these two dedicated provisioners doesn't prevent to easily build a "flexible" `Vagrantfile` (i.e. able to switch between the two modes, depending on external conditions).

Note that all the common stuff is stored in a shared codebase, and we'll take care to keep things clean with the upcoming additions ;-).

I hope this answer your question... and I keep all ears to more ideas and critics!

**Comment by mkuzmin** [comment]
The arguments sound reasonable.

Speaking on Ansible runtime installation, I have another feature request. Are you going to support `requirements.yml` files?
With remote provisioner I was able to run `ansible-galaxy` explicitly, but now it has to be done within your plugin: roles must be downloaded after runtime installation, but before playbook execution.

**Comment by gildegoma** [comment]
@mkuzmin good catch about `ansible-galaxy` integration. This feature request is tracked by #2718, and you're right this is a must have for Vagrant 1.8.0. I add it to the pending tasks for PR #5340, thanks!

**Comment by warrenseine** [comment]
@gildegoma Thanks for the detailed explanation. It makes sense.

**Comment by gildegoma** [comment]
FYI: `ansible-galaxy` support is still not implemented. With a little chance I can find the time to fix it before 1.8.0 release, otherwise I'll do my best to ship it "asap" (e.g. in one of the next minor releases). If someone want to pick this item and work on it, feel free to announce in #2718.

**Comment by lemontreeran** [comment]
Any update on the ansible_local provisioner?
Does it support the  ansible-galaxy now?
