### ISSUE TITLE
chef_client provisioner fails to cleanup node on chef server

### ISSUE THREAD

**Issue by pharaujo** [mitchellh/vagrant#2476]
I am having trouble cleaning up the node on chef server when destroying a vagrant instance.

My config:
```rb
  config.vm.provision :chef_client do |chef|
    chef.chef_server_url = "https://internalchefserver"
    chef.validation_key_path = "./pedro.pem"
    chef.validation_client_name = "pedro"
    chef.delete_node = "true"

    chef.add_recipe "base"
  end
```

Destroying gives a stack trace:
```
$ vagrant -v
Vagrant 1.3.5
$ vagrant destroy -f
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
[default] Running cleanup tasks for 'chef_client' provisioner...
Deleting node "#<Vagrant::Config::V2::DummyConfig:0x00000100ce87f8>" from Chef server...
/Applications/Vagrant/embedded/gems/gems/childprocess-0.3.9/lib/childprocess/abstract_process.rb:36:in `initialize': all arguments must be String: ["/Users/pedroaraujo/.rvm/gems/ruby-1.9.3-p448/bin/knife", "node", "delete", "--yes", #<Vagrant::Config::V2::DummyConfig:0x00000100ce87f8>] (ArgumentError)
<omitted stack trace>
```

I had a look at the [source code](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/chef/provisioner/chef_client.rb#L107) and it seems ```node_name``` is not defined, so I added the following to my config:
```rb
    chef.node_name = config.vm.hostname
```

This almost worked, but it seems knife tries to use the embedded GEM_PATH and fails to load its core dependencies:
```
$ vagrant destroy -f
[default] Forcing shutdown of VM...
[default] Destroying VM and associated drives...
[default] Running cleanup tasks for 'chef_client' provisioner...
Deleting node "vagranttest" from Chef server...
Cleaning up the 'node' for Chef failed. The stdout and
stderr are shown below. Vagrant will continue destroying the machine,
so please clean up these resources manually.

stdout:

stderr: /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency.rb:247:in `to_specs': Could not find chef (>= 0) amongst [builder-3.2.2, childprocess-0.3.9, erubis-2.7.0, ffi-1.9.0, i18n-0.6.5, i18n-0.6.4, log4r-1.1.10, mini_portile-0.5.1, net-scp-1.1.2, net-ssh-2.6.8, nokogiri-1.6.0, rbvmomi-1.6.0, trollop-2.0, vagrant-1.3.5, vagrant-1.2.3, vagrant-cachier-0.4.1, vagrant-vsphere-0.0.1] (Gem::LoadError)
	from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems/dependency.rb:256:in `to_spec'
	from /Applications/Vagrant/embedded/lib/ruby/1.9.1/rubygems.rb:1231:in `gem'
	from /Users/pedro/.rvm/gems/ruby-1.9.3-p448/bin/knife:22:in `<main>'
	from /Users/pedro/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `eval'
	from /Users/pedro/.rvm/gems/ruby-1.9.3-p448/bin/ruby_noexec_wrapper:14:in `<main>'

```

**Comment by sethvargo** [comment]
I think, for once and for all, this is fixed by https://github.com/mitchellh/vagrant/pull/5912 :smile:. 

Unfortunately this is a generally unsolved problem and each Ruby version manager behaves slightly differently. With the complex behavior of Bundler, individual system settings, and star/moon alignment, it is possible that whatever incantation of Ruby + Chef + other rubies on the system that this might still persist for a small number of users. We have chosen to optimize and test for the "common" use case, which is ChefDK, using Vagrant in the official installer and using Vagrant as a bundled gem. I also tested rbenv and chruby (for the Chef installation) and was able to get things working.

I am marking this issue as fixed, while recognizing that certain situations may not be accounted for. Unfortunately we just can't make this work perfectly for everyone. If you are experiencing issues, please _open a new issue_ and include your Ruby setup, Chef installation, Vagrant version, and the debug output. Moving forward, we will likely only support bug reports as they relate to the official installation processes for both tools (ChefDK and Vagrant's official installer).

This will be released in Vagrant 1.7.3
