### ISSUE TITLE
Cleanup Tasks for Shell Provisioner

### ISSUE THREAD

**Issue by jeremyfelt** [mitchellh/vagrant#2538]
Support for cleanup tasks was added via #1302 in Vagrant 1.3.0 and only the Chef provisioner was given a built in method to handle this functionality.

It would be excellent if the built in shell provisioner also had the ability to run either an inline script or file on `vagrant destroy`.

**Comment by pdxfixit** [comment]
+1 for this feature.

**Comment by sjmarshy** [comment]
+1

**Comment by komlenic** [comment]
+1

**Comment by komlenic** [comment]
I think this should be a core feature due to its utility and varied use-cases, however using the vagrant-triggers plugin is an option.

To implement this functionality using vagrant-triggers plugin, in your vagrantfile you can add:
```ruby
config.trigger.before :destroy do
  info "Dumping the database before destroying the VM..."
  run_remote  "command"
end
```

If you prefer to use a shell script to contain all your teardown/cleanup tasks:
```ruby
config.trigger.before :destroy do
  info "Dumping the database before destroying the VM..."
  run_remote  "bash /vagrant/cleanup.sh"
end
```
... where /vagrant/cleanup.sh is a script that will exist on both the host and the guest, because vagrant shares the directory containing the vagrantfile on the host, with /vagrant on the guest by default.

**Comment by Stono** [comment]
+1

**Comment by clok** [comment]
+1

**Comment by franklinkim** [comment]
+1

**Comment by edux** [comment]
+1

**Comment by akatz0813** [comment]
+1 Using vagrant with aws code deploy on-premises and really need to deregister the machine from within the vm on destroy.

**Comment by iampuma** [comment]
+1

**Comment by dennisgranath** [comment]
+1

**Comment by kadaan** [comment]
@gtmtech FWIW internally we added support for vagrantfile specified parameters which can be specified in a similar way to triggers. We use it to allow users to pass in their credentials way earlier in `vagrant up` and to allow them to specify if they want to join the domain. The parameters end up in `vagrant up -?` just like the native parameters.  Would this coupled with vagrant-triggers accomplish what you want?

**Comment by gtmtech** [comment]
As mentioned back in Nov 11, there's still a bunch of things that vagrant-triggers doesn't address, including the ability with provisioning to run a script rather than just run individual commands (which I *believe* is still the case with vagrant-triggers - had a quick look and doesn't look like they've added this functionality yet). I know vagrant-triggers is amazingly useful, but I dont think I've ever been convinced that anything will be as neat as the ability to run a parameterised deprovisioning shell script, just like you can run a provisioning one. I'm still a +1 for this.

**Comment by gtmtech** [comment]
Just did a quick tally, and 45 people have +1'd this feature request, in case that pits it against other requests.

**Comment by kadaan** [comment]
@gtmtech I believe what I mentioned would allow you to accomplish your goals. You can define required parameters, in the vagrantfile, for any arbitrary command. These parameters are available in the vagrant-triggers definitions. The trigger can run a script on the host or guest.

For example you could define a username parameter for `vagrant destroy` which would be required when the user runs the command.  The value of this parameter is available in the :before-destroy trigger.  You can run a script in the trigger using run_remote and pass the param to the script. 

Does this accomplish wait?

**Comment by ftrojahn** [comment]
+1

**Comment by Sander-Toonen** [comment]
I just noticed the following message on ``vagrant destroy``:
_Running cleanup tasks for 'shell' provisioner..._

Does that mean that the functionality is present? If so, could it please be documented?

**Comment by thom8** [comment]
It's only available if the provisioner supports it -- AFAIK the shell provsioner does not.

**Comment by rrzaripov** [comment]
+1

**Comment by MartinLyne** [comment]
+1 (or @Sander-Toonen 's suggestion of telling us we can do it already if we can, the message is extremely misleading)

**Comment by bertramn** [comment]
+1

**Comment by jlumbroso** [comment]
+1

**Comment by chrisroberts** [comment]
Related: #3849

**Comment by chrisroberts** [comment]
As #3849 encompasses enhancement I'm going to close this one up and keep the other open. Cheers!
