### ISSUE TITLE
Salt provisioner log_level doesn't work if salt.verbose not set

### ISSUE THREAD

**Issue by artemyarulin** [mitchellh/vagrant#3754]
Hi,

From [salt provisioner documentation](http://docs.vagrantup.com/v2/provisioning/salt.html) we can control output control using
 `log_level`, but it doesn't affect the output. And even default value (which is `debug`) doesn't produce any output from salt provisioner.

I found a reason for that, in [plugins/provisioners/salt/provisioner.rb](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/salt/provisioner.rb#L268-L277):

```
@machine.communicate.sudo("salt '*' state.highstate --verbose#{get_loglevel}#{get_colorize}#{get_pillar}") do |type, data|
      if @config.verbose
        @machine.env.ui.info(data)
      end
    end
  else
    @machine.communicate.sudo("salt-call saltutil.sync_all")
    @machine.communicate.sudo("salt-call state.highstate #{get_loglevel}#{get_colorize}#{get_pillar}") do |type, data|
      if @config.verbose
        @machine.env.ui.info(data)
```

As you can see log data get printer if additional `verbose` attribute is set for salt provisioner.

So, I'm not sure - shall config.verbose check be removed or documentation updated with a `verbose` flag.

**Comment by eupharis** [comment]
I too am running into this. Any update on this bug?

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
