### ISSUE TITLE
LZMA support doesn't work

### ISSUE THREAD

**Issue by titanous** [mitchellh/vagrant#3893]
I'm trying to use the new LZMA-compressed box support with Vagrant 1.6.2 on Mavericks, and I've run into some issues. I tested three different LZMA compression options, and all resulted in failure:
## xz

`xz` is the most modern LZMA2 compression option. Adding a box compressed with it results in this error:

``` text
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

bsdtar: Error opening archive: Can't initialize filter; unable to run program "xz -d -qq"
```

Installing xz with `brew install xz` solves this problem, my recommendation is to package xz with Vagrant.
## lzma

A box compressed with `bsdtar --lzma` fails with this error:

``` text
bsdtar: Error opening archive: Can't initialize filter; unable to run program "lzma -d -qq"
```

The `--lzma` flag is deprecated so I didn't test, but I expect `brew install xz` would fix this too.
## 7-zip

A box compressed with `7z` from p7zip results in this error:

``` text
x packer_virtualbox-iso_virtualbox.box: LZMA codec is unsupported
bsdtar: Error exit delayed from previous errors.
```

I'm not sure what the problem is here, but I think just supporting `xz` would be enough.

**Comment by vadviktor** [comment]
I don't see any working solution to this issue: create a vagrant importable box archive of a vmware machine with 4G+ sized vmdk, on a windows host machine.
Couldn't we do something like "exporting" the machine first to create a really small version first and then compress that, something like the `box package` command is doing with a virtualbox machines?

It would be even a nice option to have Vagrant look for `7zip` (or even given the path as parameter) and use that instead of the built in `bsdtar` (since it is not coping with larger files as already said before).

**Comment by mwrock** [comment]
I've had luck with this: https://github.com/benesch/libarchive/releases/download/v3.1.2/libarchive-3.1.2-bin-windows.zip on windows. However, I after experimenting with it alot, I've actually come to the conclusion that the size in space saved is negated by the decompression time. I posted about that at http://www.hurryupandwait.io/blog/more-windows-packaging-for-vagrant-and-fixing-1603-errors-during-msi-installs

**Comment by chrisroberts** [comment]
Closing as fix has already been applied to the installers
