### ISSUE TITLE
vmware_fusion provider clobber NFS exports from virtualbox provider

### ISSUE THREAD

**Issue by d11wtq** [mitchellh/vagrant#4295]
I've been wondering what is going on with this, but have finally figured it out. Since upgrading to Vagrant 1.6.3—which incidentally was the same day I installed VMWare Fusion 6 and purchased the vmware_fusion provider for Vagrant—my primary VirtualBox machine keeps breaking with "Stale NFS handle".

The reason is every time I boot into my VMWare Fusion machine, Vagrant prunes "invalid" NFS exports. It is detecting the virtualbox NFS exports as "invalid" and removing them, thus breaking my running VirtualBox machine until I restart it.

**Comment by sethvargo** [comment]
@d11wtq is this still an issue with VMware Fusion 7 and Vagrant 1.7?

**Comment by theUniC** [comment]
@d11wtq @mitchellh Any update on this? I'm running the same issue :(

**Comment by sethvargo** [comment]
Closing due to lack of response. (Sorry :frowning:). If this is still an issue with a recent version of Vagrant (1.7.2+), please open a new issue and include the complete Vagrantfile as well as the output of the various commands in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html). Thanks!
