### ISSUE TITLE
Centos7: Vmware ethernet name changes when booted in vagrant with persistent udev naming rules

### ISSUE THREAD

**Issue by jameskyle** [mitchellh/vagrant#4590]
I'm creating vagrant box's with packer. The process goes smoothly without error. 

After the box is imported and a vagrant up is called, the resulting image has a different interface name.

The name is of the following format (as is the one in packer packer, just a different name): eno16777728

CentOS 7 uses persistent udev naming rules. The above naming format indicates it's using the bios device index. For the name to change, the bios index would need to change.

I assume this is a result of a change in the vmx file resulting in a change in device enumeration by the bios.

**Comment by lattwood** [comment]
Just ran into this after purchasing the vmware provider, sent an email to support@hashicorp.com (it'll come from jnickel.com, @mitchellh )

**Comment by cbednarski** [comment]
It *might* be VMware doing this. When you import or clone a VM via the GUI, VMware asks you whether you want to reinitialize the network interfaces. The reason is that these interfaces are associated with additional data like VMnet IPs and MAC addresses in VMware's virtual networking layer. If you have duplicate MACs or IPs set the boxes won't be able to connect to the network (or maybe won't boot).

I presume for simplicity and "just works" functionality, Vagrant (or possibly VMware) assigns a new NIC when you bring up the box. You'll also get a new one when you `destroy` and `up` the box. Without this, you would likely need to create a separate vmnet VLAN for each VM so it can have its own network segment which doesn't conflict with other VMs.

I think as a work-around for this you can use the Vagrant provider section to write the vmx data for the interface exactly the way you want, but you'll have to dig into the vmx format a bit. The easiest way I've found to do this is to copy the data from an existing vmx file that's already configured the way I want.

Something like:

```ruby
config.vm.provider "vmware_fusion" do |v|
  v.vmx["ethernet1.pciSlotNumber"] = "32"
  # etc.
end
```

In the clone scenario I mentioned, the GUI does provide a way to keep the same interface if that's what you want. There may be something we can pass to the VMware provider to use this behavior with Vagrant and expose via a setting like `reinitialize_nic: false`, but it would be good to confirm this will work.

I think doing this may break vagrant in subtle ways, since you won't be able to `up` more than one machine from the same Vagrantfile. Also, not an expert and I didn't test this, so I might be completely wrong. :)

/cc @sethvargo @lattwood

**Comment by lattwood** [comment]
Thanks for the speedy response

It seems like VMWare's behaviour when adding an additional virtual  network adapter is deterministic enough that copying the configuration for ens33 to ens32 during the packer build process works around this behaviour. Since I'm creating multiple VMs from the vagrantfile the VM workaround is the appropriate solution for this case.

**Comment by jameskyle** [comment]
@cbednarski 

It's true that creating a new nic is a good policy to avoid MAC collisions and such. However, this particular problem maps to which virtual *slot* the card is plugged into. 

The location the card is plugged into should have no effect on network configuration or conflicts.

**Comment by mitchellh** [comment]
I recommend going with @lattwood's workaround unless we can come up with a way for Vagrant to do this automatically .Thanks!

**Comment by rmoriz** [comment]
It seems to me this also affects/breaks Ubuntu 15.10 + 16.04 server released with systemd-based predictable interface naming (afaik the distro default, which is based on the hotplug slot for external network interfaces (non-onboard) like VMWare simulates, see https://www.freedesktop.org/wiki/Software/systemd/PredictableNetworkInterfaceNames/ )

**Comment by rmoriz** [comment]
Could it be that VMWare recently changed the **default** NIC slot ID from 33 to 32 so packer could just do the change, too? When manually setting the VMX value on build time to 32 I have no problems with vagrant anymore in later clones/uses. See https://github.com/chef/bento/pull/545#issuecomment-203043020
