### ISSUE TITLE
Cannot disable smb user/password login

### ISSUE THREAD

**Issue by fire** [mitchellh/vagrant#4661]
There doesn't seem to be a way of disabling Vagrant smb username and password logins.

    config.vm.synced_folder ".", "/vagrant", disabled: true

Doesn't prevent logins.

`vagrant up --provider=hyperv` is prompting for a username or password.

**Comment by michaelzhou999** [comment]
Is there any further updates on this issue? I am encountering an issue while trying to "vagrant up" a VM in AWS, where vagrant keeps asking me SMB username/password.  I do have a Chef solo provisioner and from reading other threads, it looks like SMB is indeed used when it comes to run Chef solo scripts? 

This becomes annoying when I don't care much about the performance gain with SMB over other sync mechanisms like "rsync" but I do care about fully automating the process of standing up a machine. 

Is there a way to work around this before a permanent solution? Thanks

**Comment by sethvargo** [comment]
Hi @fire @michaelzhou999 

Could you please share a complete Vagrantfile to reproduce this issue?

**Comment by fire** [comment]
I haven't looked into this in a long time. Will probably need to check the recent release.

**Comment by sethvargo** [comment]
Hi there,

I am going to closet his issue due to inactivity. I was unable to reproduce this issue, which could mean it's been fixed in Vagrant 1.8.1, or it could mean that I'm doing something different, but without a Vagrantfile and reproduction case, it's very difficult to debug.

If this is still occurring, please open a _new_ issue and follow our new issue template and we will get this fixed as quickly as possible. Thanks! :smile:
