### ISSUE TITLE
Double entries in /etc/exports

### ISSUE THREAD

**Issue by Carpetsmoker** [mitchellh/vagrant#4666]
Sometimes Vagrant puts doubles entries in `/etc/exports`, causing nfsd to fail, for example:

```
$ cat /etc/exports
# VAGRANT-BEGIN: 1001 9e5c7f10-0b0e-4713-a87c-0638a78bdf62
"/home/martin/code/cust/dewoningbeheerder" 192.168.33.10(rw,no_subtree_check,all_squash,anonuid=1001,anongid=1001,fsid=2556391661)
# VAGRANT-END: 1001 9e5c7f10-0b0e-4713-a87c-0638a78bdf62
# VAGRANT-BEGIN: 1001 9e5c7f10-0b0e-4713-a87c-0638a78bdf62
"/home/martin/code/cust/dewoningbeheerder" 192.168.33.10(rw,no_subtree_check,all_squash,anonuid=1001,anongid=1001,fsid=2556391661)
# VAGRANT-END: 1001 9e5c7f10-0b0e-4713-a87c-0638a78bdf62
```

I have this maybe once every two weeks, for all projects (using Vagrant daily).

I've been getting in the habit of using `vagrant up --debug`, but for some reason the problem only seems to occur if I leave the `--debug` flag out (probably coincidence, since sometimes I forget), so I can't point you to the cause of these problems...

I'm using Vagrant 1.6.5 on Arch Linux. I also had this problem on Ubuntu 12.04, and has been around since at least March (since I've been using Vagrant).

**Comment by belerophon** [comment]
This also happens to me, on Gentoo. Every time.

**Comment by derek-adair** [comment]
This has been an intermittent issue for me as well, was actually about to file this one yesterday.  It's gone from 2x > normal behavior > 2x > 4x.

**Comment by artjomsimon** [comment]
This is most probably caused by #5957 - /etc/exports isn't being overwritten by the cleaned-up file, because it lacks sudo permissions, causing the file being cluttered with the same entries.

**Comment by michaelherold** [comment]
I'm not sure @artjomsimon's diagnosis is 100% right. I'm running 1.7.4 -- which includes the fix for #5957 -- and still experiencing this issue.

**Comment by brad** [comment]
What the proper workaround? Manually remove vagrant entries from `/etc/exports` and run `vagrant reload`? Seems to be working for me

**Comment by haggaie** [comment]
This seems to be happening to me on a multi-machine setup. I'm sharing the same folder with both machines so I'm getting the same export twice (once per IP address).

**Comment by calvez** [comment]
Still the same problem. I have only one machine now, others already cleaned. 
but the problem started with mult-setup, right @haggaie 
```
╰─ vagrant up 
Bringing machine 'drupalvm' up with 'virtualbox' provider...
==> drupalvm: Checking if box 'geerlingguy/ubuntu1604' is up to date...
==> drupalvm: Clearing any previously set network interfaces...
==> drupalvm: Preparing network interfaces based on configuration...
    drupalvm: Adapter 1: nat
    drupalvm: Adapter 2: hostonly
==> drupalvm: Forwarding ports...
    drupalvm: 22 (guest) => 2222 (host) (adapter 1)
==> drupalvm: Running 'pre-boot' VM customizations...
==> drupalvm: Booting VM...
==> drupalvm: Waiting for machine to boot. This may take a few minutes...
    drupalvm: SSH address: 127.0.0.1:2222
    drupalvm: SSH username: vagrant
    drupalvm: SSH auth method: private key
==> drupalvm: Machine booted and ready!
[drupalvm] GuestAdditions 5.0.24 running --- OK.
==> drupalvm: Checking for guest additions in VM...
==> drupalvm: [vagrant-hostsupdater] Checking for host entries
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 www.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 adminer.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 xhprof.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 pimpmylog.drupalvm.dev
==> drupalvm: [vagrant-hostsupdater]   found entry for: 192.168.88.88 dashboard.drupalvm.dev
==> drupalvm: Setting hostname...
==> drupalvm: Configuring and enabling network interfaces...
==> drupalvm: Exporting NFS shared folders...
==> drupalvm: Preparing to edit /etc/exports. Administrator privileges will be required...
● nfs-server.service - NFS server and services
   Loaded: loaded (/lib/systemd/system/nfs-server.service; enabled; vendor preset: enabled)
   Active: active (exited) since k 2016-09-06 14:32:32 CEST; 28s ago
  Process: 6875 ExecStart=/usr/sbin/rpc.nfsd $RPCNFSDARGS (code=exited, status=0/SUCCESS)
  Process: 6872 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=0/SUCCESS)
 Main PID: 6875 (code=exited, status=0/SUCCESS)

szept 06 14:32:32 ThinkPad systemd[1]: Starting NFS server and services...
szept 06 14:32:32 ThinkPad exportfs[6872]: exportfs:         192.168.88.88:/home/clvz/workspace/vagrant/om-drupalvm
szept 06 14:32:32 ThinkPad exportfs[6872]: exportfs:         192.168.88.88:/home/clvz/workspace/vagrant/om-drupalvm
szept 06 14:32:32 ThinkPad systemd[1]: Started NFS server and services.
exportfs: duplicated export entries:
exportfs: 	192.168.88.88:/home/clvz/workspace/vagrant/om-drupalvm
exportfs: 	192.168.88.88:/home/clvz/workspace/vagrant/om-drupalvm
==> drupalvm: Mounting NFS shared folders...

```

and after --debug:

```
DEBUG ssh: Exit status: 32
 INFO retryable: Retryable exception raised: #<Vagrant::Errors::LinuxNFSMountFailed: The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o 'vers=3,udp' 192.168.88.1:'/home/clvz/workspace/vagrant/om-drupalvm' /var/www/drupalvm
```

**Comment by arturolinares** [comment]
Any workaround? I tried manually editing /etc/exports with no luck. Might be a coincidence, but I'm also using geerlingguy/ubuntu1604 box.

**Comment by michaelherold** [comment]
FWIW, this problem _usually_ happens to me when I have two `vagrant up|halt` running at the same time. In that case, I think it's a race condition between the two processes that causes the duplicated entries.

**Comment by patrickocoffeyo** [comment]
@arturolinares I'm having the same issue. Did you find a workaround?

**Comment by arturolinares** [comment]
Not really. I reinstalled vagrant and the error was still there, but the VM was functional.

De: Patrick Coffey <notifications@github.com>
Responder a: mitchellh/vagrant <reply@reply.github.com>
Fecha: martes, 13 de junio de 2017, 10:56
Para: mitchellh/vagrant <vagrant@noreply.github.com>
CC: Arturo Linares Goenaga <arturo.linares@gmail.com>, Mention <mention@noreply.github.com>
Asunto: Re: [mitchellh/vagrant] Double entries in /etc/exports (#4666)


@arturolinares<https://github.com/arturolinares> I'm having the same issue. Did you find a workaround?

**Comment by xtr3m3b00t3r** [comment]
I believe I'm having the same issue when trying to "vagrant up". 

`● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Mon 2017-07-31 20:35:36 BST; 5min ago
  Process: 5125 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCESS)
  Process: 5124 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCESS)
  Process: 5123 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=1/FAILURE)

Jul 31 20:35:36 apollo systemd[1]: Starting NFS server and services...
Jul 31 20:35:36 apollo exportfs[5123]: exportfs: duplicated export entries:
Jul 31 20:35:36 apollo exportfs[5123]: exportfs:         192.168.88.88:/hom…l-vm
Jul 31 20:35:36 apollo exportfs[5123]: exportfs:         192.168.88.88:/hom…l-vm
Jul 31 20:35:36 apollo systemd[1]: nfs-server.service: Control process exit…us=1
Jul 31 20:35:36 apollo systemd[1]: Stopped NFS server and services.
Jul 31 20:35:36 apollo systemd[1]: nfs-server.service: Unit entered failed …ate.
Jul 31 20:35:36 apollo systemd[1]: nfs-server.service: Failed with result '…de'.
Hint: Some lines were ellipsized, use -l to show in full.
Job for nfs-server.service canceled.
==> drupalvm: Mounting NFS shared folders...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

mount -o vers=3,vers=3 192.168.88.1:/home/ben/Documents/sayidoo/Development/drupal-vm /var/www/drupalvm

Stdout from the command:



Stderr from the command:

mount.nfs: requested NFS version or transport protocol is not supported
`

I can't run nfs-server.service manually either, it fails with the same

`● nfs-server.service - NFS server and services
   Loaded: loaded (/usr/lib/systemd/system/nfs-server.service; enabled; vendor p
   Active: failed (Result: exit-code) since Mon 2017-07-31 20:41:22 BST; 7min ag
  Process: 8138 ExecStopPost=/usr/sbin/exportfs -f (code=exited, status=0/SUCCES
  Process: 8135 ExecStopPost=/usr/sbin/exportfs -au (code=exited, status=0/SUCCE
  Process: 8134 ExecStartPre=/usr/sbin/exportfs -r (code=exited, status=1/FAILUR

Jul 31 20:41:22 apollo systemd[1]: Starting NFS server and services...
Jul 31 20:41:22 apollo exportfs[8134]: exportfs: duplicated export entries:
Jul 31 20:41:22 apollo exportfs[8134]: exportfs:         192.168.88.88:/home/ben
Jul 31 20:41:22 apollo systemd[1]: nfs-server.service: Control process exited, c
Jul 31 20:41:22 apollo systemd[1]: Stopped NFS server and services.
Jul 31 20:41:22 apollo systemd[1]: nfs-server.service: Unit entered failed state
Jul 31 20:41:22 apollo systemd[1]: nfs-server.service: Failed with result 'exit-`

I've removed the duplicated lines from /etc/exports, destroyed the vagrant vm, to vagrant up again only to have it put more duplicates in. Not sure whats going on.. I'm at the end of my rope. Any help on this would be much appreciated!

I'm running Antegos Linux.

**Comment by SchnWalter** [comment]
For me, double entries appear in `/etc/exports` because I have 2 mount points for the current directory (where the `Vagrantfile` is located). I'm mounting it inside the VM in `/vagrant` and `/var/www/example.com`

NOTE: If I'm adding three mount points for the same directory, it appears three times in `/etc/exports`.

Looking at the issue description and comments, you guys might have the same problem as me. Could you please check if the path in `/etc/exports` is shared with the VM in twice? Or maybe ad a 3rd mount point like this:
```
/vagrant
/var/www/project
/opt/project
```

**Comment by SchnWalter** [comment]
The code responsible for this issue is in [plugins/hosts/linux/cap/nfs.rb](https://github.com/mitchellh/vagrant/blob/v1.9.8/plugins/hosts/linux/cap/nfs.rb#L167). The `nfs_opts_setup(folders)
` method should make sure that the directories are unique, before they are passed to `Vagrant::Util::TemplateRenderer.render('nfs/exports_linux'`

**Comment by briancain** [comment]
Thanks so much for bringing this up @SchnWalter . I was finally able to reproduce this bug based on your comments above. I've opened #8945 to fix this bug.

**Comment by cristiroma** [comment]
Here is the patch for vagrant-1.9.1 shipped with Fedora 26, to apply:

```
$>sudo su
# cd /usr/share/vagrant/gems/gems/vagrant-1.9.1/plugins/hosts/linux/cap
# wget https://gist.githubusercontent.com/cristiroma/687d50dd06ccf09c9c2d2d27d3c9cd4f/raw/848f6d6422586bcc1775be432737bec593f72ab5/vagrant-issue-8666-1.9.1.patch
# patch -p1 < vagrant-issue-8666-1.9.1.patch
```
