### ISSUE TITLE
Repackaging (or unpackaging?) a large Vagrant box produces a corrupted box

### ISSUE THREAD

**Issue by gCardinal** [mitchellh/vagrant#4727]
There was [this issue](https://github.com/mitchellh/vagrant/issues/4299) written in August to which I commented about having a similar problem.

Since then I've been able to test a lot more about what could be the source of the problem. As a quick side note, I do not know any Ruby, so I did some quick looking around, but nothing too complete.

I got lucky once and managed to package a working box, so I'm assuming this means my machine can indeed package boxes properly.

First off, I'm on Windows 7 and here's the machine I'm trying to package:
* Based on: https://vagrantcloud.com/ferventcoder/boxes/win2008r2-x64-nocm
* Windows 2008 R2 x64
* The total weight of the box (before vagrant compresses it) is 34GB (got a bit heavier than last time).

This is the error I get:
```
The box failed to unpackage properly. Please verify that the box
file you're trying to add is not corrupted and try again. The
output from attempting to unpackage (if any):

x ./box-disk2.vmdk: Write failed
x ./box.ovf
x ./Vagrantfile
bsdtar.EXE: Error exit delayed from previous errors.
```

What I know did not help in solving this problem:
* I thought maybe the tools used to compress weren't doing the job properly and noticed in the source code that Vagrant will check if Cygwin is installed and use it if it is so I installed Cygwin. 
* Changed the way I packaged. From packaging via the VirtualBox's name, to the machine name in the Vagrantfile. Didn't change anything.
* I tried decompressing the .box to fetch the vmdk file (with 7-zip) to create a new VirtualBox machine and then package this one. That didn't work either.

I'm confused as to whether packaging or unpackaging is the problem since I can reach the vmdk within a corrupted box no problem, but then again if unpackaging was the problem I'm not sure the box I got lucky and managed to package would be able to be unpackaged that consistently (it never failed actually). Plus, packaging never fails.

I'm really not sure what's going on and what else I can try, but I don't mind giving more details if needed.

**Comment by mitchellh** [comment]
Sorry for such a late response here. During a couple version triages we were unable to get a repro case here. When we see `write failed` it usually means you ran out of disk space during the package. During packaging, Vagrant requires 2x the original space since it copies all files. 

Can you check if that caused it?

Otherwise, we're going to have to close this for now since we can't get a repro and we haven't heard more than these two cases. We would _love_ to fix it but more sleuthing is required from anyone getting this. Sorry!

**Comment by mrshanahan** [comment]
Ahh sorry, should have updated this a few weeks ago! We did indeed find that our issue was that we ran out of disk space, precisely because of the 2x disk space usage. Thanks!
FYI - we kept thinking that it was an import issue since we weren't getting any indication of error on a bad packaging attempt; should Vagrant be complaining if that happens?

**Comment by baldursson** [comment]
I'm on a Mac and had this issue. Thought is was because I was running out of space, but then I realized I had missed this disclaimer when downloading the box from Microsoft: 

> Mac Users: You need to use a tool that supports zip64 like The Unarchiver to unzip the files.  

It was as easy as that.

**Comment by luiscastillocr** [comment]
@baldursson what exactly did you do? it just happened to me, I am on Windows and exported a box for a coworker that uses MAC
