### ISSUE TITLE
Hostname Bug in EL7

### ISSUE THREAD

**Issue by whiteadam** [mitchellh/vagrant#4804]
This isn't a bug with Vagrant, but just FYI for anyone having an issue, update systemd.

Vagrant sets the hostname with the following (which IS the proper way):
```hostnamectl set-hostname #{fqdn}```

but the systemd currently shipping with the EL7 ISOs (systemd-208-11.el7) will not report the fqdn when running the following:
```hostname -f```

This bug is fixed in systemd-208-11.el7_0.4

Hope it helps,
-Adam

**Comment by sethvargo** [comment]
Hi @whiteadam 

Thank you for opening an issue. Since this has been fixed upstream, I'm not sure what we can do in Vagrant other than display a nicer error message. Since this is already fixed though, I am going to close this issue and direct others here if they experience the issue :smile:. Thank you for the report. If you disagree with my assessment, we can definitely revisit this :smile:.

**Comment by whiteadam** [comment]
No problem @sethvargo . Thanks for giving back to the community and cleaning up these old issues :+1:
