### ISSUE TITLE
`vagrant-mounted` is fired prematurely

### ISSUE THREAD

**Issue by immunda** [mitchellh/vagrant#4814]
I'm trying to start a `docker` upstart script after `vagrant-mounted` has been fired as my containers rely on a synced folder.

In order to track down what exactly was going wrong, I created a test service as follows:

```
description "Test"
author "Me"
start on filesystem and vagrant-mounted
stop on runlevel [!2345]
respawn
script
  echo `ls /synced/folder/location` > /tmp/test_out
end script
```

This is successfully fired, but shows the output of `/tmp/test_out` to be an empty `ls` command. If I run this command when logged in soon after, at that point the synced folder has been successfully mounted.

Details:

Host: Mac OSX 10.9.5
Guest: Ubuntu 14.04.1
Vagrant: 1.6.5

Certainly happy to provide any more info.

**Comment by mitchellh** [comment]
Hm, we fire the event after the mount command. I haven't been able to reproduce this locally, however I'm open to any suggestions you may have, since all the events are fired after the path is launched.

One issue: we fire the event for _each_ shared folder. So perhaps it is being fired before the proper shared folder. We set the MOUNTPOINT var to specify which.
