### ISSUE TITLE
Windows Guest: Folder Sharing - Escape passwords

### ISSUE THREAD

**Issue by kadaan** [mitchellh/vagrant#4849]
When cmdkey is run in mount_share_folder.sb, the password is not escaped and not surrounded in quotes.  This causes vagrant up for some users to timeout as the cmdkey command is waiting for user input.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
