### ISSUE TITLE
Configure DNS server for host on host-only network interface

### ISSUE THREAD

**Issue by techtonik** [mitchellh/vagrant#4863]
This is a revised #4361. The problem I am trying to solve is to get access to development web server that uses multiple subdomains. For that you need a DNS server that can serve development zone. I don't want to use external DNS, so I setup a DNS server on host-only network, but host doesn't query it without manual configuration of network interface (tested on Windows).

It would be nice if Vagrant supported manual configuration of DNS server for host network adapter on host-only virtual network interface:
```
Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.50.4", dns: "192.168.50.10"
end
```

**Comment by mitchellh** [comment]
Please use `auto_config: false` and just manually configure for this.

**Comment by techtonik** [comment]
@mitchellh do you know another VirtualBox wrapper on Windows that allows to set DNS server for newly created network interface? Doing stuff by hand is not something that I expect from automation solution, so maybe I am just using the wrong tool.

**Comment by mitchellh** [comment]
@techtonik The issue is that there are a LOT of permutations of network configurations that are available, so we bring in 1st class support for a few, but we can't support them all. DNS servers are pretty guest OS specific so this is something we want to avoid. 

There isn't any tool to do this, but it is probably a shell script one-liner for provisioning (the issue for us being that that one line is different for most OS's).

**Comment by techtonik** [comment]
This is not about guest DNS configuration. It is about configuring host network interface to recognize that there is DNS server running in Guest for specified subnet. There is are no more options there, except maybe gateway,

**Comment by alexisrosano89** [comment]
I've the same problem too
