### ISSUE TITLE
Vagrant ignores default provider which bringing up a specific machine in multi-machine environment

### ISSUE THREAD

**Issue by schmunk42** [mitchellh/vagrant#4899]
I have this in my Vagrantfile

```
ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'
```

But when I want to start one container the setting is ignored:

```
Kraftbuch:app tobias$ vagrant up db
Bringing machine 'db' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* A box must be specified.
```

Starting all containers works as expected though.

```
Kraftbuch:app tobias$ vagrant up
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'db' up with 'docker' provider...
Bringing machine 'proxy' up with 'docker' provider...
```

Running Vagrant 1.6.5

**Comment by mitchellh** [comment]
@odigity For you specifically: that won't work. Vagrantfile is loaded long after Vagrant has chosen the default provider. ENV variables must be set _before_ `vagrant` is run.

**Comment by mitchellh** [comment]
Oh, this actually explains everything. ENV  vars can't be set in the Vagrantfile. I missed that detail in the original comment. Any environmental variables to control Vagrant must be set prior to invocation. 

If you show me your Vagrantfile, I can attempt to comment why specific VMs are using VirtualBox rather than Docker.

**Comment by p-l-** [comment]
The thing is the statement `ENV['VAGRANT_DEFAULT_PROVIDER'] = 'docker'` from the Vagrantfile seems to be effective when running `vagrant up` but not when running `vagrant up vmname`.

**Comment by mitchellh** [comment]
Yeah that is odd, but it isn't a bug. Both behaviors are undefined since this is not a feature of Vagrant, and therefore as undefined behaviors, they're both "correct" technically, though obviously incorrect from a user perspective. 

Perhaps it is worth adding a check if any environmental variables change during the load of a `Vagrantfile` to show a warning... that might help the UX inconsistency.

**Comment by odigity** [comment]
@mitchellh -- That would help prevent people from making the mistake of attempting to set env vars in the Vagrantfile, sure.

But that still doesn't answer the questions of:
1) Why does 'vagrant up' work (uses the correct provider for the box, libvirt in my case), but 'vagrant up <node>' doesn't?  (defaults back to virtualbox)
2) What's the correct work-around?

**Comment by odigity** [comment]
To others experiencing the same problem:

In the meantime, what worked for me was adding the following to ~/.bashrc and reopening all my terminals:

    export VAGRANT_DEFAULT_PROVIDER=libvirt
