### ISSUE TITLE
Vagrant 1.7.0 - Ubuntu 14.04 Host - Provisioner Naming Fails on Vagrant up

### ISSUE THREAD

**Issue by sschafft** [mitchellh/vagrant#4949]
For some reason the vagrant up --provision-with XX seems to fail but works with vagrant provision. 

See video here: https://www.youtube.com/watch?v=U5I-l64VS6Q

Documentation both through vagrant up -h and the vagrant site seem to specify that this _should_ work. 

Documentation from site (https://docs.vagrantup.com/v2/provisioning/basic_usage.html):

"The --provision-with flag can be used if you only want to run a specific provisioner if you have multiple provisioners specified. For example, if you have a shell and Puppet provisioner and only want to run the shell one, you can do vagrant provision --provision-with shell. The arguments to --provision-with can be the provisioner type (such as "shell") or the provisioner name (such as "bootstrap" from above)."

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to inactivity. If this is still occurring, please open a _new_ issue with the complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)? Please also be sure to run the latest version of Virtualbox and Vagrant. Thanks! :smile:
