### ISSUE TITLE
Error: VBoxManage.exe: error: The host network interface with the given name could not be found"

### ISSUE THREAD

**Issue by chaliy** [mitchellh/vagrant#4970]
I am trying to setup small test cluster of windows machines with DHCP private_network, my Vagrantfile:

```ruby
    # -*- mode: ruby -*-
    # vi: set ft=ruby :
    
    Vagrant.configure(2) do |config|
      config.vm.box = "mwrock/Windows2012R2"
    
      config.vm.network "private_network", type: "dhcp"
    
      config.vm.provider "virtualbox" do |vb|
        vb.gui = true
        vb.memory = 4096
      end
    end
```

Unfortunately, `vagrunt up` give me:

    $ vagrant up
    Bringing machine 'default' up with 'virtualbox' provider...
    ==> default: Checking if box 'mwrock/Windows2012R2' is up to date...
    ==> default: Clearing any previously set network interfaces...
    There was an error while executing `VBoxManage`, a CLI used by Vagrant
    for controlling VirtualBox. The command and stderr is shown below.
    
    Command: ["hostonlyif", "ipconfig", "VirtualBox Host-Only Ethernet Adapter #11", "--ip", "172.28.128.1", "--netmask", "255.255.255.0"]
    
    Stderr: VBoxManage.exe: error: The host network interface with the given name could not be found
    VBoxManage.exe: error: Details: code E_INVALIDARG (0x80070057), component Host, interface IHost, callee IUnknown
    VBoxManage.exe: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
    VBoxManage.exe: error: Could not find interface 'VirtualBox Host-Only Ethernet Adapter #11'

So for every `vagrant up` it tries to create new VirtualBox Host-Only Ethernet Adapter, fail and obviously does not even start box.

Host machine is Windows, provider is VirtualBox.

ipconfig output

    Ethernet adapter VirtualBox Host-Only Network:
    
       Connection-specific DNS Suffix  . :
       Description . . . . . . . . . . . : VirtualBox Host-Only Ethernet Adapter
       Physical Address. . . . . . . . . : 08-00-27-00-18-ED
       DHCP Enabled. . . . . . . . . . . : No
       Autoconfiguration Enabled . . . . : Yes
       Link-local IPv6 Address . . . . . : fe80::1df4:f75f:22ea:96a2%22(Preferred)
       IPv4 Address. . . . . . . . . . . : 192.168.56.1(Preferred)
       Subnet Mask . . . . . . . . . . . : 255.255.255.0
       Default Gateway . . . . . . . . . :
       DHCPv6 IAID . . . . . . . . . . . : 419954727
       DHCPv6 Client DUID. . . . . . . . : 00-01-00-01-1C-03-5E-90-28-D2-44-54-EB-D1
       DNS Servers . . . . . . . . . . . : fec0:0:0:ffff::1%1
                                           fec0:0:0:ffff::2%1
                                           fec0:0:0:ffff::3%1
       NetBIOS over Tcpip. . . . . . . . : Enabled

**Comment by Hinnack** [comment]
I have the same problem on OSX

==> win: Clearing any previously set network interfaces...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["hostonlyif", "ipconfig", "dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp", "--ip", "192.186.100.1", "--netmask", "255.255.255.0"]

Stderr: VBoxManage: error: The host network interface with the given name could not be found
VBoxManage: error: Details: code NS_ERROR_INVALID_ARG (0x80070057), component Host, interface IHost, callee nsISupports
VBoxManage: error: Context: "FindHostNetworkInterfaceByName(name.raw(), hif.asOutParam())" at line 218 of file VBoxManageHostonly.cpp
VBoxManage: error: Could not find interface 'dyld: DYLD_ environment variables being ignored because main executable (/Applications/VirtualBox.app/Contents/MacOS/VBoxNetAdp'

strange interface name. I thought I fix that DYLD_ bug on my system by unsetting the var:
unset DYLD_LIBRARY_PATH
the bug is described here: http://openradar.appspot.com/11894054 (just for the record)
This may have nothing to do with the problem at all…

**Comment by forivall** [comment]
I'm having the same issue, trying to use the coreos image https://gist.github.com/forivall/a4454010cb06d3836660

**Comment by forivall** [comment]
I figured out my problem, which was more of a virtualbox problem, (also windows only): I had an old version of the virtualbox network driver installed; I found and deleted it with this method: https://technet.microsoft.com/en-us/library/cc730875.aspx

**Comment by riyunoa** [comment]
Hi @forivall I have the same problem. But when I do "pnputil.exe -e" I have a few different versions of the Oracle Virtualbox driver - which one did you know to remove? Thanks in advance. :)

**Comment by AustinPalmer** [comment]
@riyunoa just remove the oldest one. Mine had 2 from 2015 and one from 2014. getting rid of the 2014 entry did the job for me.

**Comment by forivall** [comment]
Yup, just the oldest ones.

**Comment by Serphiroth** [comment]
Take a look at this topic :
http://stackoverflow.com/questions/31765581/the-host-network-interface-with-the-given-name-could-not-be-found/31856846#31856846

**Comment by lalten** [comment]
I had this error because my *VirtualBox Host-Only Network* network adapter was disabled in the network connections. Enabling it resolved the issue.

**Comment by mitchellh** [comment]
This turned out to be a VirtualBox bug. Update and this should be fixed.

**Comment by VikasBains** [comment]
Hi,
I have updated latest vagrant and virtual box but still same issue.
I have also commented on https://github.com/mitchellh/vagrant/issues/6120 ...with details
