### ISSUE TITLE
vagrant ssh Couldn't reserve space for cygwin's heap

### ISSUE THREAD

**Issue by sydneyhenrard** [mitchellh/vagrant#5099]
When I run `vagrant ssh`, I get

```
D:\vm\ionic-box-master>vagrant ssh
C:\Program Files (x86)\Git\bin\ssh.EXE: *** Couldn't reserve space for cygwin's heap, Win32 error 0
      0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
AllocationBase 0x0, BaseAddress 0x68570000, RegionSize 0x2E0000, State 0x10000
C:\Program Files (x86)\Git\bin\ssh.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
```

**Comment by mitchellh** [comment]
This doesn't look like Vagrant can do anything here. Vagrant is simply doing an `exec("ssh")`, and is letting the kernel handle how that happens. 

If you can find a way to fix this and you feel like Vagrant should be abel to do that, then let me know and I'll take a look. But these errors are not coming because of Vagrant. Some basic tests: does that ssh.exe work properly outside of Vagrant? If so, perhaps environmental variables set by Vagrant are messing things up?

**Comment by sydneyhenrard** [comment]
This fixed it:

```
C:\Program Files (x86)\Git\bin> rebase.exe -b 0x50000000 msys-1.0.dll
```

**Comment by ashukaul** [comment]
I was getting the same err, when I was running 'vagrant ssh' from cmder

Not sure if this would help anybody, But for me the upper fix didn't work, what work was replacing the myss-1.0.dll with the one given in the below link 

http://www.support.code-red-tech.com/CodeRedWiki/VirtualAllocPointerNull?action=AttachFile&do=view&target=msys-1.0.zip
replaced the myss dll at the below location : 
C:\Users\<username>\cmder\vendor\msysgit\bin\mys-1.0.dll 
and it worked.
