### ISSUE TITLE
Vagrant gets confused if you provision more than one VM at a time

### ISSUE THREAD

**Issue by ferventcoder** [mitchellh/vagrant#5112]
I saw this with Windows, where suddenly I was running commands against the wrong box. I provisioned them at the same time in two different terminals. FWIW I used to do this with 1.5.4 and didn't come into this issue. On 1.6.5 I've seen this a few times. Is there some globals that are getting shared?

**Comment by mitchellh** [comment]
Vagrant still doesn't officially support this use case. As you said, there are issues with globals. We've been eliminating any as we find them. What provider is this with? 

I'm going to close this issue because it is an ongoing work, but with no clear deliverable goal/time.

If you can find specific areas of issue though, we'll continue to fix those towards this goal.

**Comment by ferventcoder** [comment]
Right on, wasn't sure if it was allowed or not. :)

**Comment by ferventcoder** [comment]
Virtualbox is the provider I see it with.

**Comment by ferventcoder** [comment]
I'd file my 2003 vagrant box issue, but I know Windows 2003 isn't officially supported. I may be the only owner of a 2003 vagrant box. :)

**Comment by mitchellh** [comment]
Heh, its probably not a guest issue. Its probably just some shared state somewhere in Vagrant core. If you can ever figure it out, let me know and I'll smush it.
