### ISSUE TITLE
Vagrant shared folder is shit on windows

### ISSUE THREAD

**Issue by fresheneesz** [mitchellh/vagrant#5161]
I understand there are complexities with supporting an NTFS filesystem in linux, but this is driving me crazy. I'm currently working around this mess by using a filewatcher running in the guest that watches files in the shared folder and copies them to a directory in the pure linux filesystem (and back for specific files/directories). I can't watch the *whole* shared folder tho, because the watcher takes too long to copy stuff, so my script has a somewhat complicated set of definitions for what to copy where. But recently I've been noticing more and more that my filewatcher workaround is very often failing to correctly fucking update files on the linux side. 

As you can probably tell by frequent use of swear words, I'm pretty pissed off at the workflow this is forcing me into. Sometimes I spend 15 minutes looking into a bug, and then finding out my file didn't copy over right, so the code i'm looking at is NOT the code that's running. I need a way to develop for linux on windows that doesn't make me want to go on a killing spree. Does anyone have such a workflow? Regardless this ticket is about making the windows shared folder experience on vagrant NOT a nightmare, like it is right now. Or at least like it is on vagrant v1.6.3 on windows 8.1 (centos 6.5 guest), which is what I'm using.

**Comment by mitchellh** [comment]
Hi, I'm sorry you're frustrated. And I apologize for censoring a bit here but I modified your issue to remove the swear words. I don't find them constructive and they only usually make more people angry, which also isn't helpful to finding and solving the real issue. Your frustration is well heard, but let's behave as adults.

I don't have good news for you though. Vagrant doesn't do anything related to enabling synced folders so much as configuring other systems. I'm guessing/assuming that you're just using the built-in VirtualBox shared folders. These are known to be quite slow, and I even did some work and benchmarking around the various synced folder mechanisms Vagrant can configure, you can see them here: http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines

I just want to reiterate that Vagrant is not the system doing the folder sharing, it is just the system configuring your shared folders. We don't have access to the underlying shared folder systems, which are the responsibility of other software packages (VirtualBox, VMware, Rsync, NFS, Windows for SMB, etc. etc.)

There is no _perfect_ option, there are just tradeoffs. Example: the pure virtual disk is quite fast (as you can see in the benchmark), so we have an rsync synced folder to get your data to a virtual disk. The pro here is that its fast to access on the guest, the con is that there is a latency to waiting for the file to sync over there. Another pro is that `rsync-auto` will only sync what changes, and uses WDM to be quite fast. But compare to VirtualBox shared folders: the pro is that they *just work*, the con is that as the number of files/folders increases they become very slow to a point where for some people they *don't work*. 

You'll have to weigh these pros/cons and choose the one that works best for you.

For years we've looked into any knobs we can tune to make certain synced folders faster and we do our best there from what we know today. If there are any we're missing, let us know and we'll bring em in. But besides that, the best we can do is offer you choice.

The choices are documented, and the benchmark should help weigh your choice. But remember there is no panacea (unfortunately) and there will be tradeoffs for each. 

With that, I'm going to close this since I see no directly actionable tasks that we can take as a project other than continuing to introduce synced folder options as we see them. Let me know if you have an idea and if so we can reopen the issue and perhaps rename it to be more targeted.

**Comment by fresheneesz** [comment]
@mitchellh What if a filesystem that's both guest- and host- compatible is run on the host, and all development done in there? Then shared folders wouldn't be super bizarre on the vagrant side right?

**Comment by mitchellh** [comment]
@fresheneesz That would work quite well, but we haven't found such a system yet.

**Comment by fresheneesz** [comment]
Maybe UDF? http://unix.stackexchange.com/questions/59585/file-system-compatible-with-all-oses

**Comment by mitchellh** [comment]
That is pretty interesting. I've never heard of it but seems like it might be able to work. Most filesystems don't deal well with multiple people accessing it at one time (as in multiple distinct systems, a disk attached to multiple OSes). I'd have to research this more but this is an interesting alternative if Vagrant can automatically create another disk, copy files to it, and then mount that in the guest as well. 

I think this wouldn't work right now, we'd need more core work in place to support this sort of synced folder. But thanks for pointing it out, and we should be able to get there.

**Comment by thasmo** [comment]
Sounds very interesting!

**Comment by patricknelson** [comment]
Given my frustrations thus far being a developer on Windows host machines and working in linux environments (particularly with `node.js`'s, really `npm`'s, extremely long file paths and symlinks) this could be a tremendous life saver. Another major benefit would (hopefully) be speed. Should provide much better consistency and (hopefully) reduced complexity over `rsync` (since I haven't been able to get it to not crash when doing heavy operations like moving large amounts of files, etc -- separate discussion).

Also wanted to post here since I wanted to publicly :+1: this and be notified of progress :smile:

**Comment by patricknelson** [comment]
p.s. Since this issue is closed, are there still (or could there still be) plans to support UDF in Vagrant?
