### ISSUE TITLE
Starting vagrant through cygwin clobbered my guest machine

### ISSUE THREAD

**Issue by fresheneesz** [mitchellh/vagrant#5163]
Trying to get an rsync shared folder to work, i started up vagrant through cygwin, but it looks like the machine is completely fresh. None of the commands I had installed are installed anymore, and my whole home directory is empty. What happened??

vagrant v1.6.3 on host windows 8.1, guest centos 6.5

**Comment by mitchellh** [comment]
Hm, this sounds like an issue with VirtualBox that we're aware of. We have another Vagrant issue (don't know the number off the top of my head) for making a heuristic to try to detect the scenarios this will happen and warn the user. 

The issue here (I think) is that your normal shell and your cygwin shell are running as different Windows users (usually admin and not admin). VirtualBox scopes all your VMs by user, so when you switch users, Vagrant _cant_ see the other VM anymore, and "deletes" it. More correctly: Vagrant just loses the reference to it. The VM itself should exist in VirtualBox when it is launched by the other user still. 

Is this the case? Can you reliably reproduce this multiple times? If so, it would help to get a debug log (`--debug` and gist it) so we can see what Vagrant is thinking and why its clobbering the other machine.

**Comment by fresheneesz** [comment]
I can try again, but i'd like to know when in the process exactly you'd like me to get a debug log (i assume that's with `vagrant up --debug`). 

So when I try to bring up the machine again from the normal windows console, I get this:

```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Clearing any previously set forwarded ports...
There was an error while executing `VBoxManage`, a CLI used by Vagrant
for controlling VirtualBox. The command and stderr is shown below.

Command: ["showvminfo", "48fb079e-a168-49c2-b8ae-e305dfcf6d86", "--machinereadable"]

Stderr: VBoxManage.exe: error: Could not find a registered machine with UUID {48fb079e-a168-49c2-b8ae-e305dfcf6d86}
VBoxManage.exe: error: Details: code VBOX_E_OBJECT_NOT_FOUND (0x80bb0001), component VirtualBox, interface IVirtualBox, callee IUnknown
VBoxManage.exe: error: Context: "FindMachine(Bstr(VMNameOrUuid).raw(), machine.asOutParam())" at line 2610 of file VBoxManageInfo.cpp
```

Looks pretty clobbered to me. And shouldn't vagrant only care about the folder its started in and the associated data? Why should the user matter? I would assume multiple users could go in and start up the machine, as long as its being started up at different times.

**Comment by fresheneesz** [comment]
So here's a more detailed sequence of events:

1. `vagrant init backendCentos` on the normal windows cmd window
2. `vagrant up` - normal cmd window:
    ```
Bringing machine 'default' up with 'virtualbox' provider...
==> default: Importing base box 'backendCentos'...
==> default: Matching MAC address for NAT networking...
==> default: Setting the name of the VM: backend_default_1420869976352_51619
==> default: Clearing any previously set network interfaces...
==> default: Preparing network interfaces based on configuration...
    default: Adapter 1: nat
==> default: Forwarding ports...
    default: 22 => 2222 (adapter 1)
==> default: Booting VM...
==> default: Waiting for machine to boot. This may take a few minutes...
    default: SSH address: 127.0.0.1:2222
    default: SSH username: vagrant
    default: SSH auth method: private key
    default: Warning: Connection timeout. Retrying...
==> default: Machine booted and ready!
==> default: Checking for guest additions in VM...
==> default: Mounting shared folders...
    default: /vagrant => D:/billysFile/IDEAS/Tixit/backend
```
3. I log in via PuTTY
4. I do `sudo touch /BTWasHere` in putty
5. `vagrant halt` on the normal cmd window
6. `vagrant up --debug` in cygwin (same folder) [debug logs](http://www.filedropper.com/6vagrantup--debugincygwinsamefolder)
7. I log in via PuTTY
8. I check the root - the file BTWasHere is no longer there
9. I do `sudo touch /BTWasHere2`
10. `vagrant halt` on cygwin
11. `vagrant up --debug` in the normal cmd window aaaand of course windows console doesn't have enough buffer by default to show me even a quarter of the logs, but hopefully the cygwin ones are the ones you're interested in.
12. I log back in, and the BTWasHere2 file is no longer there. Seems like in both directions, one clobbers the other. 

Hope this helps. This is pretty terrible, clobbering someone's whole machine just cause the load it up in a different environment. Luckily I have very automated processes - takes me like 10 minutes to get it all back up and running. Other people's set ups may be more manual.

**Comment by mitchellh** [comment]
Yeah this is looking like VirtualBox's normal behavior in different shells. It is caused by one of two things (or both happening at once): your user is changing or your home directory is changing (both unrelated to Vagrant).

The reason why is because the ".vagrant" folder Vagrant has only stores the _metadata_ about the VM for VirtualBox since VirtualBox manages the data and actual configuration for the VM. For other hypervisors like VMware or Hyper-V, Vagrant actually stores the actual VM in ".vagrant" so that it can't be lost, but for VirtualBox it is a little trickier so we're prevented from cleanly doing that.

So, for VirtualBox, Vagrant is seeing just a UUID of the VM in the ".vagrant" folder. It is then asking VirtualBox to look up this UUID, and VirtualBox uses your home directory and user to look up the VM, and if either have changed, it won't be found, and the error above is shown.

As I said in my first comment, there is another issue somewhere around here still open where we're planning on introducing some heuristic. Effectively, we're going to store the VB data folder alongside the UUID, and if that doesn't match what VirtualBox is reporting as its folder, then we're going to show an error instead of assuming the VM doesn't exist. 

The interim solution is to make sure to use Vagrant from just one of your consoles. Sorry about this, and sorry you're running into these terrible issues. They're generally edge cases (Windows is our largest user base and we rarely run into this) but you seem to be getting bit!

**Comment by fresheneesz** [comment]
Ahh, ya its been a rough day ; ) . Thanks for the help
