### ISSUE TITLE
ssh auth_methods is missing keyboard-interactive

### ISSUE THREAD

**Issue by ben0x4a** [mitchellh/vagrant#5178]
I am using vagrant for testing puppet code for server configuration. One of our audit requirements for the servers is two-factor auth. This auth requires ssh to use publickey and keyboard-interactive authentication methods. When "RequiredAuthentications2 publickey,keyboard-interactive" is added to sshd_config, "vagrant provision" fails with:

        Guest-specific operations were attempted on a machine that is not
        ready for guest communication. This should not happen and a bug
        should be reported.

I tracked this down to plugins/communicators/ssh/communicator.rb  line 327 (https://github.com/mitchellh/vagrant/search?utf8=%E2%9C%93&q=auth_methods&type=Code):

        auth_methods: ["none", "publickey", "hostbased", "password"],

Adding "keyboard-interactive" to the array fixes the issue.

        auth_methods:          ["none", "publickey", "hostbased", "password", "keyboard-interactive"],

**Comment by mitchellh** [comment]
We don't do keyboard interactive because we don't want interaction during a `vagrant up`. If you require this, please on bootstrap disable it, and then use an `ssh` directly afterwards. This isn't something we formally want to support right now. However, if you have an idea of what it would look like in Vagrant, then we can take a look.
