### ISSUE TITLE
Vagrant Cloud certificate not accepted by bundled curl

### ISSUE THREAD

**Issue by CyBeRoni** [mitchellh/vagrant#5229]
Hi,

The TLS cert Vagrant Cloud presents is not accepted by the embedded curl in Vagrant on OSX. This means anything related fails:

`$ /opt/vagrant/embedded/bin/curl https://vagrantcloud.com/`
 `curl: (60) SSL certificate problem: unable to get local issuer certificate`
 `More details here: http://curl.haxx.se/docs/sslcerts.html`
 `(etc, usual curl 'cert isn't trusted' output)`

This problem does not occur when the system curl (which is always available on osx, so I'm not sure why Vagrant even bundles it) is used.

**Comment by davebirch** [comment]
Not sure this is just an installer bug, been seeing the same (or very similar) issue today on 2 separate boxes running vagrant every time it tries to check the hashicorp/precise64 box.

Error message is like the following whenever I run a vagrant command which checks this box (which is essentially all of them!):

==> master: Checking if box 'hashicorp/precise64' is up to date...
==> master: There was a problem while downloading the metadata for your box
==> master: to check for updates. This is not an Error, since it is usually due
==> master: to temporary network problems. This is just a Warning. The problem
==> master: encountered was:
==> master: 
==> master: SSL certificate problem: unable to get local issuer certificate
==> master: More details here: http://curl.haxx.se/docs/sslcerts.html
==> master: 
==> master: curl performs SSL certificate verification by default, using a "bundle"
==> master:  of Certificate Authority (CA) public keys (CA certs). If the default
==> master:  bundle file isn't adequate, you can specify an alternate file
==> master:  using the --cacert option.
==> master: If this HTTPS server uses a certificate signed by a CA represented in
==> master:  the bundle, the certificate verification probably failed due to a
==> master:  problem with the certificate (it might be expired, or the name might
==> master:  not match the domain name in the URL).
==> master: If you'd like to turn off curl's verification of the certificate, use
==> master:  the -k (or --insecure) option.
==> master: 
==> master: If you want to check for box updates, verify your network connection
==> master: is valid and try again.

I've not changed anything my end and everything was working fine yesterday, seems to have started sometime this morning UK time. Apologies if this isn't the same issue, I'll happily raise a separate one, but the two do seem very related.

Currently running Vagrant 1.6.3 on both of the effected boxes.

**Comment by CyBeRoni** [comment]
Yes, it was OK yesterday. Technically the fault is in vagrantcloud.com which now only sends a leaf certificate but really I think Vagrant shouldn't be bundling curl. And I don't know where else to make this issue.

**Comment by sethvargo** [comment]
@CyBeRoni we are aware of this issue and are trying to get our certificates fixed as soon as possible. Please standby.

**Comment by sethvargo** [comment]
Hi there,

This seems to be an issue related with the ca bundler (see #5739 for more detailed information). We will be updating the bundle in the next release and the issue should go away. Sorry about the issue in the meantime - workaround instructions are in the linked issue! :smile:
