### ISSUE TITLE
Ansible Provisioning: --limit error

### ISSUE THREAD

**Issue by JGailor** [mitchellh/vagrant#5241]
Trying to provision a local development instance with virtualbox, vagrant, and ansible.  Using a simple setup with an inventory file, a playbook, and a vagrant file, the command that vagrant is trying to run for provisioning with ansible is:

```
PYTHONUNBUFFERED=1 ANSIBLE_FORCE_COLOR=true ANSIBLE_HOST_KEY_CHECKING=false ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s' ansible-playbook --private-key={my stuff, could be anything} --user=vagrant --connection=ssh --limit='default' --inventory-file=development webapp.yml
```

When this command runs I get the following error:

```
ERROR: provided hosts list is empty
Ansible failed to complete successfully. Any error output should be
visible above. Please fix these errors and try again.
```

If I run the command by hand and remove the --limit='default' (can't just remove the single quotes, have to remove the whole option), everything runs fine.

**Comment by JGailor** [comment]
This makes sense, but seems like it creates a case where you can't use ansible & vagrant to build a development environment without treating it as a special case.

In this case I do specify a static inventory file and playbook specifically selects groups from that inventory to run the play.  Is there any reason why I have to specify this again in Vagrant as the ansible.limit instead of just letting the provisioner run properly against the playbook?

**Comment by gildegoma** [comment]
For the design background: The general mechanism of `vagrant provision` has been originally implemented to provision one machine after another. So by default the ansible provisioner sets a reasonable limit, to keep from potentially hitting unexpected/wrong machines.

But if you know what you're doing with your static inventory+playbook settings, you can very simply disable this "prudent behaviour" by setting `ansible.limit = "all"` in your `Vagrantfile`. This way you don't repeat yourself, but you just instruct Vagrant to trust your ansible configuration files.

I hope this answers your question. Here is mine: have you already considered to use an auto-generated inventory approach instead of your static `development` inventory?

I would like to close this issue, but please tell me if there is anything still unclear, or wished.

**Comment by JGailor** [comment]
Giles, you've been awesome with helping with my misunderstanding of vagrant & explaining the rationale.   Thank you!

To answer your question, I considered using the auto-generated inventory from vagrant, but I decided against it a few important reasons to me.

1) I value the homogeneous nature of keeping my development inventory in a static file the same way I keep my staging & production inventories.  When bringing a new member on the team, esp. without Ansible experience, I have found it much easier to explain how each tool works if there aren't exceptions and edge cases (for staging / production, the inventory files look like this, for development they look like that).  I think of it as striving for simplicity and uniformity.  While it may be easier to use the vagrant file for specifying the inventory, I think it adds a downstream technical debt.

2) I like tools that have well-defined boundaries and do one thing exceptionally well.  I think Vagrant is amazing for managing local virtual machines, and I think Ansible is really awesome at managing the configuration of servers.  I love both tools but I like to keep the boundaries between the two of them clean.  If for some reason one of them stops working for a particular deployment scenario, I would to be able to switch one out without having to touch the other.  It's never that easy, of course, but it's something I strive for.

Please feel free to close the issue.  You've been very helpful and I've been able to work around my issue with your assistance.

**Comment by gildegoma** [comment]
@JGailor thanks for your great feedback :)

I close this one, but feel free to open more issues in the future. Happy Ansibling and Happy Vagranting!
