### ISSUE TITLE
Where are the .box files

### ISSUE THREAD

**Issue by bailey86** [mitchellh/vagrant#5254]
Hi,

Since I'm on Ubuntu I've got Vagrant 1.4.3 - so I need to install using the actual box_url.

If I'm looking on the https://atlas.hashicorp.com/boxes/search page - how do I find out the actual URL to the box file.

Especially, I'd like to install Debian 7 - but simply can't find the URL for the .box file.

Thanks.

**Comment by mitchellh** [comment]
Please ask these questions on the mailing list, as we reserve this for bug tracking of Vagrant itself.

We don't currently expose the direct box URL. You can add `.json` to the URL for now of a box and get the box URL for a specific provider there. This is safe to do since we have backwards compatibility requirements for prior versions of Vagrant that use this.
