### ISSUE TITLE
Removing a box from a deleted provider

### ISSUE THREAD

**Issue by iknite** [mitchellh/vagrant#5393]
Hi!

Trying to delete a box from an unknow provider is not suported. 

```
The provider 'kvm' could not be found, but was requested to
back the machine 'default'. Please use a provider that exists.
```

I've just uninstall the plugin `vagrant-kvm` before uninstaling the boxes, now I had to remove the files manually. 

Cheers & kudos

**Comment by sethvargo** [comment]
Hi @iknite 

Thank you for opening an issue, and sorry for the delay here. Unfortunately there is not much that Vagrant can do here besides maybe warn the user and suggest installing the plugin. The reason for this is that plugins are free to choose where they install "boxes" and how they are managed.

The reason I used "boxes" in quotes is because I'd like to draw your attention to the vagrant-aws provider. This provider does not actually manage any local box files and, instead, is used to manage boxes on AWS. In this case, Vagrant has no ability to "delete" a remote box, because only the provider knows how to communicate with AWS. 

Sorry! 😦
