### ISSUE TITLE
expose number of cpus and ram to vagrant config

### ISSUE THREAD

**Issue by tkellen** [mitchellh/vagrant#5402]
Would you be open to a PR that makes this available inside Vagrant.configure for any supported host? It seems like this is something that Vagrant should provide:

```ruby
LINUX = RUBY_PLATFORM =~ /linux/
OSX = RUBY_PLATFORM =~ /darwin/
WINDOWS = (/cygwin|mswin|mingw|bccwin|wince|emx/ =~ RUBY_PLATFORM) != nil
if OSX
  CPUS = `sysctl -n hw.ncpu`.to_i
  MEM = `sysctl -n hw.memsize`.to_i / 1024 / 1024
end
if LINUX
  CPUS = `nproc`.to_i
  MEM = `sed -n -e '/^MemTotal/s/^[^0-9]*//p' /proc/meminfo`.to_i / 1024
end
if WINDOWS
  CPUS = `wmic computersystem get numberofprocessors`.split("\n")[2].to_i
  MEM = `wmic OS get TotalVisibleMemorySize`.split("\n")[2].to_i / 1024
end
```

I use these constants to determine what percentage of ram or # of cpus to give the vm access to. I'm aware that the above is not complete, but I would be willing to work through the issues around it until we have something that works for any supported host.

**Comment by sethvargo** [comment]
Hrm. This is actually super interesting to me. I've used a similar script in the past for cross-team development. I think this brings up two interesting discussion points:

1. How close should you be to production?
2. How optimized should a local workstation be?

One of the guiding principles of Vagrant is that your development environment is as close in parity to production as possible. Does that extend to memory usage? If a production application is restricted to 2GB of RAM, should the associated development environment? I think, in practice, that rarely happens, but it's definitely something to consider here. If we start optimizing for 16GB RAM i7 processors on our Macs, but our application is actually run on a 2GB DigitalOcean droplet with shared CPU resources, are we potentially setting ourselves up for failure?

On a somewhat similar note, maybe Bill and Sandy have slightly different laptops. Since Sandy joined after Bill, she has the "newer" MBP with a better processor and slightly more RAM. Is it possible that code could "work on Sandy's machine" simply because her VM has more available resources? I don't know the answer to that, but it's food for thought.

I'll defer to @mitchellh, but I think we may like to see this as a plugin first. This will likely be implemented using [host capabilities](https://docs.vagrantup.com/v2/plugins/host-capabilities.html) if you need some guidance. FWIW, I would vote to name the values `available_*` (so `available_cpu`), etc.

I am interested to hear your thoughts here.

**Comment by tkellen** [comment]
It would be easy to cap the amount of ram or cpus you give a machine. This addition would be agnostic to what you actually set for the VM. The only goal here is to have the underlying data you need to not set things out of bounds cross-machine.

**Comment by mitchellh** [comment]
I agree we should see this as a plugin first. I'm hesitant to put this functionality in Vagrant right now. Please make a plugin!
