### ISSUE TITLE
error: vagrant up

### ISSUE THREAD

**Issue by igoreliasm** [mitchellh/vagrant#5408]
Have had this problem?

```
~/vagrant# vagrant up
VirtualBox is complaining that the installation is incomplete. Please
run `VBoxManage --version` to see the error message which should contain
instructions on how to fix this error.
``` 

Please...

**Comment by sethvargo** [comment]
Hi @igoreliasm 

What happens when you run:

    VBoxManage --version

What is the output?

**Comment by igoreliasm** [comment]
Hello @sethvargo 
The output is:
```
WARNING: The character device /dev/vboxdrv does not exist.
	 Please install the virtualbox-dkms package and the appropriate
	 headers, most likely linux-headers-generic.

	 You will not be able to start VMs until this problem is fixed.
4.3.18_Ubuntur96516
```

**Comment by sethvargo** [comment]
Hi @igoreliasm,

Unfortunately that means the issue is with VirtualBox. It looks like you need to install the `virtualbox-dkms` and probably `linux-headers-generic`. A quick google search found the following stackoverflow article that may be helpful: http://stackoverflow.com/questions/13291015/how-to-correct-virtualbox-installation
