### ISSUE TITLE
why global-status shows two vms while there is only one vm?

### ISSUE THREAD

**Issue by foresthz** [mitchellh/vagrant#5415]
![](http://img.itc.cn/photo/jmcy2OvCzGp.jpg)

http://img.itc.cn/photo/jmcy2OvCzGp.jpg

**Comment by sethvargo** [comment]
Hi there,

Vagrant's `global-status` command doesn't actively verify the state of the machines listed, and is instead based on a cache. Because of this, it is possible to see stale results (machines say they're running but they're not). For example, if you restart your computer, Vagrant wouldn't know. To prune the invalid entries, run global status with the `--prune` flag.

For more information, please see the [Vagrant Global Status documentation](http://docs.vagrantup.com/v2/cli/global-status.html)
