### ISSUE TITLE
has_plugin? returns true for uninstalled plugins

### ISSUE THREAD

**Issue by amosshapira** [mitchellh/vagrant#5417]
I'm testing code to auto-install plugins if they aren't found. The code uses, e.g. (simplified):

    unless vagrant.has_plugin?("puppet")
      system "vagrant plugin install puppet"
    end

If I execute `vagrant plugin uninstall puppet` and `vagrant plugin list` then I see that the `puppet` plugin isn't included in the output, but the code above will not trigger because `has_plugin?` still returns `true`.

When I try the same with `vagrant-aws` plugin it works as expected - `has_plugin?` returns `false` if I uninstall the plugin and triggers the re-install.

Is this because the `puppet` plugin comes built-in? Is there another way to get the information the way `vagrant plugin list` sees it?

**Comment by sethvargo** [comment]
Hi @amosshapira 

Thank you for opening an issue. Unfortunately it is not possible to uninstall the core plugins (like puppet). If there is a bug with the puppet plugin, please report it on the repo.

Since the puppet plugin comes packaged with Vagrant core, this check should be unnecessary. :smile:
