### ISSUE TITLE
Manual provider VM deletion leaves me unable to easily remove them from global-status registry

### ISSUE THREAD

**Issue by derek-adair** [mitchellh/vagrant#5428]
pretty nit-pcky, but worth filing IMO...

I've noticed a bunch of VMs creeping up in my vagrant global-status and i've finally nailed th culprit.  When you manually delete a VM from a provider it leaves the vagrant status of that VM untouched.... which is fine and to be expected, but the problem is i can't remove them from the global-status registry.

Whats more is the behavior is different for AWS / Virtualbox providers.

**Virtualbox**
==> Default: VM not create. Moving on....`

**AWS**
There are errors in the configuration of this machine. Please fix
the following errors and try again: 
                                                           
AWS Provider:                                   
* vagrant_aws.config.ami_required

-------
Its important to note that -f doesn't work here like i'd expect it, particularly with the AWS.  It seems like -f should just remove the VM from the vagrant registry **NO MATTER WHAT**, right?

Either way, I can work around the virtualbox provider by simply running `vagrant up <id>` and a `vagrant destroy <id>` after.  Not sure how to clean out these AWS VMs though...

**Comment by sethvargo** [comment]
HI @derek-adair 

As mentioned in the [Vagrant Global Status documentation](http://docs.vagrantup.com/v2/cli/global-status.html), `vagrant global-status` doesn't actively verify the state of the machines listed, and is instead based on a cache. Because of this, it is possible to see stale results (machines say they're running but they're not). For example, if you restart your computer, Vagrant wouldn't know. To prune the invalid entries, run global status with the `--prune` flag.

Does that make sense?

**Comment by derek-adair** [comment]
ah, nice!  That seems to solve the virtualbox issues i was having, although these pesky aws VMs are still hanging around.  Perhaps this is an issue with the AWS provider plugin?

```
➜  Dev/  vagrant global-status --prune
There are errors in the configuration of this machine. Please fix
the following errors and try again:

AWS Provider:
* vagrant_aws.config.ami_required
```

**Comment by sethvargo** [comment]
Hi @derek-adair,

That validation is coming from the Vagrantfile. It appears that the vagrant-aws plugin requires you specify a particular parameter. It looks like there's a bug and the error message is not displaying correctly. It should read:

    An AMI must be configured via "ami" (region: <region>)

**Comment by derek-adair** [comment]
thanks for filing that other bug for me :)

Shouldn't `vagrant destroy -f` be a nuclear option to just... remove everything regardless of errors?

**Comment by sethvargo** [comment]
Vagrant is going to call the appropriate middleware for "destroy" on itself and all the plugins. It is  up to the specific plugin to implement what "destroy" means to it. For example, the AWS plugin could determine that "destroy" actually means "stop", not "terminate" (it doesn't, just giving you an example). I would file a bug against vagrant-aws, since it seems like the issue lies there.

**Comment by derek-adair** [comment]
ok, thanks, that makes a lot of sense.
