### ISSUE TITLE
Vagrant converts "/" to "_" when creating guest path in synced folder in VirtualBox

### ISSUE THREAD

**Issue by zeeforgellc** [mitchellh/vagrant#5467]
Vagrantfile entry:

```ruby
config.vm.synced_folder "C:\\shared\\bar.zee", "/media/bar.zee", owner: "vagrant", group: "vagrant"
```

Resulting VirtualBox shared folder settings (Settings->SharedFolders->Machine Folders):

```text
media_bar.zee => C:/shared/bar.zee
```

I expected, and want, the shared folder settings to be:

```text
media/bar.zee => C:/shared/bar.zee
```

Note that the path separator ("/") has been replaced with an underscore ("_").

This name munging works when the VM is spun up from Vagrant (using "vagrant up"), presumably because of magic in vagrant on the host machine. However, it means that the shared folders do not work when the VM is started from VirtualBox, bypassing vagrant.

This strikes me as gratuitously intrusive. I do not want consumers of the VMs I build with vagrant to require vagrant in order to use them.

Is there some easy work-around or, even better, some undocumented command-line switch or directive?

**Comment by mitchellh** [comment]
Vagrant changes the ID of the synced folder. Not sure why this makes it so it doesn't work in the VirtualBox GUI. Mine actually works, even with the slash, though the mount command has to be modified a bit (to specify the correct ID). Maybe VirtualBox instead is doing something magical and trying to mount the guest path? 

I'm not sure, but it certainly isn't the intention of Vagrant to make your VM reliant on it.

We need to replace slashes since VirtualBox on different platforms actually doesn't accept slashes in the name, and instead of special casing that platform, we do the transformation on all of them.

Please let me know if you can find out more, but at this point I don't think there is anything we can do here.

**Comment by sw-carlin** [comment]
If the VM is started outside of Vagrant, the slashes are underscores. If the VM is started with Vagrant, they are slashes as specified. How is this not an issue caused by Vagrant? Vagrant shouldn't be storing the slashes as underscores in the Virtualbox configuration. If it needs to do that for being guest agnostic, that should only occur as part of the Vagrant configuration. The Virtualbox configuration is already tightly coupled with the guest OS, is it not?

**Comment by NelsonFrancisco** [comment]
Anyone got a solution on this?

It still happens in 2021! At least to me: `config.vm.synced_folder ".", "/opt/stuff"`

it replaces `/` with `_` with command `vagrant up`
