### ISSUE TITLE
SSH Connection Error Messages (or non-messages) insufficient.

### ISSUE THREAD

**Issue by DealerUplift-DavidJohnston** [mitchellh/vagrant#5473]
Stumbling upon, and mis-posted to, #3329.

Recent VirtualBox security enhancements in 4.3.x seem to increase the probability of encountering an error during `vagrant ssh`.  While the issue is with VirtualBox vagrant ideally could be a little more thorough in detecting the problem and reporting useful (or any) error messages.  In particular issuing a `vagrant ssh` while experiencing this issue simply consumed maybe 5 seconds of my life before giving me back a command line (Windows 7, GitHub for Windows Bash Shell).

There also seems to be a timing variance between the connection refusal if the VM is still booting versus one where there is never any hope that SSH is going to connect.

In this particular case a single "Error: SSH not possible; host not listening (or accepting connections) on port 2222" would be better than repeated warnings.  I say this not knowing exactly where the cause is or whether it is even possible to reasonably diagnose in software.  I'm ranting and rambling but maybe it will help someone.

Key warning/error messages for search:

`Warning: Connection refused. Retrying`
`[...] port 2222: Bad file number`

**Comment by sethvargo** [comment]
Hi there,

Thank you for opening an issue. I've tried to reproduce this a number of times, but I have been unsuccessful. Additionally, Vagrant is a fairly large project and I would have expected a ton of +1 and "me too" if this was a wide-spread issue. It's possible this has been fixed in upstream virtualbox or it's a local environment issue.

If this is still happening, could you please open a new issue and follow the provided issue template to include all the debug output and reproduction steps? Thank you and sorry! 😦
