### ISSUE TITLE
windows encoding problem

### ISSUE THREAD

**Issue by Tanyusha** [mitchellh/vagrant#5475]
C:\q>vagrant init hashicorp/precise32
	C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:224:in `join': incompatible character encodings: UTF
	-8 and Windows-1251 (Encoding::CompatibilityError)
			from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:224:in `setup_environment'
			from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:15:in `setup'
			from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler.rb:129:in `setup'
			from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.2/bin/vagrant:71:in `<main>'

**Comment by sethvargo** [comment]
Hi @Tanyusha 

Sorry you are having problems. Is there any more information in the stacktrace? That error looks to be coming from Bundler.

**Comment by Tanyusha** [comment]
The reason of my problem is the availability Cyrillic symbols in filepath. To solve this problem I moved the project to other folder so that the Cyrillic characters didn't meet in the file path.

But may be the reason of this error is vagrant.

**Comment by mitchellh** [comment]
Compiling all these into #5896

**Comment by samphippen** [comment]
@Tanyusha Hi, I'm looking into encoding issues related to Vagrant. If you've still got the setup, would you mind running the following script with the Ruby interpreter provided in `C:/HashiCorp/Vagrant/`

```
ruby -e "p ENV['PATH'].bytes; p '--------'; p ENV['PATH'].encoding"
```

This will help us debug the issue. Although it's actually caused by [this line of code](https://github.com/bundler/bundler/blob/v1.7.11/lib/bundler/runtime.rb#L224). I should be able to fix it without your path information, but it'd be useful for you to provide a repro case if you can.

Thanks :)

**Comment by samphippen** [comment]
On windows systems with windows-1251 encodings these [lines of code](https://github.com/bundler/bundler/blob/v1.7.11/lib/bundler/runtime.rb#L222-L224) cause the bug.

In Ruby, strings have utf-8 as their default encoding. Coming off the shell, the string will have a windows-1251 encoding. Consider the following array literal:

```
["💕", [209].pack("C*").force_encoding("windows-1251")]
```

This is something akin (encoding wise) to what bundler will produce, as PATH has the windows encoding, and the bundler path is unshifted to it.

Attempting to call `.join` with `File::PATH_SEPARATOR` will raise because join does not attempt to coerce strings into compatible encodings. The solution here is to map utf-8 encoding first over the array.

@mitchellh I'm going to go ahead and submit a patch to bundler to get this sorted.

**Comment by samphippen** [comment]
@mitchellh a PR for this now exists in bundler (See above), but we'll have to see if bundler will merge it. Do we need to do anything on this PR for now?

**Comment by xx1196** [comment]
???
