### ISSUE TITLE
Docker NFS freeze

### ISSUE THREAD

**Issue by pikeas** [mitchellh/vagrant#5479]
I'm experiencing a problem with NFS, which I began describing at https://github.com/docker/docker/issues/10589 and then https://github.com/docker/docker/issues/4213. I'm not sure whether this is a Docker problem, or a Vagrant problem.

In brief, I have an OS X machine, running a Vagrant CoreOS VM for docker, with my files mounted via NFS. When I `--volumes-from` mount a directory from OSX to Docker, the container is able to write to that folder for a period of time, but eventually locks up utterly. The container can't be `stop`ed, `kill`ed, or `rm -f`ed. The only solution is to `vagrant halt; vagrant up` and then `rm` it.

I don't have a one-liner for reproduction, but I can reproduce when working with moderate to large numbers of files:

    `docker run --rm -it -v `pwd`:/tmp/app my_image bash`
    # in container
    cp -R /tmp/app/* /app    # read succeeds
    cd /app
    # installs a bunch of packages from package.json in cwd
    npm install
    cp -R /app/node_modules /tmp/app
    # locks up partway through write

I'm running fully updated versions of OS X, Vagrant, CoreOS (alpha channel), and docker itself.

**Comment by pikeas** [comment]
Okay, the fix seems to be using the `tcp` mount option for NFS rather than `udp`.

I burned quite a lot of time (days) before figuring out this simple fix. The problem is that the vast majority of documentation online regarding Vagrant NFS mount options suggest using `udp`. Even Vagrant's own `nfs_udp` option (which is equivalent) defaults to true, rather than false. The docs at http://docs.vagrantup.com/v2/synced-folders/nfs.html say:

    UDP is faster but has some limitations (see the NFS documentation for more details).

Based on my research, `tcp` would be a much better default than `udp`. At the very least, the docs should be updated with an explicit description of the tradeoffs/differences between them.

**Comment by tyronep** [comment]
Thank you @pikeas for the work in tracking this down, and for sharing your solution. Like you, I was also encountering lockup when running `npm install` inside of Docker, in a CoreOS guest.

After 8 hours or so I ran across this thread, which linked to yours: https://github.com/docker/docker/issues/4213. Agreed on your assessments of tradeoffs and how nuanced the issue is, and a shame that Vagrant's maturity probably means that a change in defaults is unlikely.

**Comment by phpguru** [comment]
I've got dduportal/boot2docker-vagrant-box working with NFS on Yosemite, Macbook Pro mid 2014 and it's awesome. My friend/colleague has a slightly older Macbook pro with all of the exact same versions of everything installed as far as we can tell and it simply refuses to mount NFS shares from the host. The error `vagrant up` spits out is `bad file descriptor` and after 8 hours of troubleshooting, we're not able to figure out why it works on mine and not his.

**Comment by clody69** [comment]
Had the same problem. Vagrant machine with CoreOS on MacOS. Synched a local folder via vagrant and mounted using a docker data container. When executing npm install, it was freezing while downloading one pacakge. I could ssh from another console but I couldn't kill the docker container. So, I had to stop the machine and restart it. 
Using TCP instead of UDP on mounting the folder it works. This is my configuration
```config.vm.synced_folder "../.", "/home/core/share", id: "core", :nfs => true, :mount_options => ['nolock,vers=3,tcp,noatime,actimeo=1']```

I also added some additional settings (noatime and actimeo) to have fast NFS refresh when using grunt watch for development

**Comment by ohjames** [comment]
I'm seeing the same issue with a `vboxsf` mount although I don't get to write any files, my first write seems to cause an indefinite hang.

**Comment by sethvargo** [comment]
Hi all,

I looked at the associated Docker issues, and this appears to be an upsteam issue. If you think there is something we could do in Vagrant to make this experience better, we would gladly review a PR or proposal for that specific change 😄. It looks like Docker is investing a lot of work in this area though, so I'm going to defer to upstream. Thanks! 😄
