### ISSUE TITLE
Why does the homebrew formula write to /usr/bin instead of /usr/local/bin?

### ISSUE THREAD

**Issue by bucaran** [mitchellh/vagrant#5483]
Kindly point me to the right channel if this is not the best place for this issue.

What the title says. Basically, I had to enter my password to install vagrant via brew. 

I specifically went to great lenghts to customize my environment so that I never have to run into this.

Anyway, what is the rationale? Why `/usr/bin`?

**Comment by sethvargo** [comment]
Hi @bucaran,

Thank you for opening an issue. Unfortunately the Vagrant maintainers do not manage the homebrew packages and we recommend using the official installers from http://www.vagrantup.com/downloads.html. Perhaps @phinze knows?

**Comment by bucaran** [comment]
@sethvargo Mmm OK, I think I figured it out. Basically, homebrew (cask) downloads the official installer to my cask directory and runs it, which is when `sudo` gets in the picture and vagrant gets installed to `/opt/vagrant` and symlinked to `/usr/bin`.

So, I guess my question is just why `usr/bin` and not `usr/local/bin` or perhaps another location and why does it install to `/opt`? If this is possible, I would like to uninstall vagrant and install again using another location.

**Comment by phinze** [comment]
Hi @bucaran - you correctly identified the fact that the Cask for Vagrant simply executes the official installer, which is a `pkg` that extracts to `/opt/vagrant` and links to `/usr/bin`.

Because we want Vagrant to work reliably on a large set of host operating systems, the Vagrant installation process does a lot of work to isolate a safe execution environment for Vagrant. In that directory you'll see we have an embedded, fully isolated ruby interpreter. We've found that this gives us a lot more consistency and reliability across the wide variety of machines that Vagrant deploys to.

But there's always a tradeoff, :grinning: and here, the the tradeoff is limited installation location customization. While you are welcome to try to figure out a workaround, we don't officially support installing Vagrant to other locations.

I hope this explains the situation sufficiently for you - I'm happy to continue the conversation if there's anything else I can describe in more detail. Going to close this for now, though, since we're pretty much stuck with `/usr/bin` and `/opt` :ok_hand:

**Comment by bucaran** [comment]
Gotcha.

More details about why `/usr/bin` is more reliably or provides a more isolated / safer environment as opposed to `/usr/local/bin` would be appreciated.

**Comment by phinze** [comment]
> More details about why `/usr/bin` is more reliably or provides a more isolated / safer environment as opposed to `/usr/local/bin` as well as `/opt` would be thankful in my journey :smile:

Sure!

`/opt` is [defined in FHS](http://www.pathname.com/fhs/pub/fhs-2.3.html#OPTADDONAPPLICATIONSOFTWAREPACKAGES) as a good place to live for software packages that need to maintain their own directoriy hierarchies. Vagrant maintains a full Ruby installation rooted at `/opt/vagrant/embedded`, along with baked-in copies of several dependent tools that are difficult to consistently install across OSs and distros like `openssl`. The "bring everything with you" strategy has come to be known as an "omnibus" installation, named after the [tool that the chef team wrote for themselves](https://github.com/chef/omnibus) to distribute Chef consistently. You'll notice "omnibus" installations are most common among Ruby projects - because Ruby is just a bear to get working cross platform. :bear: 

A key benefit targeting of `/opt/<packagename>` is the ability to have a consistent prefix path (`/opt/vagrant/embedded` in our case), which is something that Unix tools know how to deal with well. This allows us to set a couple of key environment variables and give Vagrant its own little world to work out of.

As for `/usr/bin` vs `/usr/local/bin`, that's not strictly FHS compliant, but it's more of a compatibility decision. We make many decisions in Vagrant to try and minimize the potential support issues - and by dropping links into `/usr/bin` - a directory that is _always_ in `$PATH`, we can help prevent a percentage of our users having first-run sadness because they need to figure out their `$PATH`.

(An OS X specific side note here: `brew doctor` gets very angry if it finds symlinks in `/usr/local/bin` that it does not manage via a `Formula`).

Does that help explain a bit better? Let me know! :dancer:

**Comment by bucaran** [comment]
Thanks for taking the time. It definitely does. :+1:
