### ISSUE TITLE
Vagrant / Docker provider on Windows - Sporadic hangings when "waiting for machine to boot"

### ISSUE THREAD

**Issue by svogt** [mitchellh/vagrant#5522]
Sporadically our Docker containers are hanging in "waiting for machine to boot" on Windows (custom Docker host with Ubuntu + Docker provisioner) and Docker containers which have "has_ssh=true" set. 

After some investigation I found the following:
- In https://github.com/mitchellh/vagrant/issues/3951 jbarbuto commented on 27 Jul 2014 that commenting out
  https://github.com/mitchellh/vagrant/blob/v1.6.3/plugins/communicators/ssh/communicator.rb#L261-L280
  helped him fix the issue.

Looking at our logs we had the same symptoms he mentions in that issue (which are a bit different from the rest of the issue). Commenting out the connection reuse fixed that problem for us as well. We have in total at least bootet 100 times since then and no locked up start (which previously would fail at least 30% of the time).

So from my POV it looks like that on Windows the following can happen:
- Connection is open
- connection.exec("") doesn't raise an exception
- Docker provider does an SSH test (see
  https://github.com/mitchellh/vagrant/blob/v1.7.2/plugins/providers/docker/communicator.rb#L23-L31)
  which fails because the connection isn't fully open

-> Endless loop. Connection is never "discarded" but in a state where
SSH isn't working properly

**Comment by oxygen0211** [comment]
We deployed the workaround @svogt described on 6 installations which all had the issue before (I am working on the same project as @svogt) and it didn't occur once since then. I think this is a strong hint that something is funky with the retry mechanism in combination with Windows, VirtaulBox and the Docker provider.

In this time we even introduced more containers to the environment which, in my experience before deploying the workaround, raised the possibility for one of the containers hanging in "waiting for machine to boot" extremely, but disabling connection reuse seems to completely prevent these states.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
