### ISSUE TITLE
Documentation : Default route/gateway thru public network

### ISSUE THREAD

**Issue by aglossa** [mitchellh/vagrant#5524]
The issue has already brought up but closed inappropriately with a lot a acrimony.
https://github.com/mitchellh/vagrant/issues/2389

The use case : a VM connected to a LAN with DHCP that distributes IP.

The Vagrantfile directive

```ruby
         config.vm.network "public_network", type: "dhcp", bridge: "en0: Ethernet"
```

generates the adequate VirtualBox conf but it also inserts 

```text
#VAGRANT-BEGIN
#The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet dhcp
    post-up route del default dev $IFACE || true
#VAGRANT-END
```

in /etc/network/interfaces although the default / expected behaviour is killing the default route thru the host (nat).

After finding with Google this proposed patched https://github.com/nickrw/vagrant/commit/a0b684a4ab4a447d408b083c7d62d5f6b5e7d817

I discovered in the code https://github.com/mitchellh/vagrant/blob/master/plugins/providers/virtualbox/action/network.rb
a new config variable to handle this: use_dhcp_assigned_default_route.

I suppose that's what many people are looking for / expecting. So the Documentation should probably put this into the front light
https://docs.vagrantup.com/v2/networking/public_network.html

**Comment by aglossa** [comment]
Should also be the (commented) default in the example Vagrantfile generated with vagrant init

**Comment by sethvargo** [comment]
Related, https://github.com/mitchellh/vagrant/pull/5721.

**Comment by mitchellh** [comment]
We actually prefer people use `auto_config: false`. The other option is there for legacy reasons. We document the auto config option.

**Comment by aglossa** [comment]
Tried the auto_config: false option, always in a 'public' network env with dhcp.

Result : the ip is correctly assigned with dhcp, no unwanted route is added... but dns resolver is not (/etc/resolv.conf point to the Virtualbox host, not the one provided by dhcp).

So I stay with the legacy option (and please keep it).

**Comment by CVTJNII** [comment]
+1 for leaving :use_dhcp_assigned_default_route.  I have been having network stability issues caused by the default NAT settings and a local caching proxy.  I was able to resolved it by not natting my VMs by setting up a second, bridged interface and setting it as the default route via the use_dhcp_assigned_default_route option.  The :use_dhcp_assigned_default_route option is a much cleaner solution than auto_config: false and embedding manual network config in my configs.

For my set up the proxy is very important as I'm repeatedly running Test Kitchen tests which destroy and create VMs in quick succession resulting in the files needed for the Chef run to be downloaded frequently.  Having a caching proxy makes a noticeable difference and, as I mentioned above, I used the :use_dhcp_assigned_default_route to stabilize the config.  Please retain it.

**Comment by john-shine** [comment]
+1, is this solved by official ?
