### ISSUE TITLE
Invalid state problem

### ISSUE THREAD

**Issue by alexkleinubing** [mitchellh/vagrant#5526]
Hello, im using latest versions of Vagrant (1.7.1) and VirtualBox (4.3.26, tested 4.3.8 too) on a Windows 7, to up a ubuntu/trustly64. VT-x enabled.

I got the following error to state machine:

*ERROR vagrant: #<Vagrant::Errors::VMBootBadState: The guest machine entered an i
nvalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'poweroff' state. Please verify everything is configured
properly and try again.*

But, if i open the VirtualBox to see a GUI, the VM is up normally. But i dont want to open it every time.

**Comment by manoyes** [comment]
I think having the same issue, but it might be unrelated. I'm using Vagrant (1.7.2), Virtualbox (4.3.26) on a Ubuntu 14.04 release. If I try to do a `vagrant up` with `v.gui = false` or with the Virtualbox window closed, I get an invalid state error. This problem seems to occur more if I try to execute the command through ssh (for example, `ssh machine.com 'vagrant up'` as one command). But, setting `v.gui = true` or just having the virtualbox window open (tunneled with `ssh -X`) fixes the invalid state issue.

My use-case for this is a Jenkins continuous integration Master server connects to a build slave via ssh and needs to start a vagrant machine for running tests.

**Comment by danielvdende** [comment]
I'm having a similar problem. I had a number of boxes in operation, opened my Vagrantfile to add a new config. Then when I ran `vagrant up`, I was told that it could not boot and was subsequently placed in `poweroff` state. Now ALL my boxes are in `poweroff` state when I check `vagrant status`. The apps running on these boxes are still running though, but I can't ssh into them. I also cannot run `vagrant halt`, nothing seems to happen. When I run `vagrant up` port collisions occur

**Comment by manoyes** [comment]
If it helps my issue was the Virtualbox accelerate3D option being on when running on a server platform on a Xeon CPU that didn't have graphical acceleration available. I was only able to determine this by reading the Virtualbox log file, not by turning on the GUI option and watching the Virtualbox window.

**Comment by danielvdende** [comment]
My issue was caused by a VirtualBox update + kernel upgrade executed by server admins without my knowledge. Reboot solved the issue.

**Comment by mitchellh** [comment]
Fixed, error message
