### ISSUE TITLE
vagrant(1) is slow

### ISSUE THREAD

**Issue by benesch** [mitchellh/vagrant#5528]
Apologies in advance if this issue seems glib. I love Vagrant to pieces; it's saved me hours on hours debugging development environments.

But this drives me insane:

```
$ time vagrant
Usage: vagrant [options] <command> [<args>]
-snip-
real	0m1.416s
user	0m1.295s
sys	0m0.111s
```

vagrant(1) is just slow to execute! #5224 seems related, but the reporter was seeing ~4s execution times. In my experience, ~1s execution time, minimum, is standard for all `vagrant` invocations on recent machines.

This is most annoying when trying to run a command via SSH on the guest:

```
$ time vagrant ssh -c 'true'
Connection to 127.0.0.1 closed.

real	0m2.376s
user	0m1.494s
sys	0m0.336s
```

```
$ vagrant ssh-config > ssh_config
$ time ssh -F ssh_config default true

real	0m0.325s
user	0m0.011s
sys	0m0.005s
```

Caching the output of `vagrant ssh-config` shaves a full *two* seconds off command execution. I end up implementing some sort of Vagrant wrapper for every project I work on to realize this speedup, but I wish I didn't have to. Is there any low-hanging fruit performance-wise? I'm happy to do some digging if a) this isn't just me, and b) this is something you think is important.

I did my best to search for similar issues, but "Vagrant is slow" almost always means "VirtualBox is slow" and so it's hard to separate the noise.

**Comment by mitchellh** [comment]
We've tried to make this faster and continue to shave time off as we go, but the real issue is Ruby here. We've been cheating more and more by turning `vagrant` into a Go executable that hides Ruby for as long as it can, but there is only so much. I'm not sure how much more we can squeeze out without a significant rearchitecture. For now we're going to close but this is always on our mind. Sorry!
