### ISSUE TITLE
Bundle rsync client for Windows installation

### ISSUE THREAD

**Issue by raphinesse** [mitchellh/vagrant#5534]
Bundling rsync and SSH (#4884) would really help to simplify setup on Windows. There are a lot vagrant issues about rsync on windows and reducing the variable parts would probably simplify finding a robust solution for these, too.

As an example it took me two attempts of a few hours each to get rsync running with vagrant. And now it only works with a hack¹ in my Vagrantfile and cwRsync which bundles an ssh version that sucks hard at utf-8. Not exactly a good starting point for convincing co-workers to pick up vagrant.

¹ `ENV["VAGRANT_DETECTED_OS"] = ENV["VAGRANT_DETECTED_OS"].to_s + " cygwin"`

**Comment by thiagotalma** [comment]
+1

Vagrant will not be a complete solution while relying on "hacks" with third-party applications.

Rsync is the source MANY problems that end up scaring new users of Vagrant.

**Comment by jonathanan** [comment]
+1

(new user to vagrant) Trying to get a linux host to sync folders with windows guest powered by virtualbox.

**Comment by Perni1984** [comment]
What exactly are you trying to achieve with rsync? If it's about synced folders, I would advise you going for, type: "smb" on a Windows host an either enforcing smb v3 (Windows 10, Windows 8) or smb v2 (Windows 7).

**Comment by raphinesse** [comment]
@Perni1984 I was using rsync for one way host to guest synchronization to circumvent problems that come with synced folders in certain scenarios (symlinks, poor performance with huge amounts of files).

**Comment by Perni1984** [comment]
@raphinesse: Not sure if it solves your problem, but I had a hard time figureing out how to best develop with Symony2 on my Windows 10 host - because of the poor performance with huge amounts of files of standard vboxfs. 17.000 ms per page load or more were standard for dev environment, because it stats a lot of files during a page load.

I now run my pages with about ~500 ms(!) with a simple trick. Mounting the shared folder with smb3 and mfsymlinks (attention: guest OS with linux kernel > 3.18 needed)

`config.vm.synced_folder "/projectfolder/www", "/var/www", type: "smb", mount_options: ["vers=3.02","mfsymlinks"]`

did the trick for me. Moreover I move out all files I don't necessarily need in my shared folder (e.g. /vendor, /logs, /node_modules /cache) to a location inside the native file system of the guest OS and put a symlink there. With this "trick" only the native guest OS filesystem is used and I am able to circumvent e.g. bad performance on shared folders and all node.js windows path related problems. I have a shell provisioner running that does all this automatically.

**Comment by ukoloff** [comment]
I believe, rsync should be added to Vagrant on Windows. New user shouldn't fiddle with config files, just install and run.

I downloaded some packages from `mingw` and unpacked them into `C:\HashiCorp\Vagrant\embedded\bin`. After that rsync works likes a charm!

The downloaded packages are:
- libiconv-1.14-1-msys-1.0.17-dll-2.tar.lzma
- libintl-0.18.1.1-1-msys-1.0.17-dll-8.tar.lzma
- libminires-1.02_1-2-msys-1.0.13-dll.tar.lzma
- libopenssl-1.0.0-1-msys-1.0.13-dll-100.tar.lzma
- libpopt-1.15-2-msys-1.0.13-dll-0.tar.lzma
- openssh-5.4p1-1-msys-1.0.13-bin.tar.lzma
- rsync-3.0.8-1-msys-1.0.17-bin.tar.lzma

Needed files are:
- msys-crypto-1.0.0.dll
- msys-iconv-2.dll
- msys-intl-8.dll
- msys-minires.dll
- msys-popt-0.dll
- msys-ssl-1.0.0.dll
- rsync.exe
- ssh.exe

I packed all the files in attached zip.
[rsync.zip](https://github.com/mitchellh/vagrant/files/659008/rsync.zip)

Please, add these files to Vagrant on Windows installation package.

**Comment by chrisroberts** [comment]
Fixed via mitchellh/vagrant-installers#107
