### ISSUE TITLE
Issue with ansible running in vagrant ruby+gems context

### ISSUE THREAD

**Issue by Zeelot** [mitchellh/vagrant#5548]
I have an ansible plugin that is written in ruby. The plugin gets executed on the host machine and when running ansible on my own, uses the rvm+ruby+gems I have set up in my personal Gemfile. However, when I try to provision a VM with vagrant for local development, the ansible plugin that gets executed cannot find the needed gems: `require': cannot load such file -- hiera (LoadError)`

If I install the needed gems using `vagrant plugin install hiera`, things work. However, I would rather not have to install my gems as vagrant plugins as they aren't actually dealing with vagrant at all (it's specifically for Ansible to run).

I'm not a ruby developer so I may be way off but if there any way for the vagrant call to run ansible to be done with a fresh set of environment variables? Something in this file: https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/util/subprocess.rb

Any suggestions? Are there any configuration options I might have missed that would allow this to work?

**Comment by sethvargo** [comment]
Hi @Zeelot,

Thank you for opening an issue. Unfortunately you have identified one of the biggest pain points of working with embedded Ruby environments. Depending on your local Ruby setup, the shellout (subprocess) execution can behave quite crazily. 

I realize this is a crappy answer, but it is something we routinely struggle with in Ruby (see https://github.com/mitchellh/vagrant/issues/5154 for an example of the same thing with Chef). We are exploring some different solutions, but unfortunately it's a very difficult problem to solve. Since 5145 is tracking the same root cause, let's keep conversation over there :smile:
