### ISSUE TITLE
doing an upgrade using cloud-init directives can cause chef provisioner installation to fail

### ISSUE THREAD

**Issue by olbrich** [mitchellh/vagrant#5571]
If I place a user script in a vagrant file like
    
    aws.user_data = "#cloud-config\napt_upgrade: true"

The vm will attempt to upgrade on first boot.  If there are actual changes to install, apt may take some time to complete.  Vagrant does not have visibility into when this script completes and attempts to install the chef packages when using the 'chef_zero' provisioner.  Since apt is already occupied when this kicks off, an error occurs which terminates the process.   

    E: Could not get lock /var/lib/dpkg/lock - open (11: Resource temporarily unavailable)
    E: Unable to lock the administration directory (/var/lib/dpkg/), is another process using it?

Perhaps the provisioner should capture this error and retry a few times before bailing.  Is there some other workaround for this?

**Comment by mitchellh** [comment]
I think this is outside the responsibilities of Vagrant. If you're knowingly adding user data that takes time, it makes more sense to add your own provisioner to wait for it to complete. While a retry would help, there are a lot of other cases where it can still fail and I don't think it is generally Vagrant's job to be 100% on this.

**Comment by BogdanSorlea** [comment]
@mitchellh say I'm wrong (which you will), but this means Vagrant is not a good tool: it is not uncommon for bootstrapping/provisioning to involve `apt-get upgrade` (and in most cases a reboot after that), resulting in the behaviour above (even when using cloudinit + puppet) and sometimes in vagrant complaining about ssh timeout due to the instance rebooting

The latter problem is hard to overcome in vagrant "v2", as the `config.ssh.timeout` and `config.ssh.max_tries` config properties have been removed (they exist in `v1.0`, but not in `v1.1+`). Even that does not constitute a good solution, but it is better than nothing

So, are there any plans around functionality that will enable Vagrant to wait for cloudinit to finish properly before continuing to run the Vagrant provisioner (`config.vm.provision :shell, inline: puppet_run_stuff_here`) and for Vagrant to not crap out if the instance reboots as part of a potential upgrade?

Maybe I am missing some techniques on doing this kind of stuff, in which case any tips and tricks are welcomed.

**Comment by mitchellh** [comment]
I think it does make sense for Vagrant to retry things, but it is very difficult to make it 100% robust. We've been fighting that battle for years, and we slowly make progress and lose progress. With the experience we've gained since from making Packer, Terraform, and more, we've learned that simply making it much more explicit what your machines are doing makes things MUCH more stable. For example, only you know that the boot process means that the machine isn't ready for X seconds after boot. 

Cloud-init is a common enough thing we could probably look for it. If there were a PR, I'd be happy to take a look at that. For most other things, I think doing the logic on your own makes for a much better tool: it works more often because it isn't using heuristics to get your environment right, it is more explicit to people reading your config file, etc. 

In your case, a solution:

`config.vm.provision "shell", inline: "sleep 60"`
