### ISSUE TITLE
Setting guest_ip does not allow using the same port for another guest_ip

### ISSUE THREAD

**Issue by thebillkidy** [mitchellh/vagrant#5587]
When creating a machine with:

    config.vm.network :forwarded_port, :host => 8080, :guest => 8080, :host_ip => '192.168.1.10'

I can't create yet another machine with this configuration:

    config.vm.network :forwarded_port, :host => 8080, :guest => 8080, :host_ip => '192.168.1.11'

When doing this I get:

    Vagrant cannot forward the specified ports on this VM, since they
    would collide with some other application that is already listening
    on these ports. The forwarded port to 8080 is already in use
    on the host machine.

    To fix this, modify your current projects Vagrantfile to use another
    port. Example, where '1234' would be replaced by a unique host port:

      config.vm.network :forwarded_port, guest: 8080, host: 1234

    Sometimes, Vagrant will attempt to auto-correct this for you. In this
    case, Vagrant was unable to. This is usually because the guest machine
    is in a state which doesn't allow modifying port forwarding.

Which does not make sense because I am binding it on different ip's

P.S. I tried using guest_ip too but that didn't work

**Comment by dragon788** [comment]
@thebillkidy This is because you MUST use different ports on the host when using forwarding. If you were using bridged or private mode, each guest could use that port because they would have their own IPs. Where did you find the syntax of host_ip? In the documentation I see just ip, and it is referencing public or private networks, not forwarded ports? See this open issue, https://github.com/mitchellh/vagrant/issues/4608

**Comment by thebillkidy** [comment]
If you go here: http://docs.vagrantup.com/v2/networking/forwarded_ports.html and scroll down a bit you will see: guest_ip and host_ip. The thing is that when binding ports they can be bound on interfaces. Normally if we have let's say 2 different virtual machines running then we have 2 different interfaces. Which allows us to have the same port on both of these interfaces.

My example: I have 2 nginx instances running in 2 different virtual machines. These therefor have 2 bound ip's to them that are different from each other. If I now forward port 80 from both these machines so that I can access them on the interface it's ip. Then this should be possible right?

You can correct me if I am wrong, but as I see it on this moment it should be possible to do this right?

**Comment by dragon788** [comment]
Ooooh, I hadn't noticed that portion before, since they didn't give any examples. It does seem like if you have two separate host interfaces and each VM listens on a different host interface you should be able to map the same port in two places.

So you tried doing a 
    config.vm.network :forwarded_port, :host => 8080, :guest => 8080, :guest_ip => '10.0.1.10, :host_ip => '192.168.1.10'
And
    config.vm.network :forwarded_port, :host => 8080, :guest => 8080, :guest_ip => '10.0.1.11, :host_ip => '192.168.1.11'

Using whatever your guest IPs are in each separate Vagrantfile?

I actually filed a bug today where I did NOT have conflicting port mappings, but when the second machine came up it clobbered the config of the first one so only the ports mapped to the second one showed up.

**Comment by thebillkidy** [comment]
I have not tried using both host_ip and guest_ip, this because I want to bind to a different ip on the host computer (I guess host is my computer) and the guest computer (the virtual machine) should bind on *:<port>.

**Comment by thebillkidy** [comment]
I'm going to close this though, since it seems to be a duplicated issue too the one you linked (#4616).

**Comment by pravinchandar** [comment]
Fixed in #7035
