### ISSUE TITLE
Vagrant + Homestead: UTF-16LE Encoding InvalidByteSequenceError on Windows 8

### ISSUE THREAD

**Issue by Hamsterkacke** [mitchellh/vagrant#5595]
I'm trying to run Vagrant with Homestead for Laravel.
I'm using git bash on Windows 8 and have everything installed and setup as described.
But wenn i run homestead up, i get the error from the title:

http://screencloud.net/v/yOeD

I already tried to find a solution on Google, but had no luck.

**Comment by sethvargo** [comment]
Hi @Hamsterkacke 

Thank you for opening an issue and I am sorry Vagrant is not working as you expect. Do you have any special characters (including spaces, quotes, parenthesis, etc) in your $PATH? Can you please share the complete `Vagrantfile` as well as the output of the command in [debug mode](http://docs.vagrantup.com/v2/other/debugging.html)? Thanks!

**Comment by mitchellh** [comment]
See #5896 where we'll be tracking all these

**Comment by samphippen** [comment]
@Hamsterkacke Hi! I'm going to take a look at the various encoding issues affecting vagrant. By any chance, can you still reproduce the issue?

If so, could you do so again and paste the full Stacktrace.

Either way, on the same machine could you possibly run:

```
ruby -e "p ENV['PATH'].bytes; p '--------'; p ENV['PATH'].encoding"
```

There should be a ruby interpreter provided somewhere in `C:\HashiCorp\Vagrant` and it's preferable for you to use that one, instead of the one installed on the system.

That'll really help us debug this issue.

Thanks :+1:

**Comment by samphippen** [comment]
I think there's not enough info to reproduce this one for now.
