### ISSUE TITLE
Password input not hidden in Cygwin terminal

### ISSUE THREAD

**Issue by denisw** [mitchellh/vagrant#5624]
When I run `vagrant up` in a Cygwin terminal (MinTTY), I get a warning like the following if I need to type in a password (e.g. for SMB synced folders):

    Error! Your console doesn't support hiding input. We'll ask for
    input again below, but we WILL NOT be able to hide input. If this
    is a problem for you, ctrl-C to exit and fix your stdin.

And indeed, the typed-in password is not hidden. However, MinTTY is more than capable of hiding password input - it does so without hiccups in SSH password prompts, for instance. Tried with Vagrant 1.7.2 on Windows 8.1.

**Comment by rcuddy** [comment]
Confirming this occurs in Babun configured cygwin/mintty as well

**Comment by mitchellh** [comment]
This error is coming from Ruby itself when we request a `noecho` prompt. I'm not sure what a workaround might be for Windows, but we're just calling a Ruby standard library function `noecho` to do this, and it is raising an exception (that we catch and show as this error). 

Can't fix without a clear workaround.

**Comment by kuya1284** [comment]
I've been experiencing this same issue for a while.  I'm using MobaXterm, which is also based on cygwin.

Mitchell, do you know if any of these links will help with coming up with a solution?

* https://github.com/composer/composer/issues/2831
* http://stackoverflow.com/questions/5239465/hiding-user-input

I just tried testing something in my terminal.  When I run 

`stty -echo`

or

`bash -c 'stty -echo'`

Anything I type after doesn't get echoed to the screen.  Then when I type the following (even though nothing is getting echoed back), anything I type after starts getting echoed.

`stty echo`

or

`bash -c 'stty echo'`

Also, if I decided to hit CTRL+C to exit instead of entering my password, my terminal locks up and the only thing I can do at the point is to kill the process.  I'm assuming this is because of the exception that gets raised and Vagrant doesn't terminate gracefully.

Is this something you could look into further please?  Would it be alright to reopen this ticket?

Thanks.

**Comment by russellvt** [comment]
I've also been seeing similar issues under Cygwin command prompts for mercurial. Generally, I find that if I don't react *quickly* to the password prompt and, instead, let it visibly sit for a couple of seconds... it works. However, if I start typing the second that prompt appears, at least a portion of my password is echo'd to the tty (ie. via mintty).

**Comment by gawbul** [comment]
Any news on a fix for this?

**Comment by gawbul** [comment]
I've used control sequences (specifically `\e[8m` and `\e[0m`) to work around this. I've added this to the top of my Vagrantfile:

```
# capture username and password for smb synced folders
if RbConfig::CONFIG['host_os'] =~ /cygwin|mswin|mingw32/
  puts "Due to MinTTY and Cygwin not supporting the no-echo TTY mode"
  puts "it is necessary to request your account username and password"
  puts "at this stage in order to correctly setup SMB shared folders."
  puts
  print "Enter username: "
  STDOUT.flush
  username = STDIN.gets.chomp
  print "Enter password: \e[0;8m"
  STDOUT.flush
  password = STDIN.gets.chomp
  puts "\e[0m"
  STDOUT.flush
```

I then add `smb_username = username` and `smb_password = password` at the relevant place in my Vagrantfile to setup the smb synced folders.

**Comment by paulbhart** [comment]
@gawbul did you test this on mobixterm?  The code seems to execute, but the escape sequence isn't causing the password to be hidden.

**Comment by gawbul** [comment]
@paulbhart no, I haven't tried in mobixterm - not sure if it deals with control codes differently?

**Comment by paulbhart** [comment]
@gawbul it does seem too, but we just decided to use cygwin for shelling on windows.  We have run into so many little roadblocks using vagrant* on windows that I converted another user to mac!  

*these were short comings in windows (i.e. lack of ssh, rsync, etc) given our users often can't install sw on their laptops

**Comment by czukowski** [comment]
For what it's worth, the password seems be properly hidden with bash shipped with Vagrant:

`%vagrant_install_dir%\embedded\usr\bin\bash.exe`
