### ISSUE TITLE
remove outdated

### ISSUE THREAD

**Issue by hryamzik** [mitchellh/vagrant#5633]
It would be nice to have a command to remove outdated boxes. Cleaning them manually is a bit frustrating.

```
ubuntu/precise64            (virtualbox, 12.04.4)
ubuntu/precise64            (virtualbox, 20150420.1.0)
ubuntu/trusty64             (virtualbox, 14.04)
ubuntu/trusty64             (virtualbox, 20150420.1.1)
```

Here I've had to run `vagrant box remove ubuntu/precise64 --box-version 12.04.4` and the same for 14.04 box...

**Comment by dragon788** [comment]
@hryamzik The tough part is these version numbers don't necessarily compare for a computer. A human might know that one is newer, but since they are both valid versions but not directly comparable  it would be hard to code that in. The other challenge is whether the box is still in use by any running VMs, in order to remove any box that's in use you would need to pass a force/override command, doing this for large numbers of boxes could be dangerous.

**Comment by sethvargo** [comment]
https://github.com/mitchellh/vagrant/pull/6863
