### ISSUE TITLE
Adjust source installation instructions in README to reflect permissions and rake default directories

### ISSUE THREAD

**Issue by krichter722** [mitchellh/vagrant#5644]
Running `rake install` as described without `sudo` causes the installation to fail because typically unprivileged users don't have permissions to write to `/var/lib/gems/2.1.0/ `. If one runs `sudo rake install` the installation fails because the prerequisites (running `sudo bundle install` aren't fulfilled `bundle install` installs to a different directory), so that the user has to make the decision whether to run both build and installation with `sudo` or not.

The error message of an explicit `gem install /path/to/vagrant/pkg/vagrant-1.7.2.gem` is

    ERROR:  While executing gem ... (Gem::FilePermissionError)
        You don't have write permissions for the /var/lib/gems/2.1.0 directory.

This is definitely a deficit of `rake` or `gem` (that don't allow separation of build and installation with different privileges), but should be reflected in `README.md`.

Maybe `bundle` or at least it feedback is buggy (discourages the usage of `sudo`, but depends on it... https://bugs.launchpad.net/ubuntu/+source/ruby-defaults/+bug/1449297).

experienced with bdb945cd1b17138133a8e3951de3886baedb75b4

**Comment by sethvargo** [comment]
Hi @krichter722 

Thank you for opening an issue. If you are developing on Vagrant, it is expected that you have a Ruby environment that the local user has read/write permissions for. Unfortunately we cannot document all the requirements for setting up an entire Ruby development environment to hack on Vagrant as it differs significantly from different operating systems and Ruby versions.

In general, you should not use the system Ruby to or a system package for developing with Ruby. Instead, you should use a tool like rvm, rbenv, chruby, ruby-install, etc (the list is endless) to install a user-Ruby and perform development and gem installation there.

I am going to close this issue since I do not think we can possibly account for all the edge cases when working with a development Ruby. If you would like to open a PR to update the language in the README, I would gladly review it, but Ruby development environments can be quite a bike shed if we aren't too careful :smile:!
