### ISSUE TITLE
Having trouble with build_images not executing for Docker provider

### ISSUE THREAD

**Issue by henrytseng** [mitchellh/vagrant#5654]
Seems like `docker build` isn't running before the `loadbalancer` is built.  

``` ruby
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Docker Configuration
  config.vm.provider "docker" do |d| 
    d.vagrant_machine = "#{DOCKER_HOST_NAME}"
    d.vagrant_vagrantfile = "#{DOCKER_HOST_VAGRANTFILE}"
  end

  config.vm.provision "docker" do |d|
    d.build_image "/vagrant/ubuntu",
      args: "-t=myteam/ubuntu"
  end

  # Nginx
  config.vm.define "loadbalancer" do |app|
    app.vm.provider "docker" do |d|
      d.name = "loadbalancer"
      d.build_dir = "nginx"
      d.build_args = ["-t=myteam/nginx"]
      d.remains_running = false
    end
  end
end
```

`loadbalancer` has the `Dockerfile`:

```
FROM myteam/ubuntu
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
