### ISSUE TITLE
Ansible provisioner shadows `ssh_args` settings defined in an ansible.cfg file

### ISSUE THREAD

**Issue by cgsmith** [mitchellh/vagrant#5663]
Feel free to ask any questions to help clarify any questions.  When running the ansible provisioner with `vagrant provision` I do not see the settings I am passing through to ansible.extra_vars in the debug information.

This is the config I am using:

```
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
    ansible.inventory_path = "provisioning/ansible_hosts"
    ansible.host_key_checking = false
    ansible.sudo = true
    ansible.limit = 'all'
    ansible.verbose = 'vvvv'
    ansible.extra_vars = {ansible_ssh_args: '-o ForwardAgent=yes'}
  end
```

It does not seem to `ansible.extra_vars` is commented out or not I still receive the following debug info:

```
<192.168.56.122> ESTABLISH CONNECTION FOR USER: vagrant
<192.168.56.122> REMOTE_MODULE setup
<192.168.56.122> EXEC ssh -C -tt -vvv -o UserKnownHostsFile=/dev/null -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/cgsmith/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o IdentityFile="/home/cgsmith/Sites/requirements/.vagrant/machines/default/virtualbox/private_key" -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=vagrant -o ConnectTimeout=10 192.168.56.122 /bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1430498290.35-217252812831737 && chmod a+rx $HOME/.ansible/tmp/ansible-tmp-1430498290.35-217252812831737 && echo $HOME/.ansible/tmp/ansible-tmp-1430498290.35-217252812831737'
```

I would *expect* to see output in the ssh call to reference `-o ForwardAgent=yes`.  The documentation is not clear/hard to find regarding this.

Ideally (before the 1.7.3 release #5017 ) I'd like to put through `-o IdentitiesOnly=yes` through the Vagrant configuration to pass to the ssh_options[]

**Comment by cgsmith** [comment]
Please note the reference to utilizing a ansible.cfg (http://docs.vagrantup.com/v2/provisioning/ansible.html) file does not produce any results with the ansible.cfg in the same directory as Vagrantfile.

My ansible.cfg is here:
```
[ssh_connection]
ssh_args = -o IdentitiesOnly=yes
```
It did not modify the SSH command to include that option.  I also know that it is pulling the configuration because when i remove the ssh_connection identifier it screams about it.

**Comment by gildegoma** [comment]
@cgsmith Sorry for the response delay (Vagrant 1.7.3 is being released today :gift_heart:)

It is correct that it is not possible to pass extra SSH arguments in the two ways that you tried (`extra_vars` option or `ssh_args` in `ansible.cfg`) because for different reasons (like the native support of agent forwarding via [`config.ssh.forward_agent` option](http://docs.vagrantup.com/v2/vagrantfile/ssh_settings.html) Vagrant Ansible provisioner has to rely on `ANSIBLE_SSH_ARGS` environment variable, which has the highest priority.

But Vagrant/Ansible users are still able to provide additional SSH arguments, thanks to [the `ansible.raw_ssh_args` provisioner option](https://docs.vagrantup.com/v2/provisioning/ansible.html). Again sorry to give you this hint quite late.

Note: I updated the issue title, as other variables are well passed with `extra_vars` option.

**Comment by gildegoma** [comment]
Closing as this is a known limitation, which is solvable via `raw_ssh_args` setting.

**Comment by cgsmith** [comment]
:+1:
