### ISSUE TITLE
vagrant 'up' may trash your VM

### ISSUE THREAD

**Issue by ruskotron** [mitchellh/vagrant#5676]
Apologies if this has been raised before.

There is an issue whereby under certain circumstances "vagrant up" may not detect the previously run VM and will reinstall it, trashing any work that has been done on that VM beforehand.
        https://github.com/mitchellh/vagrant/issues/2969

This has happened to me often enough now, that I have to ask the question: Why is it that the "vagrant up" command which I use for starting my VM, may also in certain circumstances also trash my VM?

To me it would seem logical to have a separate command for each case. Perhaps "vagrant up" to start the VM, and "vagrant provision" to trash my VM and start again. "vagrant up" could issue a little message to say "please run provision first" if this has not been done, and this would be vastly preferable to discovering that my VM has been trashed.

Perhaps I am using vagrant incorrectly and if it is so I apologise. It could be that "vagrant up" is not the correct command to use for a "daily startup".

Thanks,
Rob

**Comment by sethvargo** [comment]
Hi @ruskotron 

The proper workflow with Vagrant is as follows:

1. Run `vagrant up` to bring up the machine
2. Run the machine as necessary
3. If you want to deallocate the resources of the machine, you can run `vagrant halt` which will stop the machine (but not destroy it)
4. When you are done with the vm, run `vagrant destroy` to terminate it and remove it from disk.

If you restart your computer, the state information that Vagrant has about the machine can become out of sync with the actual state of the machine, which will cause the issue you've described. Since the machine is not running (you restarted your computer), Vagrant will attempt to re-create it. You can also use `vagrant resume` to bring back a suspended machine.

`vagrant provision` is used to apply provisioner(s) such as shell scripts or Chef recipes to the machine for configuration.

Does that answer your question?

**Comment by ruskotron** [comment]
Hi @sethvargo 

Thanks for your response. I can confirm that the way you have explained it matches my understanding.

Please accept my posting above as constructive feedback, and perhaps a suggestion for future improvement.

Kind Regards,
Robert

**Comment by mitchellh** [comment]
This is now detected by Vagrant and prevented as well.

**Comment by ruskotron** [comment]
Thanks! Does it take any steps to resolve the issue or is it still up to the user to fix the UUIDs themselves?

**Comment by ruskotron** [comment]
For the benefit of others, for whom this may still be a problem, this shell-script wrapping VirtualBox VBoxAdmin command may be helpful: https://gist.github.com/ruskotron/fbf04bac53d86d84498c
