### ISSUE TITLE
Vagrant does not remove network config

### ISSUE THREAD

**Issue by foxx** [mitchellh/vagrant#5679]
If you add a private network into Vagrantfile, and subsequently remove it, the entries are not removed from `/etc/network/interfaces` and result in `cloudinit` hanging for a long period of time whilst waiting for network devices.

I had to manually remove the following to make it work, short of doing a `destroy -f`;

```
#VAGRANT-BEGIN
# The contents below are automatically generated by Vagrant. Do not modify.
auto eth1
iface eth1 inet static
      address 169.254.20.20
      netmask 255.255.255.0
#VAGRANT-END
```

**Comment by sethvargo** [comment]
Hi @foxx 

If you change any networking, you need to run `vagrant reload` to reload and configure the network interfaces. 

Does that answer your question?

**Comment by mitchellh** [comment]
@sethvargo This is correct, but Vagrant still won't _remove_ old configured networks.

You'd need to destroy and recreate. Vagrant doesn't retain the old state of the added network config. We don't intend to do this since Vagrant is meant to make recreating your dev environment easy and adding this would add substantial complexity. We've updated the docs to help with this.
