### ISSUE TITLE
Networking does not work as expected for Red Hat 7.1

### ISSUE THREAD

**Issue by gjngeldenhuis** [mitchellh/vagrant#5712]
When building a machine using packer the interface is called ens33 but when you then import the resulting box file and try and boot it vagrant does not manage to connect to the machine. The interface is now ens32. I have installed vmwaretools:

```
./vmware-tools-distrib/vmware-install.pl -d
yum install -y open-vm-tools-deploypkg
systemctl restart vmtoolsd
```

gcc is also installed which is required for the file system drivers to work. 

Is this a vagrant bug? I would expect vagrant to take care of devices and connecting them as appropriate

**Comment by sethvargo** [comment]
Hi @gjngeldenhuis 

I am sorry you are having issues with Vagrant. There is not enough information here to adequately diagnose or reproduce the problem. Can you please provide the complete `Vagrantfile` as well as any [debug output](http://docs.vagrantup.com/v2/other/debugging.html) you may have? Thanks!

**Comment by mitchellh** [comment]
Closing due to lack of response.

My two cents: I'm not sure if this is a Vagrant bug, but Vagrant imports the VM as-is, removes all the network adapters, and recreates them. So it can very well be doing that. This is a core functionality of Vagrant where we don't support pre-existing network adapters, however, and we'd like to fix that but it isn't planned in the short term.
