### ISSUE TITLE
Vagrantbox ubuntu/vivid64 not usable

### ISSUE THREAD

**Issue by berendt** [mitchellh/vagrant#5761]
Not sure if this is a box-related or a Vagrant-related issue. At the moment it is not possible to use the box `ubuntu/vivid64` because of the following error message:

```
==> default: Setting hostname...
The following SSH command responded with a non-zero exit status.
Vagrant assumes that this means the command failed!

service hostname start

Stdout from the command:



Stderr from the command:

Failed to start hostname.service: Unit hostname.service is masked.
```

**Comment by sethvargo** [comment]
Hey @berendt,

I am sorry you are having problems using that Vagrant box from Atlas, and thank you for the bug report. For some boxes, Atlas only acts as a proxy to a user-hosted .box file. In this case, the box author has chosen to self-host the box instead of using Atlas's hosting solution.

Much like code on GitHub is contributed by the community, boxes on Atlas are contributed by the community. Everything under the `ubuntu` namespace is contributed and owned by Canonical - the organization behind Ubuntu. Unfortunately, just like GitHub cannot fix bugs in users' codebases, we cannot fix problems with third-party Vagrant boxes. I would recommend filing an issue with Canonical's support team to see if they can resolve the issue, or use a HashiCorp-provided box such as `hashicorp/precise64`.

Please let me know if you have any questions.
