### ISSUE TITLE
vagrant creating new connections every time it runs

### ISSUE THREAD

**Issue by robme** [mitchellh/vagrant#5792]
Every time I run `vagrant up` it creates a new connection in NetworkManager (I'm using Fedora 21). The hardware address and the IP addresses are the same, but because it adds a new connection it forgets the firewall zone I told it to use last time. This causes the nfs mount to fail (and hang), and I have to Ctrl+C the vagrant up command. It then fails to clean up and I have to Ctrl+C a second time, leaving the box in a broken state. Then I set the firewall zone, run `vagrant destroy` and `vagrant up` again, it works.

After the computer is restarted, the connections in NetworkManager persist, but show as disconnected, and then when I run vagrant up the process above repeats. Every time.

I'm not even sure that the VirtualBox connections should appear in NetworkManager as if they were wired ethernet connections ([one for every box](http://i.imgur.com/VeySOEO.png)). I've tried reporting this to Fedora and they say it's a VirtualBox issue. I've tried reporting it to VirtualBox and they say it's a vagrant issue and they don't support vagrant. So now I'm trying to report it here.

**Comment by mitchellh** [comment]
I'm not very familiar with what you're talking about (NetworkManager, Fedora) except on the surface. I'll just explain everything, and hope you can understand, or that it is even helpful:

1. Vagrant will create a new host-only network if there are no matching ones.

2. Vagrant will remount the NFS folder on every `vagrant up` and `vagrant reload`. This will cause a new network connection to the NFS host over the host-only network. 

3. Vagrant itself does not directly make any network connections to things (from the host). Vagrant on the guest doesn't _directly_ make network connections, except through VirtualBox.

I'm also going to say this is a VirtualBox issue. I don't want to send you on a wild goose chase, so I'll offer advice: the VirtualBox people will ignore any issues that involve Vagrant because it is hard for them to debug. If you can reproduce this outside of Vagrant, then they'll be forced to accept it. I recommend trying that. Note the steps that Vagrant uses above.

I'd be happy to help if you ask specific questions. Or, if you can explain further, I'll look into this further.
