### ISSUE TITLE
Options given to commands using `vagrant ssh -c` fail to work

### ISSUE THREAD

**Issue by ajlanghorn** [mitchellh/vagrant#5820]
I have a virtual machine running in the latest version of Vagrant. Vagrant supports the passing of commands from the host to the guest using the `-c` flag on `vagrant ssh`. For instance, `vagrant ssh -c date` will tell me the date according to the guest, when run from the host. This all works fine so far.

When an option is provided to `date`, say `-u` to convert the output of `date` to UTC, such as `vagrant ssh -c date`, Vagrant complains that the option provided to it was unknown. I initially thought that this was because my shell was expanding the flag passed to date, and therefore giving `-u` to Vagrant which would have resulted in the error described above.

It looks, at least initially, like `vagrant ssh -c` doesn't like options being passed to the commands being run on the guest through the use of `-c`.

Let's take various incarnations of `vagrant ssh -c 'date -u'`, using different quoting around the command to try to work around my shell escaping things:

```
vagrant ssh -c 'date -u'
An invalid option was specified. The help for this command
is available below.

Usage: vagrant ssh [options] [name] [-- extra ssh args]

Options:

    -c, --command COMMAND            Execute an SSH command directly
    -p, --plain                      Plain mode, leaves authentication up to user
    -h, --help                       Print this help
```

```
vagrant ssh -c "'date -u'"
Thu Jun 11 15:59:54 UTC 2015
Connection to 172.16.182.233 closed.
```

A colleague running the same version of Vagrant and Zsh as I am gets the following:

```
vagrant ssh -c 'date -u'
Thu Jun 11 15:37:03 UTC 2015
Connection to 127.0.0.1 closed.
```

So. How come this failed for me, and not for him. Is this a known thing?

I'm confused!

**Comment by sethvargo** [comment]
Hi @ajlanghorn 

Unfortunately this looks to be a problem with your local shell configuration. For some reason it is not passing in the literal and evaluating the string. This is confirmed by the fact that your colleague running the same version of Vagrant is not having issues. Unfortunately I cannot reproduce your issue locally.

If you are able to provide a reproduction case, we can definitely revisit this, but unfortunately we cannot debug individual environment configurations due to the vast number of potential touch points. I would recommend disabling any plugins you have installed and see if that resolves the issue. Thanks! :smile:

**Comment by allen-munsch** [comment]
A little late to this thread, however for anyone else having this issue, of using the `-c` flag for vagrant ssh.

I was able to get the following to work:

```
vagrant ssh -- 'uname -a'
vagrant ssh -- uname -a
vagrant ssh -- "uname -a"
```

I also attempted to run a clean shell using `bash --rcfile "some_empty file"` not sure if it actually runs a no configs shell.
I also tried the `script` command, However both attempts also resulted in the same error.
I also attempted to do `sh -c 'vagrant ssh -c "uname -a"'`, but had the same error.

Ubuntu 18.04
Vagrant 2.2.0
bash 4.4.19(1)-release (x86_64-pc-linux-gnu)
