### ISSUE TITLE
Problems running vagrant 1.7.2 with hyperv on windows 2012

### ISSUE THREAD

**Issue by claudiutraistaru** [mitchellh/vagrant#5829]
There is an issue with the new-vm in import_vm.ps1 script , this should solve it:

```
if ((Get-WmiObject Win32_OperatingSystem).Version -ge 6.3) {
                    # Windows 6.3 and higher = 2012 R2 + 81. http://msdn.microsoft.com/en-us/library/windows/desktop/ms724832(v=vs.85).aspx
                    $vm_params = @{
                        Name = $vm_name
                        Generation = $generation
                        NoVHD = $True
                        MemoryStartupBytes = $MemoryStartupBytes
                        SwitchName = $switchname
                        BootDevice = $bootdevice
                        ErrorAction = "Stop"
                    }
                } else {
                      $vm_params = @{
                        Name = $vm_name
                        NoVHD = $True
                        MemoryStartupBytes = $MemoryStartupBytes
                        SwitchName = $switchname
                        BootDevice = $bootdevice
                        ErrorAction = "Stop"
                    }
                }
```

Sorry I have no access now to a computer to have git installed and push a fix the proper way.

**Comment by sethvargo** [comment]
@sneal @mwrock do you have any insight here? :smile:

**Comment by sneal** [comment]
@sethvargo Win2012R2 [added](https://technet.microsoft.com/en-us/library/hh848537(v=wps.630).aspx) a `-generation` flag which [older](https://technet.microsoft.com/en-us/library/hh848537(v=wps.620).aspx) OSs don't support.

Looks legit, but I don't have a convenient way to try this out. I spot checked the OS version check and it seems correct, but it might be more flexible to test to see if the `New-VM` command support the `-Generation` command rather than check the OS version.

**Comment by mwrock** [comment]
Agree with @sneal that this looks like it will work but checking the params is more robust. I'm not sure if you could get this feature on server 2012 (not R2) by simply installing WMF 4. If so, you would definitely want to have the condition be based on the param or powershell version instead of OS version.

 You could check for the param with:

```
(Get-Command New-VM).Parameters.ContainsKey('Generation')
```

I'd also change the name of this issue to clarify that this would break OS's below 2012R2/8.1 since many mentally equate Server 2012 and 2012R2.

**Comment by mitchellh** [comment]
Fixed!
