### ISSUE TITLE
For multi-vm setups, perform commands without name arg if single box is running

### ISSUE THREAD

**Issue by patcon** [mitchellh/vagrant#5842]
In a Vagrant setup that provisions two machines -- say `ubuntu1404` and `ubuntu1410` -- It might be reasonable for Vagrant to be able to do this:

```
vagrant up ubuntu1404
vagrant provision
vagrant ssh
```

Currently, we get this:

```
ᐅ vagrant ssh      
This command requires a specific VM name to target in a multi-VM environment.
```

**Comment by amosshapira** [comment]
+1

**Comment by sethvargo** [comment]
Hi @patcon 

Thank you for the suggestion. I understand this might be convenient, but I think we should only do this if that's the only machine running. If there is more than one machine running, I think we have to have the user specify the name unfortunately.

**Comment by patcon** [comment]
That sounds perfectly reasonable to me! :)

**Comment by sethvargo** [comment]
Hi @patcon 

I looked into doing this, and, well, it's sad. When we check if a machine is running, we have to ask the underlying provider (virtualbox). I implemented this, and it makes each command that requires a machine name _significantly_ slower because it has to iterate over each machine to see if it's running. While I agree this would be a nice enhancement, I don't think it's worth sacrificing performance. I also like the consistent UX. Sorry! 😦
