### ISSUE TITLE
smart handling of nfs-server service

### ISSUE THREAD

**Issue by shanemikel** [mitchellh/vagrant#5876]
I'd like to see Vagrant stop the nfs-server (only if Vagrant needed to start it to begin with) upon stopping the VMs.

**Comment by mitchellh** [comment]
This sounds like a good feature, but not something we plan on doing on our own since it isn't heavily requested. If you'd like to submit a PR (or anyone else), we'd be happy to look at it. But since we dont' plan on doing it ourselves we're going to close the issue, since it'll otherwise just linger here forever.
