### ISSUE TITLE
Shell provisioner runs `export` commands regardless of Vagrantfile config.ssh.shell setting, returns errors on non-SH-based shells like FreeBSD's TCSH.

### ISSUE THREAD

**Issue by bryson** [mitchellh/vagrant#5888]
Consider the following Vagrantfile:

```ruby
Vagrant.configure(2) do |config|
  config.vm.guest = :freebsd
  config.ssh.shell = "tcsh"

  config.vm.define "dinosaur" do |dino|
    dino.vm.provision "salthost", type: "shell",
      inline: "sudo tcsh -c \"echo '192.168.152.1 salt' >> /etc/hosts\""
  end
end
```

When provisioning runs, Vagrant ignores the value for `config.ssh.shell` and, prior to running my inline command, executes other commands including `export`. TCSH does not support `export`, and instead uses `set` or `setenv`. Because of this, each time the provisioner runs the contents of my script are executed correctly, *and* an error message is returned: 

```text
==> dinosaur: Running provisioner: salthost (shell)...
    dinosaur: Running: inline script
==> dinosaur: export: Command not found.
```

This issue is easily worked around, in this specific situation, by setting `config.ssh.shell = "sh"`. However, this is not ideal, and the value of the `config.ssh.shell` directive should be inspected and properly handled.

**Comment by mitchellh** [comment]
We haven't gotten significant request (only you so far, not to call you insignificant!) for this support and `export` is ingrained pretty deeply in the SSH communicator. I'd kindly ask you to find a workaround for this. If you feel more ambitious I'd look at a PR to fix this, but given the otherwise lack of request, I'm going to mark as "nofix". Sorry.
