### ISSUE TITLE
Insecure world writable dir /usr/local/bin in PATH on MacBook

### ISSUE THREAD

**Issue by abr4xas** [mitchellh/vagrant#5890]
Hi there, i don't know why but:

```
/opt/vagrant/bin/../embedded/gems/gems/vagrant-1.7.2/lib/vagrant/pre-rubygems.rb:31: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
/opt/vagrant/embedded/gems/gems/bundler-1.7.11/lib/bundler/runtime.rb:222: warning: Insecure world writable dir /usr/local/bin in PATH, mode 040777
```

Vagrant version:

```
Latest Version: 1.7.2
You're running an up-to-date version of Vagrant!
```

**Comment by sethvargo** [comment]
Hi @abr4xas 

This warning is coming from Ruby, the underlying language for Vagrant. The issue is that your `/usr/local/bin` folder is world-writable (7-bit on write), which allows anyone (even guests) to put exectuable files in that folder. Since that folder is also in your `$PATH`, OS X will look in that path for binaries.

This is outside of the scope of Vagrant, since you would get this error running many other programs, but you can fix it by changing the permissions on `/usr/local/bin` to read-only for world.
