### ISSUE TITLE
Stuck up with docs right from the beginning

### ISSUE THREAD

**Issue by pitchforks** [mitchellh/vagrant#5938]
I am completely new to Vagrant and this issue describes my first experience with it up to the point where I got totally stuck.

Details about my setup:

OS: Slackware64-14.1 Linux
vagrant-1.7.2 installed from here http://slackbuilds.org/repository/14.1/system/vagrant/ . Apparently it seems to just repackage the official rpm package instead of building from source.

First step: read https://docs.vagrantup.com/v2/getting-started/index.html

It says:

    $ vagrant init hashicorp/precise32
    $ vagrant up

    After running the above two commands, you'll have a fully running virtual machine in VirtualBox  unning Ubuntu 12.04 LTS 32-bit.

Sure this simplicity is a selling point. But instantly, my first question comes up. I like to know a bit more about what's happening behind the curtain, right from the start. As I understand, vagrant might be going to download some stuff. The above example doesn't tell me anything about:

1. Where exactly is it going to download stuff?
2. How can I change the location of my vagrant environment. What if I want to choose a custom location from the start?

In VirtualBox, I can open its GUI and tell it "put my virtual machine image file here, in this custom directory", so I'm just trying to draw an analogy here. (Is it wrong?)

Let's try to find out:

    $ man vagrant
    No manual entry for vagrant

Bah. Is my vagrant install broken or vagrant just doesn't bother to provide a manpage?

Next try:

    $ vagrant --help

This is a bit better. Can I find the answer to my question this way?

    $ vagrant help init

Nothing about locations

    $ vagrant help up

Nothing about locations either.

And at this point I'm completely stuck. I don't know what to do next.

Is my common sense approach wrong or does vagrant need some improvement in this area to look just a bit friendlier to newcomers?

**Comment by sethvargo** [comment]
Hi @pitchforks 

Thank you for opening an issue, and I am sorry you are having problems getting started with Vagrant.

Vagrant follows the standard UNIX-style help, so you can append `-h` or `--help` to any command. For example:

```
$ vagrant up -h
Usage: vagrant up [options] [name]

Options:

        --[no-]provision             Enable or disable provisioning
        --provision-with x,y,z       Enable only certain provisioners, by type.
        --[no-]destroy-on-error      Destroy machine if any fatal error happens (default to true)
        --[no-]parallel              Enable or disable parallelism if provider supports it
        --provider PROVIDER          Back the machine with a specific provider
    -h, --help                       Print this help
```

Vagrant does not publish man pages at this time. The docs on vagrantup.com should be considered the authoritative source of documentation for Vagrant.

In general, the "Getting Started" guide is for users who are new to Vagrant and new to managing virtual machines. The areas of customization you describe (changing the install location of Vagrant, etc) we generally consider to be "power user" features. And while these features are documented, we generally do not consider them to be part of the "Getting Started" guide, since most users will never care to customize those values, and adding them to the guide could cause information overload. As a general rule, we do not discuss Vagrant's internals as part of the Getting Started guide, but they _are documented_ elsewhere in the documentation.

For example, to change the directory where Vagrant stores it's data (including downloaded boxes), you can set the environment variable `VAGRANT_HOME`. This is documented in the [environment variables](http://docs.vagrantup.com/v2/other/environmental-variables.html) section of the documentation.

Does that answer your question?

**Comment by sethvargo** [comment]
(wrong button)

**Comment by pitchforks** [comment]
> For example, to change the directory where Vagrant stores it's data (including downloaded boxes), you can set the environment variable VAGRANT_HOME. This is documented in the environment variables section of the documentation.

> Does that answer your question?

Yes, that's exactly what I was looking for! Of course, I could not know that the answer to my question is at the end of the documentation, while I was only starting to read it. While I understand the policy of keeping the getting started chapter as simple as possible, perhaps it would make sense to have just a reference about this detail right there?

Again, this is by analogy with man pages, which have a FILES (this includes directories as well, because of the "everything is a file" axiom) section. Since UNIX systems have a specific filesystem hierarchy and installed software doesn't just all get dumped into the same directory, I'd say that new users willing to know where the default location for related files is (and how to change that location explicitly) is pretty common.

Thanks for your hint.

**Comment by mitchellh** [comment]
This is a very rare request (and 100% always Linux users, they're the only folks I've ever found to care where the VMs go). This isn't a negative thing, but the getting started guide is meant to be as focused as possible to get started. Even brief "if you care about X, click here" links disengage the flow a bit and I'd rather avoid them. 

Due to the rare request + getting started guide nature, I'm happy to keep this in the "env var" section. If you want to update the other parts of the docs (box section, env vars, etc.) then please make a PR and I'd be happy to do so. Anything outside the getting started guide should take the opposite approach: as much detail as possible. 

Glad you figured it out!
