### ISSUE TITLE
Windows - Orphan Network Adapters

### ISSUE THREAD

**Issue by OwenMelbz** [mitchellh/vagrant#5961]
We're using vagrant on a few windows 7 and windows 8 machines at work, however everybody is building up a nice collection of VirtualBox Host-Only Network adapters each time we create a new Vagrant box.

![image](https://cloud.githubusercontent.com/assets/1094740/8668689/b1e6ddaa-2a05-11e5-9d8a-e438ea7f9854.png)

Wondering if there is a reason for this that we could resolve?

Thanks

**Comment by adamdyson** [comment]
I'm having this problem as well...  and issue [#5377](https://github.com/mitchellh/vagrant/issues/5377) doesn't appear to be fixed either, even when using the latest version 1.7.3

**Comment by cristovaov** [comment]
This is not really a bug IMHO: VB will create a new virtual network adapter for each different IP configured in your Vagrant file under Private Network. You can easily avoid this by making sure each IP is in the same range in your Vagrant file. To clean up those adapters you can do so in the VB GUI under 'Preferences->Network->Host-only Networks'

**Comment by OwenMelbz** [comment]
@cristovaov I agree with you how it can be mitigated, however surely the created adapter should be removed when the "destroy" command is run? As a user you would expect the things that were created to be removed surely?

**Comment by cristovaov** [comment]
@OwenMelbz yes and ... no: I frequently destroy Vagrant vms and recreate them -- In my use case it would drive my Windows and VB a bit nuts should Vagrant remove the adapters on each destroy or halt and make VB recreate it.  
However, perhaps a Vagrant command that cleans up unused adapters would be handy in your case. Don't know if its feasible or if a Vagrant plugin already exists for that.

**Comment by aneeshusa** [comment]
@adamdyson Can you explain more about what's not working with the fix for #5377? I'd love to fix it if my original PR didn't fully take care of it.

**Comment by adamdyson** [comment]
@aneeshusa I've gone back to using Ubuntu 14.04, from memory you're fix did work when I tried using VirtualBox as the provider. However I prefer using VMWare Workstation, one of the reasons is because of this issue #5946

**Comment by aneeshusa** [comment]
@adamdyson Sorry about that! My PR includes a patch for VirtualBox, smb and NFS shared folder implementations because those are present in the open-source code; Hashicorp would need to apply the fix to the closed-source VMware provider themselves (if they haven't already). Glad to hear it worked for you on VirtualBox.

**Comment by mitchellh** [comment]
We've gone back and forth on removing the interfaces. You're right that we're quite capable of it. The issue is that the interfaces are often needed again shortly and also we can't detect if any other VMs run by _other_ users are using the interfaces (the much, much bigger issue). Therefore, it is unsafe on Windows to actually remove the interfaces.

We do remove the interfaces on Unix-like machines. 

Unfortunately I think due to the way that the API layer works with VirtualBox on Windows, we're going to have to keep it as-is.
