### ISSUE TITLE
Option for booting up vm without communications (ssh/winrm)

### ISSUE THREAD

**Issue by sumkincpp** [mitchellh/vagrant#5982]
It is great to use vagrant locally to manage virtual machies, 
But usually not all of them support ssh/winrm providers (i.e. telnet only support).

Would be great to have an option to not to wait vagrant for communication to those machine
as well as no to emit any communication errors during this boot.

In other words - using vagrant as external provisioner for virtualbox/vmware/etc..

**Comment by sethvargo** [comment]
Hi @sumkincpp 

Thank you for opening an issue. I think, in these cases, you are better off using the VBoxManage commands directly. Vagrant needs SSH/WinRM in order to run provisioners and validate the machine boot was successful. You may be interested in the upcoming Virtualbox and VMware support in [Terraform](https://www.terraform.io), which will provide this functionality. Thanks!
