### ISSUE TITLE
vagrant up error

### ISSUE THREAD

**Issue by emakis** [mitchellh/vagrant#6130]
```
C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/settings.rb:226:in `exist?': "\x9E" to UTF-8 in conversion from Windows-1253 to UTF-8 (Encoding::UndefinedConversionError)
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/settings.rb:226:in `exist?'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/settings.rb:226:in `load_config'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler/settings.rb:11:in `initialize'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:224:in `new'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:224:in `settings'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:422:in `configure_gem_home_and_path'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:92:in `configure'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:153:in `definition'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/bundler-1.10.5/lib/bundler.rb:123:in `setup'
        from C:/HashiCorp/Vagrant/embedded/gems/gems/vagrant-1.7.4/bin/vagrant:71:in `<main>'
```

I have windows10, greek language at first, installed english as primary system lang but doesn't work

**Comment by sethvargo** [comment]
Hi @emakis 

Thank you for opening an issue. We are tracking all the encoding issues in #5896 since they are all related.

**Comment by samphippen** [comment]
Hi @emakis this is caused by this line of code here:

`https://github.com/bundler/bundler/blob/v1.10.5/lib/bundler/settings.rb#L11`

Can you still reproduce this issue? If so, would you mind running this command in the directory with your Vagrantfile:

```
ruby -e "p Dir.pwd.bytes; p '------------'; p Dir.pwd.encoding"
```
This will help us debug the issue and hopefully fix it.

Thanks

**Comment by samphippen** [comment]
`0x9e` isn't a valid character in windows-125*, or extended ascii, so I'm not sure how we got here. @emakis can you still reproduce this?

**Comment by senki** [comment]
I have a very similar issue in OS X (10.11.1 with vagrant 1.7.4)
First line of my error is:

    Progress: 90%/opt/vagrant/embedded/lib/ruby/2.0.0/json/common.rb:224:in `encode': "\xCC" from ASCII-8BIT to UTF-8 (Encoding::UndefinedConversionError)

I figured out there is a non-ASCII character in my path: 

    ~/Works/Abszolút/abszolut

the output of `ruby -e "p Dir.pwd.bytes; p '------------'; p Dir.pwd.encoding"` is:

    [47, 85, 115, 101, 114, 115, 47, 109, 97, 117, 108, 105, 115, 47, 87, 111, 114, 107, 115, 47, 65, 98, 115, 122, 111, 108, 117, 204, 129, 116, 47, 97, 98, 115, 122, 111, 108, 117, 116, 102, 97, 108, 46, 104, 117]
    "------------"
    #<Encoding:ASCII-8BIT>

The problem is reproducible.

I can rename my path, but I'm Hungarian, and many non-ASCII characters available eg. "áéíöüóőúű", so its hurts. :)

Hope, this can help to resolve the encoding issues.
