### ISSUE TITLE
config.vm.network forwarded port should not bind to all IP addresses by default

### ISSUE THREAD

**Issue by orf** [mitchellh/vagrant#6133]
I was surprised to find today that the forwarded ports on vagrant bind to all IP addresses on your host by default, leaving any apps you are running on exposed to anyone on your internal network. I strongly believe that the default should be an internal IP address, with an option to expose the port on any IP address.

I mean if you want to expose a database through :forwarded_port the defaults mean that anyone on the network can connect to it. Combined with the fact that development databases/apps generally have weaker security than production (or one would hope) means I don't think its a fantastic idea to offer access to anyone by default.

**Comment by sethvargo** [comment]
Hi @orf 

Thank you for opening an issue. Please note that Vagrant's primary concern is _not_ security. Vagrant is a development tool and it is not designed or encouraged to be used in "production-like" environments. For example, all public Vagrant boxes share the same keypair (which is public) and eases the process of connecting to the machine.

If you only want to share networking with your host, you should use the "host-only" networking option.

I think there exists an opposite use case where a user _wants_ to share a database or service with others on their network. In fact, this is often a requested feature.

You can also specify the `guest_ip` and `host_ip` values when setting the forwarded port to restrict this, but I think "open" is a good default value since it minimizes the configuration the typical user needs to get Vagrant up-and-running. http://docs.vagrantup.com/v2/networking/forwarded_ports.html

Does that make sense?

**Comment by orf** [comment]
Thanks for replying, you are quite right that Vagrant's primary concern is not security and shouldn't be used in production like environments. However this doesn't make it any less surprising that by default the forwarded ports option opens the port to everyone on your network, and is no reason for Vagrant to be insecure by default. For those of us developing in a fairly large company with a large internal network it's a scary thought that my development database and app (which could contain privileged information) has been accessible all this time.

There is no information (other than the host_ip documentation line) saying that by default **your app is available to anyone**, and at the very least there should be a banner/warning message of some sort. There is no example code showing off this parameter, and that's what 99% of users are going to copy and use.

There is no doubt that there is an opposite use case where a user wants/needs to share a database/service with others, but this is surely the minor use case rather than the default. Vagrant is all about starting a development VM quickly, and while security is not it's goal it shouldn't be insecure by default. This is a clear violation of the [principle of least astonishment](https://en.wikipedia.org/wiki/Principle_of_least_astonishment).

**Comment by sethvargo** [comment]
@orf I have to disagree that the opposite use case is "minor". It's actually one of the most common use cases. In fact, users wanted to share with people _outside_ of their network, which is why we created `vagrant share`. I totally understand that this isn't _your_ use case, but please also understand that Vagrant is used by thousands of other people who have different use cases :smile:.

I would be happy to add a note/warning to the documentation, but I don't think we should change this behavior. For the standard user, Vagrant should "just work" without having to change bind ip addresses and firewall rules. For power users who are concerned with those features, there exists an option to increase that security. I agree we could do a better job of documenting it though.

**Comment by mitchellh** [comment]
Fixed (docs).

**Comment by adeck** [comment]
+1

As far as I'm concerned, this is a design flaw. The argument "security is not a concern of this application" is irrelevant; this **actively** decreases the security of the machine it's on to by default. If the attack vector were local, this would be understandable, but it it increases the network-facing attack surface. More to the point, (at least in my case and that of the OP) it violated the Principle of Least Surprise.

"For the standard user, Vagrant should "just work" without having to change bind ip addresses "
Some users want this feature. Have you actually polled what percentage of users would want this as a default? Or what percentage of users assumed the default was 127.0.0.1?
