### ISSUE TITLE
Add vagrant info command

### ISSUE THREAD

**Issue by hollodotme** [mitchellh/vagrant#6184]
Please add a `vagrant info` command that shows information about the importet box at the current working dir. 
Especially the current box version cannot be determined at the moment. I only can list all versions of added boxes by `vagrant box list`.

The following output of `vagrant info` would be helpful: (example data)
- Box name: devops000
- Box description: Ubuntu Server 14.04.1 LTS 64 Bit
- Box URL: http://example.com/vagrant/boxes/devops000.json
- Current box version: 1.0.6
- Version constraint (in Vagrantfile): ~1.0.5
- Box is outdated: yes, available version: 1.0.7

I have some self-packaged, self-versioned boxes with a json catalog managing the versions and a lot of projects I am using these boxes. Before I (blindly) destroy imported boxes in my projects to be sure I get the latest version, it would be nice to get this information listed above.

Thanks in advance.

**Comment by sethvargo** [comment]
Should also list forwarded ports

**Comment by dragon788** [comment]
One thing we are looking at implementing (which only works if you are building your own boxes) is leaving a box version "fingerprint" inside the box so that we can tell what version the box is without using Vagrant in case it crashes or a user boots the box manually after vagrant has imported it. There are ways to get the box version using the existing metadata and machine index files, but its a pain, this feature would be awesome.

**Comment by chrisroberts** [comment]
Hi there,

We would really like this, but this issue has been open for over a year with no one working on it, Leaving it open is unfortunately making our issue count look higher than it is. I’m going to close this and if someone wants to work on it I’d still be open to a PR!

Cheers!
