### ISSUE TITLE
Vagrant is attempting to interface with the UI in a way that requires a TTY. Most actions in Vagrant that require a TTY have configuration switches to disable this requirement. Please do that or run Vagrant with TTY.

### ISSUE THREAD

**Issue by saifulmasud** [mitchellh/vagrant#6194]
Occuring this problem while adding vagrant box to laravel/Homestead in git bash => "vagrant box add laravel/homestead"

**Comment by srrobinson** [comment]
This is likely related to issue #6026, probably want to keep track of that.

**Comment by Swader** [comment]
+1, getting this also on Win 10, 1.7.4 vagrant, 5.0.2 VirtualBox. Manual export helped

**Comment by jonathanborges1542** [comment]
Try running command with --provider virtual, it worked for me.

**Comment by jaminscript** [comment]
> --provider virtual

Worked for me!

**Comment by raakesh** [comment]
using --provider virtualbox worked for me.

**Comment by sethvargo** [comment]
Hi all,

Thank you for opening an issue. I believe this is occurring because of an issue in the laravel/homestead box and not Vagrant. That being said, I tried a few Vagrant boxes here locally (including the latest laravel/homestead), and none of them exhibited this issue.

I am going to close this issue, since the problem appears to be fixed. The other thing you can try (if using git bash) is to tell Vagrant you are using cwgwin:

```
export VAGRANT_DETECTED_OS=cygwin
```

**Comment by sourcec0de** [comment]
@sethvargo the export solved this issue for me.

**Comment by ccasciotti** [comment]
@sethvargo thanks man it worked for me

**Comment by Arjun1811** [comment]
When i go to my project ..for example - /cygdrive/c/project/HoXXey/Project-tt  and do a vagrant destroy .it is throwing Error Vagrant is attempting to interface with the UI in a way that requires
a TTY. Most actions in Vagrant that require a TTY have configuration
switches to disable this requirement. Please do that or run Vagrant
with TTY.
What is vagrant with TTY
