### ISSUE TITLE
Vagrant up failing on VMWare

### ISSUE THREAD

**Issue by pikeas** [mitchellh/vagrant#6201]
```
$ vagrant up --provider vmware_fusion                                                                                                                        Bringing machine 'docker' up with 'vmware_fusion' provider...
==> docker: Box 'coreos-beta' could not be found. Attempting to find and install...
       docker: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
       docker: Box Version: >= 0
==> docker: Loading metadata for box 'http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant_vmware_fusion.json'
       docker: URL: http://beta.release.core-os.net/amd64-usr/current/coreos_production_vagrant_vmware_fusion.json
==> docker: Adding box 'coreos-beta' (v766.1.0) for provider: vmware_fusion
       docker: Downloading: http://beta.release.core-os.net/amd64-usr/766.1.0/coreos_production_vagrant_vmware_fusion.box
       docker: Calculating and comparing box checksum...
==> docker: Successfully added box 'coreos-beta' (v766.1.0) for 'vmware_fusion'!
==> docker: Cloning VMware VM: 'coreos-beta'. This can take some time...
==> docker: Checking if box 'coreos-beta' is up to date...
==> docker: Verifying vmnet devices are healthy...
==> docker: Preparing network adapters...
==> docker: Starting the VMware VM...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Users/me/code/.vagrant/machines/docker/vmware_fusion/95710fcd-22bf-4e41-98a7-6f0893b9dd91/coreos_production_vagrant_vmware_fusion.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2015-08-26T21:04:06.822| ServiceImpl_Opener: PID 16332
Error: The operation was canceled

Stderr:
```

Vagrant 1.7.4 bringing up CoreOS-beta 766.1.0 on VMWare Fusion 8 with vagrant-wmware-fusion 4.0.1

**Comment by sethvargo** [comment]
Hey @pikeas,

Unfortunately "The operation was canceled" is a notoriously opaque error message we get out of the VMware tooling, and it can indicate any number of issues, including:

 * File permissions errors on the VMware install
 * A VM that is requesting too more resources than the host machine has
 * Some error message that only shows up in the GUI
 * Other misc problems

We'll have to dive into the VMware logs to figure out what's going on here.

VMware actually ships a tool that helps collect diagnostic information and packages it up into a nice zip file:

http://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1003894

Can you follow the instructions in that link to generate the file and send it to support@hashicorp.com? You're welcome to inspect the zip file if you are concerned about what details are being sent, and the script that generates the file is also viewable so you can see what it's doing.

With that information, hopefully we can get to the bottom of this issue! Since the VMware plugin qualifies under commercial support, you can email support@hashicorp.com and get a faster response. Thanks! :smile:
