### ISSUE TITLE
vagrant up hangs mounting folders - OSX Host, Win7 Guest, ssh from cygwin installed on guest

### ISSUE THREAD

**Issue by jhkrischel** [mitchellh/vagrant#6220]
Starting from a modern.ie Win7/IE10 box, installed and configured cygwin sshd, created a base box, but vagrant up stalls:

```
DEBUG ssh: stdout: Windows PowerShell 
Copyright (C) 2009 Microsoft Corporation. All rights reserved.


DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...
DEBUG ssh: Sending SSH keep-alive...

```

In the actual VM, the network share shows as properly connected.

It does _not_ hang if I don't put this in the Vagrantfile:

```
config.vm.guest = :windows
```

But it does pop this error:

```
The guest operating system of the machine could not be detected!
Vagrant requires this knowledge to perform specific tasks such
as mounting shared folders and configuring networks. Please add
the ability to detect this guest operating system to Vagrant
by creating a plugin or reporting a bug.
```

**Comment by jhkrischel** [comment]
My guess is that when I don't use winrm, it decides that it's a linux variant, and pops the error, but when I specifically tell it that it's a windows guest, it can't properly handle ssh.

**Comment by sethvargo** [comment]
Looks like this might be the same or at least related to https://github.com/mitchellh/vagrant/issues/6230

**Comment by mikhelev** [comment]
@jhkrischel , did you find answer on your problem?

**Comment by bryanwb** [comment]
@jhkrischel i am also seeing a similar issue, would love to know if you found a workaround

**Comment by tjuerge** [comment]
Same here.

I started with the MSEdgeOnWin10 Vagrant Box availabe from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/windows/. This box comes with the OpenSSH server from http://www.mls-software.com/opensshd.html. So it's possible to start this box with the following settings:
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "Windows10"
  config.vm.guest = :windows
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.ssh.username = "IEUser"
  config.ssh.password = "Passw0rd!"
  config.ssh.insert_key = false

  config.vm.provider "virtualbox" do |vb|
    vb.cpus = 2
    vb.memory = 1024
  end
end
```
Here the guest type "windows" is combined with communicator type "ssh". If the Vbox shared folder mounting is disabled then the box starts flawlessly and `vagrant ssh` can be used to access the OpenSSH server / Cygwin shell within Windows.

Enabling Vagrants synced folder support brings up this SSH keep-alive issue. Here the culprit is in [`plugins/guests/windows/cap/mount_shared_folder.rb`](https://github.com/mitchellh/vagrant/blob/master/plugins/guests/windows/cap/mount_shared_folder.rb#L26) where a PowerShell script is executed despite of communicator "ssh".

So in `mount_shared_folder()` the winrm-related stuff could be embedded in an conditional block which checks the communicator first, e.g.
```ruby
def self.mount_shared_folder(machine, name, guestpath, vm_provider_unc_base)
  if machine.config.vm.communicator == :winrm
  	name = name.gsub(/[\/\/]/,'_').sub(/^_/, '')
    path = File.expand_path("../../scripts/mount_volume.ps1", __FILE__)
    script = Vagrant::Util::TemplateRenderer.render(path, options: {
      mount_point: guestpath,
      share_name: name,
      vm_provider_unc_path: vm_provider_unc_base + name,
    })

    machine.communicate.execute(script, shell: :powershell)
  else
    if machine.communicate.test("uname -o | grep Cygwin")
      # Map the drive via "NET USE \* \\\\vboxsvr\\{#guestpath} {#ssh password} /USER:{# ssh user} /PERSISTENT:YES"
      # and create a symlink via "cmd /c mklink /d {#guestpath} {# mapped drive}"
      # Same way as in "plugins/synced_folders/smb/scripts/mount_share.ps1"
  	end
  end
```
In the else block the ssh-related stuff (running in the Cygwin shell) could be implemented similar to the PowerShell script [`plugins/synced_folders/smb/scripts/mount_share.ps1`](https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/plugins/synced_folders/smb/scripts/mount_share.ps1#L27):
* Mapping the VBox synced folder to a new Windows drive via `NET USE \* \\\\vboxsvr\\{#guestpath} {#ssh password} /USER:{#ssh user} /PERSISTENT:YES`
* Extracting the letter of the mapped drive from the output
* Creating a symlink via `cmd /c mklink /d {#guestpath} {# mapped drive}`

Doing this manually after via `vagrant ssh`:
```
==> default: The machine you're attempting to SSH into is configured to use
==> default: password-based authentication. Vagrant can't script entering the
==> default: password for you. If you're prompted for a password, please enter
==> default: the same password you have configured in the Vagrantfile.
IEUser@127.0.0.1's password:
Last login: Thu Jun  9 08:02:55 2016 from 10.0.2.2
-sh-4.1$ net use \* \\\\vboxsvr\\vagrant Passw0rd! /USER:IEUser /PERSISTENT:yes
Drive Y: is now connected to \\vboxsvr\vagrant.

The command completed successfully.

-sh-4.1$ cmd /c mklink /d vagrant y:
symbolic link created for vagrant <<===>> y:
-sh-4.1$ ls -l vagrant
lrwxrwxrwx 1 IEUser None 11 Jun  9 12:11 vagrant -> /cygdrive/y
-sh-4.1$
```
I'm not used to Ruby and Vagrant's code base. So I've no clue about executing these commands in the guest and extracting the drive letter from the output.
