### ISSUE TITLE
Vagrant 1.7.3 subprocess jail breaks execution of external ruby commands

### ISSUE THREAD

**Issue by neovatar** [mitchellh/vagrant#6242]
I just noticed, that starting with Vagrant 1.7.3 the execution of ruby commands via the vagrant-triggers plugin (and possibly all exeution of external ruby commands) is broken.

When calling a command via vagrant-triggers `run`, vagrant-triggers takes care to delete `GEM_HOME`, `GEM_PATH` and `GEMRC` from the environment (in https://github.com/emyl/vagrant-triggers/blob/master/lib/vagrant-triggers/dsl.rb#L87), so we can execute ruby commands, that depend on a non vagrant ruby environment.

But vagrant introduced a new "magic" to check if it is executed via bundler, and restores the vagrant environment for the subprocess. So if you call a ruby process, vagrant enforces the old environment and `GEM_HOME`, `GEM_PATH` and `GEMRC` point to the vagrant specific gem locations and things break because gems are not found.

We can set `VAGRANT_SKIP_SUBPROCESS_JAILBREAK` environment variable to disable the magic, but we need to set it before calling vagrant. Setting it in the Vagrantfile does not seem to work.

https://docs.vagrantup.com/v2/other/environmental-variables.html

> VAGRANT_SKIP_SUBPROCESS_JAILBREAK

> As of Vagrant 1.7.3, Vagrant tries to intelligently detect if it is running in the installer or running via Bundler. Although not officially supported, Vagrant tries its best to work when executed via Bundler.  When Vagrant detects that you have spawned a subprocess that lives outside of Vagrant's installer, Vagrant will do its best to reset the preserved environment dring the subprocess execution.

> If Vagrant detects it is running outside of the officially installer, the original environment will always be restored. You can disable this automatic jailbreak by setting the VAGRANT_SKIP_SUBPROCES_JAILBREAK.

I am not sure, how to work around this or how to switch off this behaviour from within the Vagrantfile. It was introduced in Vagrant 1.7.3 (a minor release) and breaks stuff that worked with 1.7.2.

@mitchellh Is there anything I can do to disable the jailbreak magic from within a Vagrantfile? I can change all projects Vagrantfiles, but I cannot tell all developers to call vagrant via `VAGRANT_SKIP_SUBPROCES_JAILBREAK=1 vagrant ...`. If there is no such control setting within the Vagrantfile, there really should be one.

**Comment by neovatar** [comment]
This ugly monkey patch can be placed into the Vagrantfile to make calling of external out of vagrant ruby applications possible again:

```
module Vagrant
  module Util
    class Subprocess
      def jailbreak(env = {})
        return
      end
    end
  end
end
```

**Comment by sethvargo** [comment]
Hi @neovatar 

This jailbreak is 100% necessary when shelling out to subprocesses. Subprocesses themselves need to correctly setup their required environment. Vagrant does _not_ reset the environment when the process lives inside the Vagrant omnibus repo. Without resetting the environment, it is almost impossible to shell out to a non-vagrant-related Ruby process (like Chef, Puppet, etc). There are tens of closed issues that the jailbreak solved, and you can read the detailed comment in the code explaining why this is technically necessary: https://github.com/mitchellh/vagrant/blob/3b7117b6890dee24af540bb53f726ae45f301bc5/lib/vagrant/util/subprocess.rb#L263-L289.

It is important to note that the `GEM*` variables are not reset to a vagrant-specific location; they are reset to whatever value was present in the environment before the user ran a `vagrant` command. The environment is restored to whatever existed in `env` prior to running `vagrant`. This process of storing the environment is handled by [the Vagrant launcher](https://github.com/mitchellh/vagrant-installers/blob/9e058bc5603e118679adbd10c7f7549347e53319/substrate/launcher/main.go#L118-L156). 

I definitely understand your frustration, and the intention was certainly not to introduce a breaking change in a patch release. However, this actually _fixed_ the process of shelling out to other Ruby programs. It was previously broken on Chef, Puppet, or any other Ruby program that lived outside of Vagrant. I believe the issue here is that vagrant-triggers heavily depends on the internal API implementation of subprocess. Let's try to find a way to decouple that so this doesn't happen in the future :smile:

Curiously - [Vagrant does not jailbreak if it's executing its own plugin](https://github.com/mitchellh/vagrant/blob/3b7117b6890dee24af540bb53f726ae45f301bc5/lib/vagrant/util/subprocess.rb#L97-L103), so the existing behavior should be exactly the same between 1.7.2 and 1.7.3. Perhaps that "internal plugin detection" piece is just the broken part. 

I'm personally not very familiar with vagrant-triggers internals, so if you could shed some light, that would be super helpful.

**Comment by neovatar** [comment]
Thanks for the quick answer @sethvargo!

For reference: I also opened an issue for vagrant-triggers yesterday, because I was not sure which side it needs to be fixed: https://github.com/emyl/vagrant-triggers/issues/52

I agree with you, that this should be fixed with the main goal to prevent future breakage.

> It is important to note that the GEM* variables are not reset to a vagrant-specific location; they are reset to whatever value was present in the environment before the user ran a vagrant command. The environment is restored to whatever existed in env prior to running vagrant.

Actually exactly this seems to happen. I'll describe what seems to happen, please correct me if I am wrong:

- we use ruby via rbenv, so GEM* variables are not set normally, the variables are not set (this is the standard rbenv setup)
- [vagrant launcher sets up a new environment](https://github.com/mitchellh/vagrant-installers/blob/9e058bc5603e118679adbd10c7f7549347e53319/substrate/launcher/main.go#L118-L156), adding its values to GEM (in fact creating them, if not set)
- we use vagrant-triggers to run berks (installed via a rbenv ruby) on :up
- [vagrant-triggers saves the current environment, prepares an environment runs the command and restores the environment afterwards] (https://github.com/emyl/vagrant-triggers/blob/v0.5.1/lib/vagrant-triggers/dsl.rb#L34-L58)

**Comment by neovatar** [comment]
I did a bit more debugging, not sure if I am on the right track:

If I understand the [jailbreak code](https://github.com/mitchellh/vagrant/blob/3b7117b6890dee24af540bb53f726ae45f301bc5/lib/vagrant/util/subprocess.rb#L293-L294) correctly, it will do the following:

If `::Bundler::ORIGINAL_ENV` is defined, use it and merge it with the environment saved `Vagrant.original_env` by the vagrant launcher. When I start vagrant, there are no GEM* environment variables and this is correctly saved in `Vagrant.original_env`. But in `::Bundler::ORIGINAL_ENV` the following GEM* environment variables are set:

```
 ["GEMRC", "/opt/vagrant/embedded/etc/gemrc"],
 ["GEM_HOME", "/opt/vagrant/embedded/gems"],
 ["GEM_PATH", "/home/tom/.vagrant.d/gems:/opt/vagrant/embedded/gems"]
```

So after the merge, the GEM* variables are in the environment and confuse the launched ruby to look for gems there.

I am not sure, why this is the case. Shouldn't `::Bundler::ORIGINAL_ENV` contain the original environment that existed, before `require "bundler"` was executed?

I used this simplified Vagrantfile for testing:

```
require 'pp'

pp 'Vagrant.original_env'
pp Vagrant.original_env.to_h.sort

pp '::Bundler::ORIGINAL_ENV'
pp ::Bundler::ORIGINAL_ENV.to_h.sort

Vagrant.configure('2') do |config|

  box_name = 'trusty-server-cloudimg-amd64-vagrant-disk1'
  box_url = 'https://cloud-images.ubuntu.com/vagrant/trusty/current/trusty-server-cloudimg-amd64-vagrant-disk1.box'
  
  config.vm.define 'test-1' do |server|
    server.vm.box = box_name
    server.vm.box_url = box_url
    server.vm.network :private_network, ip: '192.168.33.42'
  end

end
```

**Comment by emyl** [comment]
FYI, I've updated vagrant-triggers for skipping jailbreak using the holy `VAGRANT_SKIP_SUBPROCESS_JAILBREAK` :smiley:

**Comment by sethvargo** [comment]
Hi all,

After thinking about this more, it seems like only vagrant-triggers would have been affected by this, and the maintainer has allowed that plugin to execute in the correct context via the provided workaround :smile:
