### ISSUE TITLE
request: --machine-readable running status

### ISSUE THREAD

**Issue by thechrisroberts** [mitchellh/vagrant#6310]
I've written an in-house command line utility to use alongside our custom Vagrant boxes. One feature is the ability to dump all database backups to a backup folder on the local machine. A brief command line script makes it easy to use this alongside crontab to help with forgetful devs. Since I don't want to attempt the backup if the vm isn't running, the script first checks 'vagrant status --machine-readable' and greps the output for 'state,running'. This works well enough, but it would be nice to simplify the conditional by having a way to get a simple 0/1 response when checking if the box is running.

**Comment by mitchellh** [comment]
We've attempted to do this but it is somewhat complicated since the state for running is different for each provider and some folks want exit code 0 if the machine is _created_ vs _running_ and so on.

I think your grep approach is unfortunately the best approach going forward. Thanks for the suggestion though.
