### ISSUE TITLE
Cant get "vagrant up" to work

### ISSUE THREAD

**Issue by gilkedar** [mitchellh/vagrant#6317]
I installed vagrant 1.7.3 on my centOS 6.4, which is on a virtualbox 5.
i do the vagrant init, and then vagrant up, but always recieve the "no usable default provider found..."
I tried editing the enviromental settings as recommended in other issues with no success. 
am i missing something? is there an incompatibility with those versions?
![vagrant up issue](https://cloud.githubusercontent.com/assets/14829279/10089682/4a1c1d12-632f-11e5-9411-ae1bb3e41de2.JPG)

**Comment by loiclavoie** [comment]
You typed virtulbox instead of virtualbox

**Comment by gilkedar** [comment]
Hi thanks for the comment. when i took the snapshot i did indeed misspell, however i tried to "vagrant up" so many time, using VirtualBox,virtualbox, other Vagrantfiles, and still no success.
I am really out of ideas=/ 
thanks for the help.

**Comment by loiclavoie** [comment]
Well, to choose a provider, you must have installed it first. Did you install VirtualBox?

http://tecadmin.net/install-oracle-virtualbox-on-centos-redhat-and-fedora/

**Comment by gilkedar** [comment]
Thanks loiclavoie.
I'm a little confused. I have Virtualbox 5 on my computer, on which i installed centos-6.4
am i supposed to install VirtualBox again on the centOS? 
sorry for this n00b question

**Comment by loiclavoie** [comment]
Well, vagrant is creating VM's... So it has to be on the same level as your virtualbox. He's using the VM provider to create a certain instance and then allow you to configure it via other tool (puppet and stuff like that, depending on what you'll do with that VM).

**Comment by yloh-ewn** [comment]
To use VirtualBox 5, you should use master as VB5 support was only committed a few days ago.

**Comment by gilkedar** [comment]
Thank you guys so much for your help so far :)
i installed virtualbox 5 with your awesome guide(altough i had lots of kernel issues, but i finally got virtualbox to work).
now vagrant up finally started working, but then i got this message:

![timeout](https://cloud.githubusercontent.com/assets/14829279/10305704/6e351ad8-6c2a-11e5-9902-526eda79ee3d.JPG)


Any ideas? i hope its not related to the kernel issues

**Comment by gilkedar** [comment]
I fixed the kernel issues, and now i loaded the whole system from the updated kernel(2.6.32-573.7.1.el6.x86_64), and i even tried new boxes that fit centOS 6.7 :
   i made a new vagrantfile  $vagrant init bento/centos-6.7
   and then tried vagrant up but still getting connection time out
I am running out of options =/
thanks for the help guys.

**Comment by yloh-ewn** [comment]
I've been using box centos/7 and had to spin my own box (removing networkmanager, cleaning up dhclient lease data, stripping down ifcfg-eth0) to make it work properly. Likely, this is the same problem you're having.

**Comment by sethvargo** [comment]
Hi @gilkedar 

Thank you for opening an issue. In order to use VirtualBox 5 with Vagrant, you will need to install Vagrant 1.7.4+. You can download the latest release of vagrant from https://www.vagrantup.com/downloads.html. Please note that the versions of Vagrant included in PPAs and similar repos often include a very outdated version that does not include the latest features or patches.

There were issues with redhat guests during the initial release of Virtualbox 5 that were patched in a subsequent release, so please try upgrading to the latest version of vbox 5.

If this issue is still occurring, could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
