### ISSUE TITLE
vagrant rdp not attempting to authenticate against vagrant box

### ISSUE THREAD

**Issue by luciusbono** [mitchellh/vagrant#6358]
I think I understand what the problem is here, but here's what the behavior is. Windows 10 host, Windows 10 vagrant box. `vagrant rdp` yields the following message box, which is expected: 

![capture](https://cloud.githubusercontent.com/assets/5789441/10271707/cf7a9500-6ac9-11e5-9adb-0bdedcb28920.PNG)

But the password (`vagrant` in this case) does not work. On a hunch, I clicked `Use Other Accounts` and tried login in with the user `.\vagrant`, which autoresolves to `[hostname]\vagrant` and suddenly it works. 

Saving these credentials does nothing, the prompt returns at next `vagrant rdp`. I confirmed that there is an entry in `cmdkey` that seems like it should work:

```
Target: Domain:target=TERMSRV/127.0.0.1
Type: Domain Password
User: DESKTOP-ECDULQG\vagrant
Local machine persistence
```

But if vagrant rdp isn't passing the hostname of the vagrant box along I could see how this wouldn't be picked up. 

Am I doing something wrong here?

**Comment by sethvargo** [comment]
Hi @luciusbono 

Could you please share the box you are using? This might be a bug with the box itself.

**Comment by luciusbono** [comment]
Sure thing! https://github.com/luciusbono/Packer-Windows10

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
