### ISSUE TITLE
The executable 'bsdtar' Vagrant is trying to run was notfound in the %PATH% variable. - On Vagrant 1.7.2

### ISSUE THREAD

**Issue by ehiaig** [mitchellh/vagrant#6390]
Hello There,

I've been trying to install laravel homestead. I currently have vagrant 1.7.2 on my windows 64 laptop.

I got this:

```
$ vagrant box add laravel/homestead
==> box: Loading metadata for box 'laravel/homestead'
    box: URL: https://atlas.hashicorp.com/laravel/homestead
==> box: Adding box 'laravel/homestead' (v0.3.0) for provider: virtualbox
    box: Downloading: https://atlas.hashicorp.com/laravel/boxes/homestead/versions/0.3.0/providers/virtualbox.box
    box:
The executable 'bsdtar' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.
```

I uninstalled vagrant, restart my computer then reinstalled again. I even deleted the hashicorp folder as well as the content of the tmp folder in c://users/me/.vagrant.d/tmp

Then I tried to run the command (vagrant box add laravel/homestead) again, Yet I got the same message.

Is there something I'm not doing right? Or where do you think I can find the bsdtar to add to my path.

**Comment by sethvargo** [comment]
Hi @ehiaig 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. There were a number of issues with Vagrant 1.7.2's installer, and I believe they have been fixed in Vagrant 1.7.4. Could you please give Vagrant 1.7.4 a try? If that does not work for you, could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html) as well as your system specifications?

**Comment by ehiaig** [comment]
Thanks Sethvergo, I resolved the problem by installing LibArchive which I downloaded from http://gnuwin32.sourceforge.net/packages/libarchive.htm.

**Comment by sethvargo** [comment]
Thanks! I am glad it's working for you :smile:
