### ISSUE TITLE
setting hostname in CentOS 6.6 fails

### ISSUE THREAD

**Issue by sepetrov** [mitchellh/vagrant#6427]
Vagrant fails to set the hostname. Similar issue was reported in https://github.com/mitchellh/vagrant/issues/4352

Host OS: Mac OS El Capitan (version 10.11)
Guest OS: CentOS release 6.6 (Final)
VirtualBox: 5.0.8 r103449
Vagrant log: https://gist.github.com/sepetrov/eb6eb37b599586ff268b

**Comment by kamigerami** [comment]
It seems to believe your guest os is running atomic.

```
INFO guest: Autodetecting host type for [#<Vagrant::Machine: dev (VagrantPlugins::ProviderVirtualBox::Provider)>]
 INFO ssh: Execute: grep 'ostree=' /proc/cmdline (sudo=false)
 INFO guest: Detected: atomic!
````
which is why it is trying to run the ```hostnamectl set-hostname```command and failing since either the path to that command does not exist or the binary does not exist on your box most likely.

Did you try it with another centos 6 box.

If not have a look at https://atlas.hashicorp.com/boxes/search
