### ISSUE TITLE
Vagrant el capitan freezes

### ISSUE THREAD

**Issue by shopblocks** [mitchellh/vagrant#6442]
Somewhat often on El Capitan vagrant will freeze all of its SSH connections, such that in terminal nothing can be typed. After 5-10 minutes it unfreezes itself and everything that has been typed in since it froze gets put in at once.

This is obviously frustrating, and did not happen at all before upgrading to El Capitan.

Our vagrant machine is Ubtuntu 14.04, and has not changed since upgrading (no box update).

It has plenty of memory and CPU availability, and doesn't appear to be topping out. I have it setup with 4 GB of RAM, and it happens sporadically, and htop reports it as being around 1/3 full memory some of the time when it freezes so it isn't overuse of memory.

Annoyingly, since everything freezes, htop does not continue updating so i cannot see if something does cause huge memory usage temporarily.

Trying to SSH into the machine, or HALT and UP the machine again still continues to be broken, so as far as I can tell, it isn't an issue with the actual box itself, since otherwise halt would fix it, since it restarts the box.

Halt itself seems to work, but on up again it encounters the freezing again.

Running with --debug says it gets to the SSH connection stage and then just freezes. So perhaps it could be to do with KeepAlive or something to do with the connection being reestablished.

Is there anything i can do to debug this for you?

**Comment by chriseckman** [comment]
I'm having the same issue.

**Comment by sosensible** [comment]
I found this article, have not tried it yet.
https://caspar.green/update-el-capitan-breaks-vagrant/

**Comment by sethvargo** [comment]
Hi @shopblocks 

Thank you for opening an issue. What version of Vagrant and Virtualbox are you running? There were known issues with Virtualbox on el capitan that have been fixed in recent releases. Could you please make sure you are running the latest Vagrant and virtualbox?

Could you please share your complete `Vagrantfile` as well as the output of the vagrant command in [debug mode](https://docs.vagrantup.com/v2/other/debugging.html)?

**Comment by unabl4** [comment]
I have the same issue after updating from Mavericks to Yosemite and then to El Capitan. 
"vagrant halt" sometimes helps, sometimes not.
 
Attempting graceful shutdown of VM...
Guest communication could not be established! This is usually because
SSH is not running, the authentication information was changed,
or some other networking issue. Vagrant will force halt, if
capable.
Forcing shutdown of VM...

So, something might be wrong with SSH communication.

And sometimes even --force does not help. It remains locked, and the only way to turn it off is to go to VirtualBox itself it shut it down there.
Updated to 5.0.8 (latest version to date) - no avail, still the same issue.

**Comment by mitchellh** [comment]
Closing due to lack of response. Sorry! Please reopen a new issue if you have a response to the above.
