### ISSUE TITLE
Same/Wrong IP assigned to VBox host-only adapters - Win10

### ISSUE THREAD

**Issue by kenpb** [mitchellh/vagrant#6461]
### Software/OS
- Windows 10 Pro
- Vagrant 1.7.4
- VirtualBox 5.0.8 r103449
### Background

Every time I start a machine or force provision with vagrant up, my current host-only adapter gets a wrong IP assigned, for example if my private network IP is assigned to 192.168.50.15/24 it becomes 192.168.50.1/24 in the adapter itself also 192.168.60.45/24 turns into 192.168.60.4/24 as you can see the adapter gets only the first number of the last octet of the IP I'm trying to assign.

Also subsequent machines will get the same adapter assigned with no changes in their IP whatsoever, let's say I create a new machine with 192.168.60.19/24 as private network... it'll take the old machine 192.168.60.1 for itself.

[Here's](https://gist.github.com/kenpb/b5371ead7eb16a0f6093) an example of the type of vagrantfile that I've been using (the box is windows server 2012 r2 created with packer x64 - 0.8.6 same host) and [Here](https://gist.github.com/kenpb/1c8538ef4abab23f33ea) the debug output of vagrant up command in that file.

I've tried deleting adapters, changing the version of VirtualBox/Vagrant/Windows, changing the IP's of the machines manually and still get the same results.

Thanks.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
