### ISSUE TITLE
Can't remove virtualbox machines from vagrant when virtualbox is uninstalled

### ISSUE THREAD

**Issue by mstahl** [mitchellh/vagrant#6498]
I upgraded my setup here from Virtualbox to VMWare Fusion and have had no end of trouble since, because the last vestiges of my virtualbox setup have proven impossible to remove now.

```
$ vagrant box remove codekitchen/boot2docker
The provider 'virtualbox' that was requested to back the machine
'dinghy' is reporting that it isn't usable on this system. The
reason is shown below:

Vagrant could not detect VirtualBox! Make sure VirtualBox is properly installed.
Vagrant uses the `VBoxManage` binary that ships with VirtualBox, and requires
this to be available on the PATH. If VirtualBox is installed, please find the
`VBoxManage` binary and add it to the PATH environmental variable.
```

I don't want to reinstall virtualbox because then I'd basically be back to square one with removing virtualbox from my system. Is there somewhere where Vagrant is caching these machine lists or where these machines are where I can manually delete them? Not even reinstalling Vagrant gets rid of them.

**Comment by mitchellh** [comment]
This error happens if there is an "active" VM that Vagrant believes still exists. You can fix this by removing your `.vagrant` directory from the working dir (with the Vagrantfile).

**NOTE:** You should only do this if you have no VMs left. It will disassociate Vagrant from any VMs, or in the case of Vmware actually delete the VM itself. 

Vagrant checks ifa  VM exists when it comes up, but if it has an ID and doesn't detect VirtualBox, then it can't check if the VM exists. You might say we can safely assume it _doesnt_ but due to the way that providers work right now this sort of logic would require a large refactor undertaking. Its easier to just delete your folder. :)
