### ISSUE TITLE
reload of docker provider does not assign ports

### ISSUE THREAD

**Issue by modius** [mitchellh/vagrant#6503]
Once a container is built and started it is impossible to change the port assignment without destroying the container and restarting (vagrant 1.7.4).

I assumed that `vagrant reload mydocker` would reassign the ports nominated.  

Is this inability to change the published ports the expected behaviour?

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
