### ISSUE TITLE
file provision to support urls, documentation

### ISSUE THREAD

**Issue by glensc** [mitchellh/vagrant#6531]
would be awesome if [file provisioner](https://docs.vagrantup.com/v2/provisioning/file.html) supported urls as input.

so some trivially simple file setups can be done with just one line:

```ruby
    # install poldek-config tool
    config.vm.provision "file", source: "https://raw.githubusercontent.com/pld-linux/poldek/master/poldek-config.sh", destination: "/usr/bin/poldek-config"
```

but that just gives error for now:
```
+ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

File provisioner:
* File upload source file /home/glen/vagrant/ffmpeg/https:/raw.githubusercontent.com/pld-linux/poldek/master/poldek-config.sh must exist
```

ps: that file provisioner should have attributes like `:owner`, `:group`, `:permissions` as well. if they exist, they are not [documented](https://docs.vagrantup.com/v2/provisioning/file.html)

**Comment by glensc** [comment]
also, seems the file provisioner runs as vagrant user, not as root, this is *not documented at all*, and rather unexpected:

```ruby
    config.vm.provision 'file', source: 'poldek-config.sh', destination: '/usr/bin/poldek-config'
```

```
$ vagrant provision
==> default: Configuring cache buckets...
==> default: Running provisioner: file...
Failed to upload a file to the guest VM via SCP due to a permissions
error. This is normally because the SSH user doesn't have permission
to write to the destination location. Alternately, the user running
Vagrant on the host machine may not have permission to read the file.

Source: /home/glen/vagrant/ffmpeg/poldek-config.sh
Dest: /usr/bin/poldek-config
```

**Comment by sethvargo** [comment]
Hi @glensc 

Thank you for opening an issue. I thought about this on the plane this morning, and I think this is something that Vagrant should not support. There are a number of concerns I have with specifying a URL to a script:

- How will you verify it has the right contents? We could add some kind of checksum verification, but downloading arbitrary things from the internet and running them is usually discouraged
- This adds unnecessary work on each of the VMs. If you download the script/file ahead of time, it can quickly be shared via shared folders. If you rely on the VM to download this file, it will be downloaded for each machine in the Vagrantfile.
- How do you handle updates? Should Vagrant always download the script? What if provisioning already ran?

The problem is - there's no _right_ answer to this question. If you want this level of granularity, I would suggest just using a standard shell provisioner:

```ruby
config.vm.provision "shell", inline: <<-SCRIPT
  curl -o /usr/bin/poldek-config https://raw.githubusercontent.com/pld-linux/poldek/master/poldek-config.sh
  /bin/bash /usr/bin/poldek-config
SCRIPT
```

This is much clearer in my opinion, and there is far less magic for a user to try and interpret. You have full control over the file permissions, who the script runs as, and more.

The file provisioner uses SCP, which doesn't have a sudo mode exactly, since it connects via the SSH user. We recommend you just use the file provisioner to copy to a temp folder, then the shell provisioner to copy.

I have created #6533 to capture that documentation fix for the next release.

**Comment by glensc** [comment]
okay, i'll just do the fetching in Vagrantfile, and use shell provisoner to install from /vagrant via shared folders (doing that anyway now).

but what about `:owner`, `:group`, `:permissions` attributes? if it doesn't support switching user, the permissions could be useful, or it will just preserve whatever original file had including timestamps?

**Comment by mitchellh** [comment]
Agreed with @sethvargo that we don't want to make the file provisioner that smart. Please use a shell script for this. I've updated the docs (will be deployed with Vagrant 1.8) to note that the file upload happens as an unprivileged user!

**Comment by mitchellh** [comment]
Sorry, closed soon, but the other point I wanted to say:

While `owner`, `group`, etc. would be useful, we prefer users to upload files as-is and then use the shell provisioner to set  permissions as needed. This is ultimately flexible and way easier to maintain for us than more custom settings.

**Comment by glensc** [comment]
thanks anyway you guys for prompt response!
