### ISSUE TITLE
Vagrant Ubuntu server loses connectivity after host Ubuntu goes to sleep

### ISSUE THREAD

**Issue by chrisvel** [mitchellh/vagrant#6605]
The issue is self explanatory:

In Ubuntu 15.10 Desktop as a host, Ubuntu server 14.04LTS loses connectivity after host goes to sleep mode and repairs only after reload.

I've tried:

sudo /etc/init.d/networking restart
sudo ifdown eth0 && sudo ifup eth0

none of these work.

How can I keep the connection working after sleep ?

**Comment by sethvargo** [comment]
Hi @chrisvel 

Thank you for opening an issue, and I am sorry you are having issues with Vagrant. I think this is a bug with the underlying provider. Are you using Virtualbox? Once Vagrant boots the machine, it is no longer running, so if the host loses connection on sleep/idle, it is likely a bug in Virtualbox. Does that make sense?

**Comment by chrisvel** [comment]
Yes it's virtualbox. I thought that the Vagrant community might help as it's a very common issue and I didn't find any solution yet.

**Comment by sethvargo** [comment]
Hi @chrisvel 

There were a number of issues in the initial release of VirtualBox 5 that have since been patched, specifically with newer guests. I would recommend upgrading to the latest version and see if the issue persists.

If the problem persists, please open an issue with VirtualBox. You might also try posting to the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). Thanks! :smile:
