### ISSUE TITLE
provision with salt, install_type and install_args not being honored?

### ISSUE THREAD

**Issue by vpereira** [mitchellh/vagrant#6609]
Hi,

I'm running vagrant version 1.7.4. I'm trying to do provision with salt and I have the following code block being called:

```
config.vm.provision :salt do |salt|
       salt.minion_config = "saltstack/etc/minion"
       salt.run_highstate = true
       salt.install_type = :git
       salt.install_args = "develop"
       salt.verbose = true
  end
```

So it should be using git and trying to fetch the branch "develop" 

However looking the downloader: at `/tmp/bootstrap_salt.sh` it looks like:

```
# We just download the bootstrap script by default and execute that.
if [ -x /usr/bin/fetch ]; then
    /usr/bin/fetch -o - https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh | sh -s -- "$@"
elif [ -x /usr/bin/curl ]; then
    /usr/bin/curl -L https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh | sh -s -- "$@"
else
    python \
        -c 'import urllib; print urllib.urlopen("https://raw.githubusercontent.com/saltstack/salt-bootstrap/stable/bootstrap-salt.sh").read()' \
        | sh -s -- "$@"
fi
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
