### ISSUE TITLE
The ansible_local "install capability" should better support RedHat family

### ISSUE THREAD

**Issue by gildegoma** [mitchellh/vagrant#6636]
As of Fedora 22, `yum` has been deprecated in favor of `dnf`. With this new package manager, the EPEL repo is no longer needed to install ansible.

**Comment by sethvargo** [comment]
@gildegoma I think we do some `which yum` in one of the other plugins (puppet/chef?) - you could copy that pattern.

**Comment by gildegoma** [comment]
@sethvargo yup, I saw this and will cherry-pick from there. Thanks ;-)

**Comment by rickard-von-essen** [comment]
I'm confused by [this code](https://github.com/mitchellh/vagrant/blob/master/plugins/provisioners/ansible/cap/guest/epel/ansible_install.rb), EPEL should never install on (any) Fedora? It has noting to do with dnf vs. yum. 

See https://github.com/mitchellh/vagrant/issues/6286#issuecomment-154789624 for a example of trying to install EPEL on Fedora.

I made similar fixes for many of the other plugins see #6288, but I must have missed this.

The logic should be:
- if ```guest == redhat && guest != fedora``` install EPEL. (Fedora extends RedHat)
- if ```dnf``` is available use it otherwise use ```yum``` to install ansible.

**Comment by gildegoma** [comment]
@rickard-von-essen you're [totally right](http://docs.ansible.com/ansible/intro_installation.html#latest-release-via-yum). You haven't missed it, it has been merged into master quite recently, see #6500.

Please tell us if you're interested to fix it. That would be very cool to have it ready for 1.8 ;)

**Comment by rickard-von-essen** [comment]
I can take a stab on it.. back soon.
