### ISSUE TITLE
vagrant ssh not working via cygwin

### ISSUE THREAD

**Issue by oliver-dungey** [mitchellh/vagrant#6663]
I have been trying to move over to Cygwin on Windows for Vagrant but it has been stubbornly refusing to bend to my will. I got my TTY related issues fixed thanks to various other threads but I had a persistent problem in that 'vagrant ssh' would always hang via Cygwin. I have now found that this is due to a clash of software - I have Cygwin, Vagrant and GitHub installed on Windows 7. GitHub comes with an ssh client that ends up on the path, it works fine for Vagrant via the DOS CMD prompt but in Cygwin it just hangs forever. After much mucking around I have found that installing the **openssh** package in Cygwin (it's a server and client in a single package) puts it's own ssh client on the path which works perfectly with Vagrant - just make sure that it's the first ssh on the path i.e. run this from the Cygwin shell

`which ssh`

should return `/usr/bin/ssh`.

**Comment by TomyLobo** [comment]
that's more of a cygwin/github compatibility issue...
It might be possible to solve this by bundling an SSH client with vagrant, though.

**Comment by AlbertZheng** [comment]
I encountered this issue too and I already got the root cause and resolved it.

Root cause: If the Cygwin tty is launched from the program icon pinned to the taskbar of Windows 7 desktop (i.e. you used "Pin this program to taskbar" to pin the Cygwin tty shortcut to the taskbar), "vargrant ssh" would fail to deal with the output of ssh command run in the pinned Cygwin tty. 

Solution: You should always use the Cygwin tty shortcut (the shortcut target command is "yourPathToCygwinInstallation\cygwin\bin\mintty.exe -i /Cygwin-Terminal.ico -" ) created on the desktop by the installer.

**Comment by TomyLobo** [comment]
I still think bundling an ssh client with vagrant would be a good idea.
Maybe with the option of specifying an override in your Vagrantfile.
config.ssh.path or something.

**Comment by chrisroberts** [comment]
Looks like a proper fix is described here: https://github.com/mitchellh/vagrant/issues/6663#issuecomment-235459323

Cheers!

**Comment by TomyLobo** [comment]
Thinking about the issue some more...
MSYS-based and Cygwin-based programs don't interoperate too well, so which version would you bundle anyway?
If you bundled an msys ssh, it would freeze up on cygwin.
If you bundled cygwin git, it would work (I just tested it), but you'd probably have a ton of dependencies.

Since both work fine on Windows' standard prompt, I'd wager a guess that Cygwin is at fault here.
Maybe it misdetects the msys executable as a cygwin executable and waits for some kind of response that never happens.

Just in case you want to report this upstream.

Btw, if I open a Cygwin Terminal and then use right-click -> pin on the Cygwin Terminal, that creates 
"%APPDATA%\Microsoft\Internet Explorer\Quick Launch\User Pinned\TaskBar\Cygwin64 Terminal.lnk", with the same properties as the regular start menu link:
* target: `C:\cygwin64\bin\mintty.exe -i /Cygwin-Terminal.ico -`
* working directory: _<empty>_

I can reproduce the issue if I open C:\cygwin64\bin in windows explorer and double-click bash.exe.
Pinning the resulting terminal to the task bar creates a broken task bar link, of course.

And that is, again, Cygwin's fault.
