### ISSUE TITLE
Corruption of vagrant data file

### ISSUE THREAD

**Issue by KokareIITP** [mitchellh/vagrant#6680]
The message after typing vagrant up command is:
The machine index which stores all required information about
running Vagrant environments has become corrupt. This is usually
caused by external tampering of the Vagrant data folder.

Vagrant cannot manage any Vagrant environments if the index is
corrupt. Please attempt to manually correct it. If you are unable
to manually correct it, then remove the data file at the path below.
This will leave all existing Vagrant environments "orphaned" and
they'll have to be destroyed manually.

Path: C:/Users/admin/.vagrant.d/data/machine-index/index

I solved it with help of http://stackoverflow.com/questions/24911021/vagrant-corrupted-index-file-c-users-username-vagrant-d-data-machine-index-ind

But please could anyone help me regarding why this error occurred ?

**Comment by mitchellh** [comment]
The error message happens if we can no longer parse the index as JSON. As the message says, the only thing we can think of is that there was external tampering somehow. In theory I suppose there could also be disk corruption or even Vagrant itself somehow writing bad JSON. If we can find a repro case we'd be happy to take a closer look.

**Comment by KokareIITP** [comment]
Thanks !
