### ISSUE TITLE
SSH Agent forwarding not working for Mac and Linux

### ISSUE THREAD

**Issue by marcofranssen** [mitchellh/vagrant#6687]
Hi, I seen a few closed tickets regarding SSH Agent forwarding which was not working.

Now I'm kind of in the situation where Agent forwarding does work except for the shell provisioning on Linux and Mac. So on Windows it works flawlessly. On Linux it only works afterwards when you do vagrant ssh.

As our shell provisioners do need to clone some git repos we require the ssh agent forwarding to be working.

It is a debian wheezy box build from our existing virtualbox image. As you can see we use the root user to login.

``` Ruby
Vagrant.configure("2") do |config|
  config.ssh.username = "root"
  config.ssh.forward_agent = true

  config.vm.provider :virtualbox do |vb|
    vb.name = box_name
    # vb.gui = true
  end

  config.vm.provision "shell", path: "init.sh"
end
```

Would be great if someone has some ideas on how to tackle this. Either as workarround, or a potential fix for vagrant.

We do have the ssh key loaded in the ssh-agent. So when on linux following command will show that the key is loaded.

`ssh-add -l`

When doing `vagrant ssh` after provisioning it also proves it is there as we then can just clone fine.

On Windows the key is available in putty agent.

**Comment by marcofranssen** [comment]
Forgot to mention we also tried using keychain to load the key....

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
