### ISSUE TITLE
Vagrant rsync-auto with a windows or linux host isn't receiving notification of deleted folders

### ISSUE THREAD

**Issue by nuncanada** [mitchellh/vagrant#6819]
From the output, the callback code to rsync isn't even being called when a folder is deleted.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
