### ISSUE TITLE
ssh -c output is polluted with CR chars

### ISSUE THREAD

**Issue by ntki** [mitchellh/vagrant#6827]
Version: only tried 1.7.4 and 1.8.1.

I was trying to pipe out binary from a linux vm with ssh on a linux host. With option `-c` it seems to prepend every `\n` with an `\r`. Fortunately it is not the case with `--`.

```
$ vagrant ssh -- "echo test" | xxd
0000000: 7465 7374 0a                             test.

$ vagrant ssh -c "echo test" | xxd
Connection to 127.0.0.1 closed.
0000000: 7465 7374 0d0a                           test..
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!

**Comment by ntki** [comment]
Hi

Just tried it with 1.9.0 and 1.9.1. The issue is still standing.

Cheers
