### ISSUE TITLE
Docker provider: --no-parallel should be the default if there are container links

### ISSUE THREAD

**Issue by cweagans** [mitchellh/vagrant#6831]
Longer term, dependency resolution would be kind of amazing (opened as a separate issue: https://github.com/mitchellh/vagrant/issues/6830), but as a short term fix, if the link method is being used in any docker provider in the entire Vagrantfile, `--no-provider` should be the default so that we can guarantee that the containers will come up properly.

In this scenario, the user is still responsible for ordering their machines such that the dependencies come up first, but that's not much different from what we have now.

**Comment by sethvargo** [comment]
Hi @cweagans 

Thank you for opening an issue. While this definitely isn't the nicest experience, we have documented the need to use `--no-parallel` with the Docker provider. We are going to focus efforts on larger tickets like 6830 on the core team, since that's ultimately a much better solution. We would gladly review a pull request for this functionality, but since it will become unnecessary once 6830 is solved, I do not think the core team will be implementing it. Thanks! :smile:
