### ISSUE TITLE
Call to undefined method 'split' in provider plugin "vmware_workstation"

### ISSUE THREAD

**Issue by nilmerg** [mitchellh/vagrant#6859]
When running "vagrant up" with the latest version of the vmware workstation provider (4.0.6) an exception is raised while configuring the network adapter of the virtual machine. Version 4.0.5 showed the same error.

https://gist.github.com/nilmerg/2c562a8ca65a8a42a497

The box in use is "puppetlabs/centos-6.6-64-nocm" but the error occurred with box "bento/centos-7.1" as well.

The Vagrantfile contains the following to configure the vmware_worktation provider:

```
config.vm.provider "vmware_workstation" do |v|
    v.vmx["memsize"] = "1024"
    v.vmx["numvcpus"] = "1"

    # Required because NAT is bugged in VMware Workstation v12.1
    v.vmx["ethernet0.connectiontype"] = "bridged"
end
```

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
