### ISSUE TITLE
Expose VAGRANT_VAGRANTFILE an option

### ISSUE THREAD

**Issue by jaimegago** [mitchellh/vagrant#6881]
The very useful VAGRANT_VAGRANTFILE environment variable allows to specify a vagrant file, why not make that a option to the vagrant CLI?

**Comment by sethvargo** [comment]
Hi @jaimegago 

Thank you for opening an issue. The reason this cannot be part of the CLI is because Vagrantfile's are recursively evaluated and can alter the behavior of the CLI (such as unloading or loading plugins). As such, you must specify the Vagrantfile _first_ so it can be loaded before the vagrant process.

**Comment by jaimegago** [comment]
@sethvargo I understand, would you be willing to accept a PR to at least document this ? Unless I'm mistaken it's only documented via a code comment.

**Comment by sethvargo** [comment]
https://docs.vagrantup.com/v2/other/environmental-variables.html

**Comment by jaimegago** [comment]
ah completely missed it thanks!
