### ISSUE TITLE
Vagrant ssh "-c" kills upstart process

### ISSUE THREAD

**Issue by byrnedo** [mitchellh/vagrant#6888]
I've noticed that running the ssh command using '-c' flag kills an upstart process once the session is terminated.

    ❯❯❯vagrant ssh swarm-1 -c "sudo service rexray start; sleep 3; sudo service rexray status;"
    Starting REX-Ray...SUCCESS!

      The REX-Ray daemon is now running at PID 2235. To
      shutdown the daemon execute the following command:

        sudo /usr/bin/rexray stop

    REX-Ray is running at pid 2235
    Connection to 127.0.0.1 closed.
    
    # check if it's running
    ❯❯❯vagrant ssh swarm-1 -c "sudo service rexray status;"
    REX-Ray is stopped
    Connection to 127.0.0.1 closed.
    
 If however I run it using '--' instead it works!

    ❯❯❯vagrant ssh swarm-1 -- "sudo service rexray start; sleep 3; sudo service rexray status;"
    Starting REX-Ray...SUCCESS!

      The REX-Ray daemon is now running at PID 2235. To
      shutdown the daemon execute the following command:

        sudo /usr/bin/rexray stop

    REX-Ray is running at pid 2235
    Connection to 127.0.0.1 closed.

    ❯❯❯vagrant ssh swarm-1 -c "sudo service rexray status;"
    REX-Ray is running at pid 2235
    Connection to 127.0.0.1 closed.

Is this expected behavior or why does this happen?

I'm on version 1.8.1. Vm was Ubuntu 14.04.

**Comment by sethvargo** [comment]
Hi @byrnedo 

Thank you for opening an issue. This is the expected behavior. You are spawning a subprocess without a TTY or login that is a subprocess of the command. Thus the upstart process is terminated when the parent dies (the SSH session).

In the second example with `--`, you are logging in and performing a session allocation, so the parent process is actually the OS, which maintains state after the SSH session terminates.

This is behaving as expected.

**Comment by byrnedo** [comment]
Thanks for the explanation @sethvargo
