### ISSUE TITLE
vagrant up "vmrun error" : laravel homestead

### ISSUE THREAD

**Issue by odyright** [mitchellh/vagrant#6921]
hello i'm using mac os El Capitan and tried to install laravel homestead  but i get this error:

```
iMac-de-ODYLIGHT:Homestead odylight$ vagrant up
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Checking if box 'laravel/homestead' is up to date...
==> default: Skipping vmnet device verification, verify_vmnet is set to false.
==> default: Preparing network adapters...
==> default: Starting the VMware VM...
An error occurred while executing `vmrun`, a utility for controlling
VMware machines. The command and output are below:

Command: ["start", "/Users/odylight/Project/Homestead/.vagrant/machines/default/vmware_fusion/ef8f82b4-e1e5-4d58-92d2-7fdb1a7732c1/ubuntu-14.04-amd64.vmx", "nogui", {:notify=>[:stdout, :stderr], :timeout=>45}]

Stdout: 2016-01-24T17:22:52.108| ServiceImpl_Opener: PID 3842
Error: The operation was canceled

Stderr: 
iMac-de-ODYLIGHT:Homestead odylight$ vagrant box list
laravel/homestead (vmware_desktop, 0.4.0)
iMac-de-ODYLIGHT:Homestead odylight$ 
```
i have vmware fusion 8 and a licence of vagrant plugin for fusion

CONFIG:
  Nom du modèle :	iMac
  Identifiant du modèle :	iMac14,2
  Nom du processeur :	Intel Core i7
  Vitesse du processeur :	4,00 GHz
  Nombre de processeurs :	1
  Nombre total de cœurs :	4
  Cache de niveau 2 (par cœur) :	256 Ko
  Cache de niveau 3 :	8 Mo
  Mémoire :	14 Go

**Comment by sethvargo** [comment]
Hi @odyright 

Thank you for opening an issue. Unfortunately that error is coming directly from VMware, not Vagrant. Double unfortunately, that error is a very generic error returned by VMware that could mean a few different things.

First, please make sure you update to the latest version of the VMware software and the vagrant-vmware-fusion plugin. It can mean a variety of things, I've found out, none of which Vagrant can really detect or do anything about, especially because the error is so vague:

* Virtualization extensions aren't enabled on the CPU
* Your trial has expired or the application requires a license key
* Permission problems on the install (corrupted install)
* You need to fill out some form data in the GUI.

The best way to determine what is going on is to enable the GUI from the Vagrantfile so Vagrant doesn't launch it headless. This _usually_ results in Fusion properly showing an error message.
