### ISSUE TITLE
re-open issue #5319

### ISSUE THREAD

**Issue by milhaus** [mitchellh/vagrant#6966]
Looks like a regression? It was closed a year ago but it doesn't say why and I'm experiencing this issue.

**Comment by sethvargo** [comment]
Hi @milhaus 

There are a number of issues that reference slow box downloads. Some boxes are externally hosted and Atlas just acts as a "pointer", and some boxes are hosted directly on Atlas, and our team is always working to improve the box delivery system. If you have a specific box that is consistently slow, please email support@hashicorp.com and we can take a look. Sometimes the upstream network providers limit box traffic because of bandwidth and there's not much we can do in those cases. This is not a Vagrant issue. Thanks! :smile:
