### ISSUE TITLE
Chef Zero provisioner should not require `nodes_path`

### ISSUE THREAD

**Issue by phs** [mitchellh/vagrant#6972]
#6559 made the `nodes_path` configuration required for chef zero provisioning, but I question how much sense that makes.

My use case for vagrant is to create a portable development environment; I don't have (or want) the chef toolchain installed on the host OS.  As such I'm not very interested in the node json files that the chef zero provisioner generates.  Providing a host OS location to contain them is a mild annoyance.

Since I don't have a `~/.chef/nodes` (or similar) to stash the node json files, it seems my best bet is to make `./nodes` my `nodes_path`.  However if I do that then I see a proliferation: the vagrant instance global id hash appears in the node id (and so node json file name.)  Now I need a `./nodes/*.json` in my `.gitignore` just to gracefully cope with a pile of files I didn't want in the first place.  Further, it seems there is no process for removing them; it's on me to periodically clean them out.

Prior to the mentioned PR, if `nodes_path` was omitted, then the chef zero nodes directory was kept only within the guest.  [Assuming the required directory is actually created within the guest](https://github.com/mitchellh/vagrant/issues/6110), I think this is a lovely default behavior.

Could we have (a fixed version of) the old default behavior back?

**Comment by sethvargo** [comment]
Chef Zero will not run without a nodes path. I know we have discussed your use case in the past, but please understand that you're use case is not the same as everyone else's. You can read more about why the nodes_path is required in the issue: https://github.com/mitchellh/vagrant/issues/6110. You actually commented on that issue and suggested the behavior, so I'm a bit confused.

**Comment by phs** [comment]
If you [recall](https://github.com/mitchellh/vagrant/issues/6110#issuecomment-152646177), I suggested creating the missing directory within the guest, which is what my one-liner workaround accomplished:

```
config.vm.provision :shell, inline: 'mkdir -p /tmp/vagrant-chef/cookbooks/nodes'
```

Notice there's nothing about a shared folder or host-side storage there.

Even if I'm off the beaten path, the fact that the one-line fix was viable suggests that it wouldn't be very hard to productionalize.  If you prefer I'm happy to put together a PR, whose net effect would be to revert df207d2 and then ensure that in the default case the needed `nodes` directory was created, somewhere around [here](https://github.com/mitchellh/vagrant/blob/d75ba63366d0f0d165236a1ef1e3ac555570fd09/plugins/provisioners/chef/provisioner/chef_zero.rb#L37).

**Comment by sethvargo** [comment]
@phs I really don't think it's unreasonable to require a `nodes_path` for working with the Chef Zero provisioner, since the node is just as critical of a component as the recipes, which are also required.

**Comment by phs** [comment]
Maybe I'm not understanding something about how chef zero operates then.

My impression is the files kept in the nodes path(s) are an implementation detail of chef zero, allowing it to record attributes that should endure between chef runs.  Unlike the cookbook, data bag or environment directories, there isn't an occasion where the user is expected to craft a nodes file and drop it into `nodes_path`(? or is there?)

Even if there was a use case for that, it's not clear what the user-authored file should be named, or how one would tell the provisioner to pick it up.  Am I missing something fundamental to how chef zero is meant to work?

**Comment by sethvargo** [comment]
@phs Chef Zero will not run properly without at least one node. `nodes_path` specifies the list of nodes that should be returned via a Chef Search, which should always include the current node. In the past, this might have worked if you were running `chef-solo -z`, but that has been deprecated in favor of `chef-client -z` which requires the nodes_path to be set and populated.

**Comment by phs** [comment]
That makes sense, but I don't think it answers the question.  Both now and prior to the mentioned PR, it appears the provisioner would synthesize a reasonable default node definition; action from the user was never required.

Anyway, I noticed the [chef solo provisioner](https://www.vagrantup.com/docs/provisioning/chef_solo.html) does not require the `nodes_path` declaration (though it supports it.)  My particular case doesn't need advanced server features (like search) so it looks like that's good enough for me.  Feel free to close.

**Comment by mattdeboard** [comment]
@sethvargo Please explain then how we have been using the chef-zero provisioner on Vagrant 1.7.4 just fine without setting `nodes_path` anywhere?

**Comment by mattdeboard** [comment]
@sethvargo This would be a little less frustrating if you provided a more detailed answer than a copy-and-paste response with a smiley face at the end to a backward-incompatible & breaking change between 1.7.4 and 1.8.x

**Comment by sethvargo** [comment]
Hi @mattdeboard 

Thank you for your inquiry. In short, _you haven't_ been using the chef-zero provisioner in Vagrant 1.7. You've been using chef-solo in zero mode, not chef-client in zero mode. That is really not the desired behavior (there are lots of reported issues). If you're using 1.7 in zero mode, you can use 1.8 in solo mode just fine, because you weren't using zero mode (it was a bug in the first place).

**Comment by mattdeboard** [comment]
@sethvargo This makes an even stronger case that this should have been documented as a breaking change, so that helpful information like that is out there for people to see.

**Comment by sethvargo** [comment]
Hi @mattdeboard 

Thank you for your reply. As I said in my other response (which includes more technical detail), we didn't view it as a break change at the time because the vocal users were reporting it as a bug. We didn't anticipate that users were depending on the bug behavior. This issue is documented in the Vagrant 1.8 changelog, but you're right that we could do a better job of calling out these types of changes in the future. Again, I'm very sorry this caused you pain.

**Comment by cburyta** [comment]
This may be a separate issue (I'm looking for other issues that overlap) but if chef_zero was able to create / delete the nodes_path that would be awesome. My issue is that running vagrant provision writes out to the nodes_path json files, and future 'vagrant up' runs will re-use that json data - even _AFTER_ a vagrant destroy / up.

This is incredibly confusing, and makes it so that using chef_zero requires manual 'rm nodes_path/*.json' calls between vagrant calls. (While it looks like chef.json is used, it's not really because the data from the past vagrant builds is merged into it.)

For this reason, I'd +1 a change to allow chef_zero nodes_path to be created in the Guest somehow.

**Comment by crazy54** [comment]
I am running into this as well, and I do not see why we are required to specify the node data when we are running this against the vagrant machine in the directory.  How come the node data cannot be automatically generated on the chef-zero run?

Here is my configuration:

Vagrantfile:
```
config.vm.provision :chef_zero do |chef|
    chef.roles_path = "chef/roles"
    chef.nodes_path = "chef/nodes"
    chef.add_role("web")
    chef.cookbooks_path = "chef/cookbooks"
 end
```

**Comment by espoelstra** [comment]
Because I ran into this recently I used the suggestion above in a somewhat hacky solution, you could put it in a global Vagrantfile or just one at the root of your "projects" directory to allow inheritance. This could allow using with the older versions with some minor modifications to compare the Vagrant version.

```
    chef.nodes_path = 'nodes' # You can comment this if you are using an older version of Vagrant or you could test for a specific version of Vagrant and leave it unset for the older ones.
    if ! chef.nodes_path.nil?
	# if we need a fresh 'nodes' for each provision `rm -rf` first
	config.vm.provision :shell, inline: "mkdir -p /tmp/vagrant-chef/cookbooks/#{chef.nodes_path}"
    end

```
