### ISSUE TITLE
Vagrant up and provision does not behave the same way

### ISSUE THREAD

**Issue by alktlr** [mitchellh/vagrant#6974]
If I run `vagrant up node1 --provision-with setup-cluster` I get the following error:

```
'setup-cluster' is not a known provisioner. Please specify a valid
provisioner.
```

If I run `vagrant provision node1 --provision-with setup-cluster` it works just fine.

Vagrantfile have the following lines:

```ruby
if ARGV[0] == "provision" && ARGV.join(" ")["setup-cluster"]
  main_config.vm.provision "setup-cluster", type: "ansible" do |ansible|
    ansible.playbook = "playbooks/setup-cluster.yml"
  end
end
```

The reason for the if statement is because the node1 can also be configured as a standalone node by just running `vagrant up node1`.

Alternative solution. There is a run: parameter to vm.provision. If option "never" could be implemented, like in do not provision this unless used with --provision-with, I could strip the if statement.

**Comment by sethvargo** [comment]
Hi @alktlr 

The error you are getting makes sense because the provisioner is not defined if the command is `up`. The provisioner is only defined if the command is `provision` - that's the first line of your conditional.

This is not how provisioners are designed to function. If you want to bring up different types of nodes, you should use multi-machine Vagrantfiles: https://www.vagrantup.com/docs/multi-machine/. You can specify top-level provisioners or machine-level provisioners.
