### ISSUE TITLE
"vagrant ssh" fails with misleading error message after moving a VM

### ISSUE THREAD

**Issue by magnusr** [mitchellh/vagrant#6998]
After moving the directory where a VM was stored, running `vagrant ssh ${id}` gave the following error message:

     VM must be created before running this command. Run `vagrant up` first.

The error message is incorrect, as the VM was up and running. If it had stated that it did not find the directory where the VM used to be, it would have been a lot easier to figure out what had gone wrong (also, if `vagrant up` would have updated the index, the issue would never have happened)

**Comment by sethvargo** [comment]
Hi @magnusr 

This is the expected behavior. There is no way for Vagrant to know what operations were performed outside of it's commands. In Vagrant's eyes, it checked if the VM existed and it did not. The fact that you moved the VM is opaque to Vagrant. Unfortunately there's really no way to detect this. Sorry! :frowning:
