### ISSUE TITLE
Synced folder goes missing

### ISSUE THREAD

**Issue by back-2-95** [mitchellh/vagrant#7003]
I have synced folder like this:

``` ruby
config.vm.synced_folder ".", "/vagrant/sug", id: "default", :nfs => true, :mount_options => ['nolock,vers=3,udp']
```

And after a while, the mount goes like this:

```
?????????? ? ? ? ?            ? sug
```

Same thing happens with another vagrant machine.

I have OSX El Capitan, VMware Fusion Pro 8.1.0.

**Comment by Fynkymynky** [comment]
Hi back-2-95, I'm having similar issues

https://github.com/mitchellh/vagrant/issues/6985

If you look at other issues here other people are having the same issue.

I have to destroy images and build them again, stop and start, sometimes I get things to work. But I spend most of my days now getting vagrant to work rather than coding.

This is great software when it works, but at the moment too many people are having problems. I don't have any answers for you though :(

**Comment by sethvargo** [comment]
Hi @back-2-95 

Can you please share your complete Vagrantfile and the output of the command in [debug mode](https://www.vagrantup.com/docs/other/debugging.html)? Thanks!

**Comment by back-2-95** [comment]
Here is one of the Vagrantfiles of machines which are affected by this error.

```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.require_version ">= 1.8.1"

$vm_gui = false
$vm_memory = 4096
$vm_cpus = 2
# VM name
$vm_name = 'dev.sug.org'
# Choose random addr from 192.168.X.X
$vm_ip = '192.168.108.19'

# Use old vb_xxx config variables when set
def vm_gui
  $vb_gui.nil? ? $vm_gui : $vb_gui
end

def vm_memory
  $vb_memory.nil? ? $vm_memory : $vb_memory
end

def vm_cpus
  $vb_cpus.nil? ? $vm_cpus : $vb_cpus
end

Vagrant.configure(2) do |config|

  config.vm.box = "geerlingguy/centos7"
  config.vm.hostname = $vm_name

  ["vmware_fusion", "vmware_workstation"].each do |vmware|
    config.vm.provider vmware do |v|
      v.gui = vm_gui
      v.vmx['memsize'] = vm_memory
      v.vmx['numvcpus'] = vm_cpus
    end
  end

  config.vm.provider :virtualbox do |vb|
    vb.gui = vm_gui
    vb.memory = vm_memory
    vb.cpus = vm_cpus
  end

  # always use Vagrants insecure key
  config.ssh.insert_key = false

  config.vm.network :private_network, ip: $vm_ip

  config.vm.synced_folder ".", "/vagrant/sug", id: "default", :nfs => true, :mount_options => ['nolock,vers=3,udp']

  # Provision nodes with Ansible
  config.vm.provision "ansible" do |ansible|
    ansible.playbook = 'ansible/provision.yml'
    ansible.inventory_path = 'ansible/inventory/development'
    ansible.limit = 'all'
  end
end
```

**Comment by back-2-95** [comment]
and output from command vagrant up --debug &> debug_log

 https://gist.github.com/back-2-95/11e05c385ecea6864bd4

**Comment by back-2-95** [comment]
"vagrant reload" fixes the issue but it comes back. Probably when I'm idle or something.

I also made clean install of OSX which did not help.

**Comment by back-2-95** [comment]
And same thing happens with Vagrant 1.8.1 and 1.7.4

**Comment by back-2-95** [comment]
Also tested with another mac (clean install). Same result.

Tested with:
-MBP 15" Late 2013
-MBP 15" Mid 2015

Usual situations where it happens:
-during the night, lid closed
-during driving home, lid closed (1 hour)

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
