### ISSUE TITLE
bi-directional synced folder on a remote provider

### ISSUE THREAD

**Issue by shaharsol** [mitchellh/vagrant#7019]
I am trying to up a vagrant on a remote provider (aws, digital ocean, rackspace etc) with a bi-directional synced folder. That is, that changes on the remote machine `/vagrant` folder are reflected on the local machine. 

It works seamlessly with VirtualBox on my local machine both when using rsync and NFS but neither work on digital_ocean for example. 

The docs are confusing as well. On one hand the vagrant docs imply that this sort of thing should work out of the box, yet each provider plugin doc mentions a limited, sometimes uni-directional sync folder support. I am not sure if it is up to the plugin to determine the extent of sync folder functionality it supports or if it's just lays the ground for vagrant to take over. 

Any definitive answer (i.e. It __can__ be done / it __can't__ be done) would be appreciated

**Comment by sethvargo** [comment]
Hi @shaharsol 

These are issues that exist with those providers. Please open an issue on the vagrant-aws or vagrant-digitalocean plugins. It's most likely impossible, since you cannot mount a local volume on a cloud machine, but rsync might be possible. Those third-party providers will need to add that support though. Thanks! :smile:
