### ISSUE TITLE
virtualbox ignored even if it is in Vagrantfile

### ISSUE THREAD

**Issue by ijstokes** [mitchellh/vagrant#7020]
I have vmware fusion installed, but I rarely use it.  Despite having `virtualbox` specified in my `Vagrantfile` as so:

```
  config.vm.provider "virtualbox" do |v|
    v.name = "6-trialbox"
  end
```

The only way I can properly bring up a box with VirtualBox (my preferred hypervisor) is by doing:

```
vagrant up --provider virtualbox
```

That seems surprising and perhaps even broken to me.  My preferred behavior (what I would call "correct" behavior) is that a `Vagrantfile` that specifies `config.vm.provider "virtualbox"` would try to use VirtualBox as the hypervisor, and not require the CLI option `--provider virtualbox`.

**Comment by sethvargo** [comment]
See my answer there please

**Comment by ijstokes** [comment]
@sethvargo there are two separate issues here.  I added a comment to #7021.  For this issue the problem I have is that the `Vagrantfile` clearly specifies inside it that `virtualbox` should be used as the provider.  It doesn't make sense to me that I **also** have to include a command line option `--provider virtualbox`.

**Comment by sethvargo** [comment]
Hi @ijstokes 

Thank you for your reply. The Vagrantfile does not allow you to specify a default provider. There's an open issue for that. The Vagrantfile you supplied defines configuration for when the virtualbox provider is used.

**Comment by LongLiveCHIEF** [comment]
@sethvargo this is not how the documentation describes how vagrant selects the provider. Vagrant tries to "reason about the best provider to use", and when a resoning can't be made because the vagrantfile has multiple providers, or no providers specified, *then* it falls back to what it reasons to be the global default provider.

The documentation is pretty clear that if you have a `config.vm.provider` defined, and only one of them, then you should be able to `vagrant up` without specifying the `--provider` flag. 

I also added comments to #7021, to clarify another reason this is an issue... multi-vm Vagrantfiles.  The documentation is consistent with what those of us reporting this issue expect. And this is also the only reasonable way a multi-vm Vagrantfile could work.  If I were to run `vagrant up --provider` on a multi-VM Vagrantfile that had different providers specified between machines defined, then the `vagrant up` would *always* fail.

The multi-VM is a common occurence, and I've used it often in the past with multiple providers.  

No, you *can't* specifiy the *default* provider via a flag inside the *Vagrantfile*, but you can control the providers used by providing configurations for the provider you want to be used on *up*.

Please re-open this issue. It had nothing to do with the *default*, but an error with the documented and expected functionality of Vagrant.
