### ISSUE TITLE
Vagrantfile doesn't document conditional execution only when provisioning.

### ISSUE THREAD

**Issue by CodeGnome** [mitchellh/vagrant#7043]
I am attempting to *conditionally* run code inside a Vagrantfile based on whether or not Vagrant is expected to provision during the current operation. For example, I want to create conditional statements in my Vagrantfile so that certain tasks only run when doing:

- `vagrant up` for the first time, or
- when I execute `vagrant reload --provision`.

The [source] implies there ought to be a way to query Vagrant itself to determine if it's a provisioning run. Specifically, there ought to be a way to hook into `@env[:provision_enabled]` or `vagrant.actions.vm.provision`, but I'm unable to figure out how to do this from within the Vagrantfile itself.

Is this method actually bound to the Vagrant object? If not there, then where? And how can I introspect it?

[source]: https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/action/builtin/provision.rb

**Comment by sethvargo** [comment]
Hi @CodeGnome 

This is not currently possible because the Vagrantfile is parsed _before_ the environment is created. This information is available to provisioners and plugins, but not the Vagrantfile itself because of the load ordering. In other words, that `@env` doesn't exist until after all Vagrantfile's have been parsed, and unfortunately that's a hard requirement because information in the Vagrantfile determines the way that object is created. It's a catch-22 for your use case.

One possible alternative is to inspect ARGV in your Vagrantfile. Something like:

```ruby
if ARGV.include?("up") || (ARGV.include?("reload") && ARGV.include("--provision"))
...
end
```

Thanks! :smile:
