### ISSUE TITLE
non-standard file locations in Windows

### ISSUE THREAD

**Issue by rbos** [mitchellh/vagrant#7066]
I am deploying this Vagrant to staff machines and notice that it stores its files in "C:\HashiCorp". This is not in keeping with Windows filesystem conventions and should be considered a bug. Please store the files in a subfolder in "C:\Program Files" or "C:\Program Files(x86)" as needed.

You wouldn't put files in / on Linux, don't do it on Windows.

**Comment by rbos** [comment]
(Also it plays merry havoc with AppLocker rulesets)

**Comment by rbos** [comment]
Also, it is ignoring my INSTALLDIR="C:\Program Files\Vagrant" directive in the MSI.

**Comment by sethvargo** [comment]
Hi @rbos 

Thank you for opening an issue. Could you please point me to the reference material for Windows filesystem conventions? There are a number of software tools that live in `c:/` instead of program files, particularly if those programs require escalated privileges (Chef, Puppet, Vagrant, etc). Vagrant is unable to reside in `C:/Program Files` because that path contains a space, and the underlying programming language Vagrant is written is will refuse to operate on Windows if there are special characters in the pathname. Additionally, Ruby itself is another tool that gets installed into `C:\Ruby` and `C:\DevKit`.

**Comment by rbos** [comment]
I don't think there's anything like an official Microsoft diktat on the subject, if you're looking for that.

Other software breaking convention isn't necessarily a valid excuse, in my opinion. Ruby is also wrong. This is a frequent problem and I file tickets about it whenever I run into it. It won't change unless the concern is relayed to the relevant parties.

If your code can't handle spaces, then that could be a security concern with string handling. It's generally good practice to make sure you can handle them, and I find that the space in "Program Files" is a good metaphorical canary in that coal mine.

Regardless, I don't feel the need to convince you. I'm only reporting the violation of the common convention. If your response is "won'tfix" then so be it, my conscience is clear and I will put in YET ANOTHER workaround for YET ANOTHER broken-ass piece of software.

**Comment by rbos** [comment]
Oh and strictly speaking, it should be the PROGRAMFILES and PROGRAMFILES(x86) environment variable, since the name of the folder varies by locale. My bad.

https://en.wikipedia.org/wiki/Program_Files

**Comment by sethvargo** [comment]
Hey @rbos 

I'm sorry you feel that way. Unfortunately, short of rewriting Vagrant in another programming language, there's no much our team can do with these limitations. I definitely understand your frustration though.

**Comment by jpierson** [comment]
@rbos, could you please reference any particular issue that Ruby or Vagrant has with spaces? I would consider helping to contribute a fix to wherever it is needed to make sure Vagrant doesn't have to install to the root drive even if it is up stream.
