### ISSUE TITLE
UX: `vagrant up` produces misleading error message if (plugin) provider is not installed

### ISSUE THREAD

**Issue by Byron-TW** [mitchellh/vagrant#7075]
When trying to bring up a machine using a provider that is still unknown, the message produced by vagrant indicates this is a problem of the box, instead of hinting at the provider being unknown or misspelled. This can send the user down a road which doesn't lead to solving the problem. It would be better to recommend installing a plugin instead - behavior which vagrant already has.

### Meta
```
➜  vagrant -v
Vagrant 1.8.1
```
```
➜  sw_vers
ProductName:	Mac OS X
ProductVersion:	10.11.3
BuildVersion:	15D21
```

* **guest operating system**
   - [vagrant-managed-servers](https://github.com/tknerr/vagrant-managed-servers)

### Vagrantfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "managed-vm" do |cfg|
    SERVER_DOESNT_MATTER_YET='8.8.8.8'
    cfg.vm.box = "tknerr/managed-server-dummy"
    cfg.vm.provider :managed do |managed, override|
        managed.server = SERVER_DOESNT_MATTER_YET
        override.ssh.username = "user"
        override.ssh.private_key_path = "~/.ssh/id_rsa"
    end
  end
end
```

### Debug output
Does not apply.

### Expected behavior

``` bash
$ vagrant up managed-vm
The provider 'managed' could not be found, but was requested to
back the machine 'managed-vm'. Please use a provider that exists.
```
Please note that the desired behavior happens to be shown if you have previously brought up the vm, with the `vagrant-managed-servers` plugin installed (but uninstalled it right afterwards).

### Actual behavior

```bash
$ vagrant up
Bringing machine 'managed-vm' up with 'virtualbox' provider...
==> managed-vm: Box 'tknerr/managed-server-dummy' could not be found. Attempting to find and install...
    managed-vm: Box Provider: virtualbox
    managed-vm: Box Version: >= 0
==> managed-vm: Loading metadata for box 'tknerr/managed-server-dummy'
    managed-vm: URL: https://atlas.hashicorp.com/tknerr/managed-server-dummy
The box you're attempting to add doesn't support the provider
you requested. Please find an alternate box or use an alternate
provider. Double-check your requested provider to verify you didn't
simply misspell it.

If you're adding a box from HashiCorp's Atlas, make sure the box is
released.

Name: tknerr/managed-server-dummy
Address: https://atlas.hashicorp.com/tknerr/managed-server-dummy
Requested provider: [:virtualbox]
```
### Steps to reproduce

Please be sure to *not* have the `vagrant-managed-servers` plugin installed, which serves as example, before running any of the steps to reproduce the issue.

```bash
$ vagrant plugin list
vagrant-share (1.1.5, system)
```

1. execute `vagrant up managed-vm`

**Comment by sethvargo** [comment]
Hi @Byron-TW 

Thank you for opening an issue. Unfortunately due to the way the middleware is designed, it's very difficult for Vagrant to detect this. If Vagrant errors when downloading a box that does not correspond to a provider, that prevents users from "pre-downloading" boxes before they've installed Virtualbox or VMware using the `vagrant box add` command. Since the `up` command wraps that middleware, it would require a fairly significant refactor of the middleware layer to change the behavior for "up" compared to "box add", and there also exists a philosophical argument of whether those should behave differently in different code paths. While I definitely understand this isn't the most ideal UX, this is not something the core team plans to fix, so I'm going to close this issue. That being said, we would gladly review a pull request for this. Thank you for taking the time to open an issue. Have a great day! :smile:
