### ISSUE TITLE
vagrant machine stops responding after few minutes

### ISSUE THREAD

**Issue by sunil-jhamnani** [mitchellh/vagrant#7082]
I am able to ssh the vagrant machine but after some time the connection gets dropped. I checked on the the vagrant VM  and it's repeatedly showing this: _**e1000 0000:00:03.0 eth0: Reset Adapter**_
Also it says connection cannot be established when I try to ssh from my host machine. One more thing to add here is may be the mahcine gets totally disconnected because after this issue when I tried installing using apt-get it fails.

### Vagrant version
Vagrant 1.8.1

### Host operating system
MAC OS X 10.11

### Guest operating system
Ubuntu 14.0

### Vagrantfile
```ruby
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "ubuntu-1404-x86_64"

  ## Use for local testing
  config.vm.define "testing" do |testing|

    testing.vm.provider :virtualbox do |vb|
      vb.cpus = 2
      vb.customize ["modifyvm", :id, "--memory", "1024"]
      vb.customize ["modifyvm", :id, "--cpuexecutioncap", "50"]
    end

    testing.vm.provider :libvirt do |lv|
      lv.cpus = 2
      lv.memory = 1024
    end

    testing.vm.hostname = "devtest"
  end

  ## Use only for infrastructure deployment
  config.vm.define "infra" do |infra|

    infra.vm.provider :libvirt do |lv|
      lv.host = "10.10.0.87"
      lv.connect_via_ssh = true
      lv.username = 'ilaird'
      lv.id_ssh_key_file = "/home/userx/.ssh/id_rsa"
      lv.cpus = 8
      lv.memory = 24000
    end

    infra.vm.hostname = "devit"
    infra.vm.network :public_network,
        :mac => "52:54:00:b0:e6:e4"
  end

  ## Service discovery ip address
  config.vm.network :private_network,
    :libvirt__forward_mode => "none",
    :libvirt__host_ip => "172.31.0.1",
    :ip => "172.31.0.100"

  config.vm.provision "shell", path: "scripts/update.sh"
  config.vm.provision "shell", path: "scripts/docker-install.sh"
  config.vm.provision "shell", path: "scripts/mesos-install.sh"
  config.vm.provision "shell", path: "scripts/docker-registry.sh"
  config.vm.provision "shell", path: "scripts/service-bus.sh"
  config.vm.provision "shell", path: "scripts/mysql-database.sh"
  config.vm.provision "shell", path: "scripts/redis-cache.sh"

  config.vm.synced_folder "resources/", "/vagrant/"

end
```

### Expected behavior
Vagrant machine should be connected to the network.

### Actual behavior
It gets disconnected

### Steps to reproduce
1.vagrant ssh get successful
2.After some time connection is lost and it gets disconnected. 
3.not able to ssh after that

**Comment by sunil-jhamnani** [comment]
Hi @mitchellh,

Please help me on this

**Comment by sethvargo** [comment]
Hi @sunil-jhamnani 

Thank you for opening an issue. Unfortunately I am not able to reproduce this issue locally because I do not have access to your scripts or the box you've specified. Are you able to reproduce this issue with no scripts using a box like `hashicorp/precise64` or `bento/ubuntu-14.04`?

There are a number of variables in your Vagrantfile, mainly:

1. The Vagrant box itself

  If the Vagrant box is improperly built or packaged, it may not have the proper software installed. I recommend using one of our trusted boxes under the "hashicorp" or "bento" namespace to control this variable.

2. The provisioning scripts

  Please remove all provisioning scripts. Since you are able to reproduce this error with just a `vagrant ssh`, you can comment out those provisioners and the issue should still reproduce. If it does not, it means there is an error or configuration in one of your scripts that is the source of the problem.

3. The custom mac address

  Overriding the VM's mac address is perfectly fine, _but_ if that mac address also corresponds to another machine on the same network, your routing and arp cache can get confused. This seems like a likely culprit to me, because if you have two machines with the same mac, it would work until the other machine poisoned the arp cache. You can check the arp cache with `arp -a`.

4. The libvirt provider

  Unfortunately we are unable to help debug third-party plugins. Are you able to reproduce this issue with the Virtualbox provider?

Please let me know if you have any questions.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄
