### ISSUE TITLE
Clarification needed of vagrant share documentation

### ISSUE THREAD

**Issue by scottsb** [mitchellh/vagrant#7095]
The Vagrant `share` documentation currently states (emphasis added):

> Just call vagrant share. This will automatically share **as many ports as possible for remote connections**. If the Vagrant environment has a static IP or DNS address, then every port will be available. Otherwise, Vagrant will only expose forwarded ports on the machine.

However, according to the SSH Sharing page:

> SSH sharing is disabled by default as a security measure. To enable SSH sharing, simply supply the --ssh flag when calling vagrant share.

If SSH is not shared by default, then it's not true that `vagrant share` will share "as many ports as possible." I'm not sure what the correct nuance is here, which is why I'm opening an issue rather than PR, but this should definitely receive clarification.

**Comment by sethvargo** [comment]
Hi @scottsb 

Thank you for opening an issue, and I am sorry this is causing you confusion. The keyword there is "as many ports as possible". Since Vagrant uses a globally shared keypair by default, it is not safe to globally share port 22 (or whatever the configured SSH port may be), because anyone who gains access to that URL could easily SSH into the machine. This is why you must explicitly enable SSH connections with the --ssh flag.

I hope that clears things up! :smile:

**Comment by scottsb** [comment]
@sethvargo, that's what I expected was the intention, but then the `share` documentation is incorrect, since it says that "if the Vagrant environment has a static IP or DNS address, then every port will be available." However, from what you're saying, the SSH port will not be available by default, regardless of whether the box has a static IP or DNS address.

**Comment by sethvargo** [comment]
@scottsb thanks for the feedback - will update the docs to clarify this point.
