### ISSUE TITLE
Humble enhancement request for vagrant package: progress status indicator

### ISSUE THREAD

**Issue by ingineering** [mitchellh/vagrant#7116]
The vagrant package command provides no incremental progress status. Especially during a long "Exporting VM" stage, it can appear that the process is hung unless you run in debug mode. A simple "10% complete…20% complete…" etc. would be very helpful.

**Comment by sethvargo** [comment]
Hi @ingineering 

Thank you for opening an issue. After investigating this, I'm sorry to say that it's not possible 😦 . We shell out to a subprocess and that subprocess does not report it's status back to Vagrant. While I totally agree that the enhancement would be great, unfortunately it's just not possible without writing our own compressor (which wouldn't be as good likely), and I don't think that effort is worth the trade-off. I'm totally with you that it'd be nice. Since I don't imagine this happening in the short term, I am going to go ahead and close this issue. Should time ever permit, we can definitely revisit this. Thank you so much!

**Comment by dgonano** [comment]
Even just some dots . . . .  that appear progressively to know it's running would be beneficial.

**Comment by port22** [comment]
I know it's slightly crank, but I just really was skeptical if it's just doing anything:

you could get the vboxmanage command from ps, extract the filename and watch ls the filesize:
```
f=$(ps aux|grep -i [v]boxmanage|rev|awk '{print $1}'|rev);watch "ls -alh $f"
```
