### ISSUE TITLE
Add unison sync to Vagrant core

### ISSUE THREAD

**Issue by pbowyer** [mitchellh/vagrant#7124]
As @rarkins [wrote](https://github.com/mitchellh/vagrant/issues/3062#issuecomment-104664752), `unison` works really well for bi-directional sync on Windows, alleviating the pain of uni-directional `rsync` and [NFS on Windows](https://github.com/winnfsd/vagrant-winnfsd).

Setting it up and keeping it running however is not so pleasant. The [vagrant-unison](https://github.com/mrdavidlaing/vagrant-unison) plugin hasn't been updated in 3 years. There have been a bunch of forks but no cohesive development (of note: [vagrant-unison](https://github.com/dmatora/vagrant-unison) by @dmatora, [vagrant-unison](https://github.com/rancohen1/vagrant-unison) by @rancohen1, and [vagrant-unison](https://github.com/dcosson/vagrant-unison) by @dcosson).

It would be fantastic if you would consider adding core support to Vagrant for unison.

References:
- https://keylocation.sg/blog/vagrant-and-unison-without-a-plugin/

**Comment by sethvargo** [comment]
Hi @pbowyer 

Thank you for opening an issue. Unfortunately we are not experts on "unison" (personally this is the first I'm hearing of it), so it is unlikely we will add this to Vagrant core ourselves. This is why we prefer these types of things to exist as plugins before bringing them into core. We would gladly review a PR to bring this into core, but without a committed and trusted maintainer to overlook that functionality, it will quickly become just as stale as the plugins themselves. Thanks! :smile:

**Comment by dcosson** [comment]
FWIW I just pushed a bunch of improvements to my fork (including restarting unison if it crashes or leaks too much memory in the VM which was the biggest problem for me). As far as I know it's the only working vagrant unison plugin on rubygems, `vagrant plugin install vagrant-unison2`. I agree it would be cool to see in Vagrant core but understand the maintenance burden.

@sethvargo The benefit of unison is that none of the shared filesystems trigger fs events in the VM so out of the box you can't use any of the live-reloading web dev tools with Vagrant. And it's preferable to rsync because it's bi-directional so e.g. you can get your Gemfile.lock out of the VM to commit it.
