### ISSUE TITLE
I have confused when run vagrant up in every path

### ISSUE THREAD

**Issue by bank32** [mitchellh/vagrant#7142]
we all know Vagrantfile can run every path in the project directory but I've tried to check the folder existing in Vagrantfile with this condition 
```
if File.directory?(File.expand_path("./api"))
```
and sometime I've been careless and ran `vagrant up` command on another path not same as Vagrantfile locate and then this condition was not execute. 

It will be better if when I run `vagrant up` on anywhere in my project directory and Vagrant will execute Vagrantfile by the directory Vagrantfile placed, not current directory.

**Comment by sethvargo** [comment]
Hi @bank32 

By default, Vagrant looks for a Vagrantfile in the current working directory (PWD), moving up recursively. You can read more here: https://www.vagrantup.com/docs/vagrantfile/

The issue you're experiencing is because Ruby's "expand_path" function operations on PWD, not relative to the file itself. You probably want something like this instead:

```ruby
if File.directory?(File.expand_path("./api", __FILE__))
```
