### ISSUE TITLE
curl is not found when running `vagrant up` in Cygwin environment

### ISSUE THREAD

**Issue by nitrocode** [mitchellh/vagrant#7152]
I have Cygwin installed with curl and I have Cygwin's bin directory in my PATH so I can run unix commands from the windows shell. In Windows cmd, I can use `vagrant up` to launch my virtual machine but under Cygwin, Vagrant complains that it cannot find curl in my PATH.

Cygwin:
```bash
$ curl --version
curl 7.45.0 (x86_64-unknown-cygwin) libcurl/7.45.0 OpenSSL/1.0.2e zlib/1.2.8 libidn/1.29 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink
```

Cmd:
```bash
c:\Users\unknown\git\app>curl --version
curl 7.45.0 (x86_64-unknown-cygwin) libcurl/7.45.0 OpenSSL/1.0.2e zlib/1.2.8 libidn/1.29 libssh2/1.5.0
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: Debug IDN IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz TLS-SRP UnixSockets Metalink
```

### Vagrant version
1.8.1

### Host operating system
Windows 8.1

### Debug output
```
ERROR warden: Error occurred: The executable 'curl' Vagrant is trying to run was not
found in the %PATH% variable. This is an error. Please verify
this software is installed and on the path.
```

[Full debug log](https://gist.github.com/nitrocode/af92c1e3a5cfee52811d)

### Expected behavior
The VM should be booting

### Actual behavior
curl is not found in the PATH

### Steps to reproduce
1. Install Cygwin and Cygwin's curl
2. Insert Cygwin's bin folder into the Windows' PATH
3. Launch `vagrant up` from Cygwin

Edit: Not sure if it's relevant but I'm also using Cygwin within ConEmu and instead of `/bin/bash` I'm using `/bin/zsh` as my default shell.

**Comment by sethvargo** [comment]
Hi @nitrocode

Thank you for opening an issue. How did you install Vagrant?

**Comment by nitrocode** [comment]
Installed latest version using the windows 64bit msi on the vagrantup website.

**Comment by sethvargo** [comment]
Hi @nitrocode 

I'm unable to reproduce this (although I'm using Windows 10 and don't have a Windows 8.1 box handy). Could you please try completely uninstalling Vagrant and re-installing:

```
rm -rf /Applications/Vagrant
rm -f /usr/bin/vagrant
sudo pkgutil --forget com.vagrant.vagrant
rm -rf ~/.vagrant.d
```

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄

**Comment by multoncore** [comment]
Hi @sethvargo ,

It seems like it might be due to some sort of `PATH` clobbering, if `Vagrantfile` contains definitions for `ENV["PATH"]`.

Give the following `Vagrantfile` content, with an additional `ENV["PATH"]` line defined, like the following:

```ruby
# Take note of this line; seems like it clobbers Ruby VM's `PATH`.
ENV["PATH"] = "/usr/local/go/bin:$PATH"

Vagrant.configure("2") do |config|
  # Generated content from `vagrant init` here

  # Due to Vagrant issue #7610
  config.ssh.insert_key = false

end
```

On Windows 7, I managed to reproduce the `curl` not found error reported here. On OS X El Capitan, it shows a different error (`virtualbox` not detected). Vagrant version used for both platforms is 1.8.5. Removing the `ENV["PATH"]` line fixes the error.

The `Vagrantfile` content with the `ENV["PATH"]` is valid Ruby code, but I'm not sure if Vagrant should see it as valid configuration.

In your [tips and tricks](https://www.vagrantup.com/docs/vagrantfile/tips.html) documentation, under the section **Overwrite host locale in SSH session**, it showed usage of `ENV`, to pass locale information to guest machine:

```ruby
ENV["LC_ALL"] = "en_US.UTF-8"

Vagrant.configure("2") do |config|
  # ...
end
```

A possible way of inferring the example above is that it might be possible to pass `PATH` information, via `ENV["PATH"]`, to the guest machine using this method; this hypothesis is invalid.

I thought I'd add my findings to this issue, to help with improving Vagrant.

Thank you all for such a great tool! ☺️
