### ISSUE TITLE
Faster vagrant package

### ISSUE THREAD

**Issue by jeffminard-ck** [mitchellh/vagrant#7171]
Was watching out build server `top` and noticed that the built-in `bsdtar` process was running with `-z` and was pegging a single cpu 100%...on my 40 core build server. Sad face!

Would it be possible to make it use something like `pigz` instead so we could get that to go faster?

Thanks!

**Comment by sethvargo** [comment]
Hi @jeffminard-ck 

Thank you for opening an issue. I'm not very familiar with pigz, but the reason we use bsdtar is for cross-platform compatibility. We need a tool that can run on Windows, linux, and Mac, and it has to have the ability to install from source. Since we are not very familiar with pigz, it is unlikely we would implement it ourselves, but we would gladly review a PR to vagrant-installers to add this package. Thanks! :smile:

**Comment by jeffminard-ck** [comment]
I meant more along the lines of letting a person specify a compression utility, something like:

`vagrant package --compression-command='pigz'` where the default would probably just be `gzip`

_(http://zlib.net/pigz/ btw, parallel gzip compression)_

**Comment by sethvargo** [comment]
Hi @jeffminard-ck 

Thank you for your reply. We only allow Vagrant to communicate with the tools that are packaged in the installer (see vagrant-installers repo), so we would still need to see the software definitions and a build of that software successfully before we could customize this option, because Vagrant also needs to be able to _unpack_ the box as well.
