### ISSUE TITLE
rsync issue during vagrant up with Cygwin/Windows

### ISSUE THREAD

**Issue by ryayon** [mitchellh/vagrant#7172]
### Vagrant version
Vagrant 1.8.1

### Host operating system
Windows 10 + Cygwin

### Guest operating system
Debian 8 / CentOS 7

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "debian/jessie64"
  config.vm.provision "shell", inline: <<-SHELL
     sudo apt-get update
     sudo apt-get install -y ocsinventory-agent
   SHELL
end
```

### Debug output
https://gist.github.com/ryayon/4bcadc44b200118f342b

### Expected behavior
The rsync process should have complete successfully

### Actual behavior
I get an error about the rsync process

### Steps to reproduce
1. vagrant up

**Comment by sethvargo** [comment]
Hi @ryayon 

Thank you for opening an issue. We've been experiencing a number of issues with the boxes published under `debian` lately because they removed some core packages on the recent version of the box. Could you please try `bento/debian-8.2` to see if the issue reproduces there?

The exact error is:

```
Host path: /home/ryayon/Vagrant/debian/8/
Guest path: /vagrant
Command: rsync --verbose --archive --delete -z --copy-links --chmod=ugo=rwX --no-perms --no-owner --no-group --rsync-path sudo rsync -e ssh -p 2222 -o ControlMaster=auto -o ControlPath=C:/cygwin64/tmp/ssh.472 -o ControlPersist=10m -o StrictHostKeyChecking=no -o IdentitiesOnly=true -o UserKnownHostsFile=/dev/null -i 'C:/cygwin64/home/ryayon/Vagrant/debian/8/.vagrant/machines/default/virtualbox/private_key' --exclude .vagrant/ /home/ryayon/Vagrant/debian/8/ vagrant@127.0.0.1:/vagrant
Error: Warning: Permanently added '[127.0.0.1]:2222' (ECDSA) to the list of known hosts.
mm_receive_fd: no message header
process_mux_new_session: failed to receive fd 0 from slave
mux_client_request_session: read from master failed: Connection reset by peer
Failed to connect to new control master
rsync: connection unexpectedly closed (0 bytes received so far) [sender]
rsync error: error in rsync protocol data stream (code 12) at io.c(226) [sender=3.1.2]
```

Which sounds like incompatible versions of rsync between the host and the guest. Could you please tell me which version of rsync is running on the guest and host?

**Comment by ryayon** [comment]
Hi Seth,

Thanks for your reply.
Yes, it works with `bento/debian-8.2`.
Does it mean I have to open another ticket?

Actually, I have the same problem with  `centos/7`.

I check

**Comment by sethvargo** [comment]
Hi @ryayon 

I think this is an issue with those box publishers, and not an issue with Vagrant itself. I think they are either not installing rsync (which is required on both the guest and host if you want to use rsync synced folders), or they are installing an old version. Unfortunately, just like GitHub has no control over bugs in their repos, we have no control over the box curation process for the boxes on Atlas. Please note that just because a box lives under the "centos" or "debian" namespace does not mean it's an "official" box. The only official boxes are those published under the hashicorp or bento namespaces. Please let me know if you have any questions! :smile:

**Comment by ryayon** [comment]
ooohh, I didn't know about official VMs.
Thanks for the information and for your help.
