### ISSUE TITLE
Vagrant and bluestack

### ISSUE THREAD

**Issue by alokpant** [mitchellh/vagrant#7194]
This is a weird behaviour that I have been experiencing. So when I run BlueStack (http://www.bluestacks.com/) the OS crashes (Black screen as shown below).
![20160301_212152](https://cloud.githubusercontent.com/assets/6135761/14200855/1652a2fe-f7ee-11e5-887a-30608b381c94.jpg)

This happens every time.

It is same other way around too. When I first run vagrant up and then try to run bluestack, it does not start (but does not crash OS).

Thinking it may be memory problem, i check my memory status and it is perfectly fine to handle both of them running.

Here are the details:

### Vagrant version
Vagrant 1.8.1

### Host operating system
OS X El Capitan

### Guest operating system
Ubuntu 15

### Steps to reproduce
1. Open Bluestack
2. Open Terminal (Version 2.6.1 (361.1))
3. Run vagrant up

**Comment by sethvargo** [comment]
Hi @alokpant 

Thank you for opening an issue, and I am sorry this is causing you problems. Unfortunately I don't think this is a Vagrant issue. There's nothing that Vagrant is doing that would cause the OS to crash, and that's evident by the fact that it doesn't crash on its own. There could be a bug in Virtualbox, which is somehow causing the OS to crash, but I doubt that as well. Ultimately, I think this is likely a bug in OS X itself (since a GSOD on Mac is _very_ rare). I would recommend looking at the carsh logs in console.app to see what thread is crashing the OS - that will be a good indication of where to raise the issue. Thank you and sorry!

**Comment by alokpant** [comment]
@sethvargo Thank you. I am also going to post them in all related places.

**Comment by govnah** [comment]
I'm getting the same exact issue. i was wondering if anything has been discoverd as to why this behavior is happening?

thank you

**Comment by av3nger** [comment]
same issue
