### ISSUE TITLE
vagrant up mounts wrong directory if Vagrantile path has spaces

### ISSUE THREAD

**Issue by tssm** [mitchellh/vagrant#7208]
Let's say that my Vagrantfile has this content: 

``` ruby
config.vm.synced_folder ".", "/vagrant", mount_options: ["dmode=777", "fmode=666"]
config.vm.synced_folder "src/", "/srv/http", mount_options: ["dmode=777", "fmode=666"]
```

and is located on `~/Documents/Project name/ModuleName`. The output will be:

```
==> default: Mounting shared folders...
    default: /vagrant => /Users/tae/Documents
    default: /srv/http => /Users/tae/Documents
```

Removing the space from `Project name` fixes it.
### Vagrant version

1.8.1
### Host operating system

OS X 10.11 (happens on 10.10 too).
### Guest operating system

Arch Linux

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
