### ISSUE TITLE
Port collision handling broken in vmware fusion plugin

### ISSUE THREAD

**Issue by ccope** [mitchellh/vagrant#7227]
Host OS: OS X El Capitan
Guest OS: Windows 8.1
[output.txt](https://github.com/mitchellh/vagrant/files/213784/output.txt)

The Vagrantfile is rather complicated, so if you need it I'll need to do some work to create a minimal test case. There was one additional Vagrant Ubuntu VM from another Vagrant project already running. I think port 22 was conflicting.

**Comment by chrisroberts** [comment]
@ccope If it's possible to provide a minimal configuration to reproduce the behavior, that would be really helpful to get this sorted faster. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
