### ISSUE TITLE
Unable to mount directories with vagrant 1.8.1 / windows 8.1 / VB 5.0.6

### ISSUE THREAD

**Issue by Nico-h** [mitchellh/vagrant#7238]
Hi

It's impossible to mount project directory with a vagrant file like this:

``` ruby
config.vm.box = "ubuntu/trusty64"
config.vm.synced_folder ".", "/var/www/html", :mount_options => ["dmode=777", "fmode=666"]
```

```
Error:
chown: changing ownership of ‘/var/www/html’: Not a directory
```

To solve the problem I had to uninstall vagrant and come back to a prior version (1.7.4)

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
