### ISSUE TITLE
Wordpress backend suddenly takes 45-60s TTFB

### ISSUE THREAD

**Issue by lukedanielson** [mitchellh/vagrant#7258]
Not sure whether this is a Vagrant issue, a Wordpress issue, or a combination, but recently a long running project of mine suddenly has run into VERY latent load times when accessing the Wordpress admin portion of the server (ie wp-admin).

I've tried to debug for the last few days, destroying the box, re-creating new ones, switching from NFS to RSYNC, profiling the DB queries through query monitor, and just about everything else I can think of, and yet I still cannot figure out what is the source of the slowdown.

Running Vagrant `1.8.1` on OSX `10.11.4` with VMWare Fushio Pro `8.1.1`.

On the Guest, I am running a LAMP with versions: 

```
Ubuntu 14.04, 
Apache/2.4.20, 
PHP 7.0.5-3+donate.sury.org~trusty+1,
MYSQL 5.5.49-0ubuntu0.14.04.1
```

Leads me to believe it is WP related, but the latency is not present on project staging and production servers.

Has anyone ever run into this issue before?  

What puzzles me is the front end seems less affected by this.

My Puphpet config.yaml file if it helps: http://pastie.org/10811633 (yes I know, but it's quick and easy to build one).

**Comment by sethvargo** [comment]
Hi @lukedanielson 

Thank you for opening an issue. Unfortunately there is not enough information here to adequately diagnose the issue or determine if this is a bug in Vagrant, local environment issue, or wordpress issue. In general, we prefer to keep the issue tracker reserved for bug reports and feature requests. General usage questions are best served for the Vagrant mailing list, since the entire community is active there 😄.

I would also recommend the following articles:

- http://mitchellh.com/comparing-filesystem-performance-in-virtual-machines
- https://sethvargo.com/faster-rails-development-with-vagrant/ (Rails, but a lot of the principles apply)

One of the most common sources of slow-down are log files being written to a shared folder. Each request has to write to the logfile on disk, which then has to be synced back to the host, all before the request can be served.
