### ISSUE TITLE
Select select network device / bridge(, but I am asked to do so)

### ISSUE THREAD

**Issue by xrow** [mitchellh/vagrant#7280]
### Vagrant version

C:\scm\xrowvagrant>vagrant -v
Vagrant 1.7.4
and
C:\scm\xrowvagrant>vagrant -v
Vagrant 1.8.1
### Host operating system

Windows 8.1
### Guest operating system

Centos 7.2
### Vagrantfile

https://gist.github.com/xrow/3cb3487b686e2a3b70a35659d785c439

``` ruby
    config.vm.network "public_network"
    config.vm.network :forwarded_port, host: 80, guest: 80
    config.vm.network :forwarded_port, host: 8080, guest: 8080
```
### Debug output

https://gist.github.com/xrow/de5a473d449cf84ad467208d89f971da
### Expected behavior

Select automaticly a device or propose one.
### Actual behavior

Not able to select a device! Can`t start vagrant.
### Steps to reproduce
1. Unplug my surface 3 pro from the docking station and log out of WIFI. Basicly take the device offline.
2. vagrant up

**Comment by xrow** [comment]
Workaround is to disable

#    config.vm.network "public_network"

Is there a smarter way to handle this? It shall work with and without network.

**Comment by briancain** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it is a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Comment by xrow** [comment]
Thanks for reviewing.
