### ISSUE TITLE
provider-specific config for Hyper-v is being ignored

### ISSUE THREAD

**Issue by aarsan** [mitchellh/vagrant#7297]
I'm trying to set RAM and VMNAME for Ubuntu 14.04 on Hyper-V (win10) using Vagrant 1.8.1

Here is my Vagrantfile:

```
# -*- mode: ruby -*-
# vi: set ft=ruby :


Vagrant.configure(2) do |config|

  config.vm.box = "dwickern/ubuntu1404"

  config.vm.provider "hyperv" do |hv|
    hv.memory = "2048"
    hv.vmname = "chef.citycorner.local"
  end

end
```

It appears that everything in my 'config.vm.provider "hyperv" do |hv|' is completely being ignored. No matter what I set in there, it doesn't do it. However, I know it's being looked at because if I type something incorrectly (hv.hostname instead of hv.vmname), it throws an error as it should.

**Comment by sethvargo** [comment]
Hi @aarsan 

Could you please supply the complete debug output as a GitHub gist?

**Comment by aarsan** [comment]
@sethvargo Here it is:

https://gist.github.com/aarsan/9ec7d4af4d24ae4544939384f1ab92d9 

thanks!

**Comment by chrisroberts** [comment]
@aarsan Can you confirm if you are still experiencing this behavior with the latest Vagrant release? Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
