### ISSUE TITLE
Fatal error with Debian/Jessie64

### ISSUE THREAD

**Issue by northern** [mitchellh/vagrant#7324]
When I try to launch a box with `debian/jessie64` I get the follow error:

    No guest IP was given to the Vagrant core NFS helper. This is an
    internal error that should be reported as a bug.

Building with `ubuntu/trusty64` seems to work fine.

### Vagrant version
Vagrant 1.8.1

### Host operating system
OSX v10.11.4 (15E65)

### Guest operating system
Debian/Jessie64

### Vagrantfile
```ruby
BOX      = 'ubuntu/trusty64'
HOSTNAME = 'mybox'
RAM      = 2048
CPUS     = 1
CPUCAP   = 95

Vagrant.configure("2") do |config|

    config.vm.box = BOX
    config.vm.hostname = HOSTNAME

    config.vm.network "private_network", type: "dhcp"
    config.vm.network :forwarded_port, guest: 80, host: 8000, auto_correct: true

    config.vm.synced_folder ".", "/home/vagrant", nfs: true

    config.vm.provider "virtualbox" do |vm|
        vm.customize ["modifyvm", :id, "--memory", RAM]
        vm.customize ["modifyvm", :id, "--cpus", CPUS]
        vm.customize ["modifyvm", :id, "--cpuexecutioncap", CPUCAP]
    end

    config.vm.provision :shell, path: "vagrant/provision.sh"
end
```

### Debug output
https://gist.github.com/northern/95f0b58cec26757f31751dd7a96ce0de

### Expected behavior
The box should launch.

### Actual behavior
Crashed with error.

### Steps to reproduce
1. Use the supplied `Vagrantfile`.

### References
None.

**Comment by sethvargo** [comment]
Hi @northern 

Your Vagrantfile does not match the contents of the issue. You said debian jesse, but the Vagrantfile is ubuntu trusty.

**Comment by sethvargo** [comment]
Hi there,

I am going to close this due to lack of response, plus I think I know the issue. If this is still occurring, please open a new issue and include the answers to the queries above as well as complete the new issue template that will appear when you submit an issue. Thanks! 😄 

The issue is that the default base box published by debian does not include the necessary files to mount guest additions. You need to use jesse-contrib instead. Thanks!
