### ISSUE TITLE
[Usability] Command line flag `--box-no-check-update` for `vagrant up`

### ISSUE THREAD

**Issue by rushiagr** [mitchellh/vagrant#7472]
There is only one way to have Vagrant not check for box updates, which is specifying `config.vm.box_check_update = false` in the Vagrantfile. While this solves the problem, it's cumbersome to add this entry into a file to enable this action. For better usability, I'd say that we should have a command line option to not check for box updates when one spawns up a VM, like so: `vagrant up --box-no-check-update`. 

### Vagrant version
1.8.1

### Host operating system
Mac El Capitan

### Guest operating system
Ubuntu Trusty 

### Vagrantfile
Irrelevant

### Debug output
N/A

### Expected behavior
N/A

### Actual behavior
N/A

### Steps to reproduce
1. Run `vagrant up`

### References

N/A

**Comment by sethvargo** [comment]
Hi @rushiagr 

Thank you for opening an issue. Vagrant's CLI is already rather complex, so I am not in favor of adding additional flags. We are trying to move things out of the CLI and into the config (Vagrantfile) because it provides a more reproducible experience across environments. 

Perhaps adding a global environment variable might be a good option as well. I would be happy to review a pull request for that. Thanks! 😄
