### ISSUE TITLE
vagrant up not checking for new box version

### ISSUE THREAD

**Issue by TheEvilMonkey** [mitchellh/vagrant#7525]
### Vagrant version

1.8.4
### Host operating system

Windows 10 Professional
### Guest operating system

Windows 10 Professional
### Vagrantfile

``` ruby
Vagrant.configure("2") do |config|
  config.vm.guest = :windows
  config.vm.communicator = "winrm"
  config.vm.boot_timeout = 600
  config.vm.graceful_halt_timeout = 600

  config.vm.box = "Windows10"
  config.vm.box_url = "http://localhost:8081/artifactory/api/vagrant/vagrant-local/Windows10"

  config.vm.network :forwarded_port, guest: 3389, host: 3389
  config.vm.network :forwarded_port, guest: 5985, host: 5985, id: "winrm", auto_correct: true
end
```
### Debug output

https://gist.github.com/TheEvilMonkey/2956ee34b7c391458c78d3a948bfaa24
### Expected behavior

When running "vagrant up" It should prompt that there is a newer version of the box available and ask whether or not it should be downloaded.
### Actual behavior

It loads the current box with the old version.
NOTE - If you run "vagrant box outdated", it does detect the new version is available and prompts for download.

**Comment by sethvargo** [comment]
Hi @TheEvilMonkey 

Thank you for opening an issue. Can you please share the output of `vagrant box outdated`?

**Comment by TheEvilMonkey** [comment]
Do you want the debug output?  Thanks.

**Comment by sethvargo** [comment]
No, just the regular output is fine.

**Comment by TheEvilMonkey** [comment]
Checking if box 'Windows10' is up to date...
A newer version of the box 'Windows10' is available! You currently
have version '2.0.0'. The latest is version '5.0.0'. Run
`vagrant box update` to update.

**Comment by TheEvilMonkey** [comment]
When I look at the debug log for "vagrant box outdated" I see where it's running curl to get current metadata to compare but I don't see that anywhere in the debug log for "vagrant up"/

**Comment by dragon788** [comment]
If the box URL you are pointing to contains valid metadata and since your example doesn't include the box_update_check = disable option then this is probably a logic error missing the update check method when grabbing the box.

@TheEvilMonkey can you remove the .js from your gist URL, it breaks things horribly on Chrome.

**Comment by TheEvilMonkey** [comment]
I removed the .js from the URL, thanks.

**Comment by chrisroberts** [comment]
@TheEvilMonkey Can you confirm if you are still experiencing this behavior on the latest version of Vagrant? If so, please include include a new gist of the debug output from a `vagrant up`. Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
