### ISSUE TITLE
Vagrant hangs when PowerShell version requirement is not met when trying to set up SMB synced folder

### ISSUE THREAD

**Issue by raphinesse** [mitchellh/vagrant#7558]
### Vagrant version

Vagrant 1.8.4
### Host operating system

Windows 7 Professional 64 Bit @ SP1
### Guest operating system

Ubuntu 14.04/16.04 64 Bit
### Vagrantfile

``` ruby
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.synced_folder ".", "/vagrant", type: "smb"
end
```
### Debug output

Since I already installed PowerShell 4 now, I can't reproduce the issue anymore. But I had a look at the debug output and it stopped right after Printing `2` which was the output of the PowerShell version check command.
### Expected behavior

Notify the user of an unmet requirement and abort the process.
### Actual behavior

Vagrant hung.
### Steps to reproduce
1. Run `vagrant up` with above Vagrantfile

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
