### ISSUE TITLE
EnvironmentLockedError when running Vagrant from different directories.

### ISSUE THREAD

**Issue by phyber** [mitchellh/vagrant#7645]
### Vagrant version

Vagrant 1.8.5 (with patch to fix SSH key permissions on Linux guests).
### Debug output

`Vagrant attempted to acquire a lock named 'machine-snapshot-stack', but this
lock is being held by another instance of Vagrant already. Please
wait and try again. (Vagrant::Errors::EnvironmentLockedError)`
### Expected behavior

Vagrant should have retried the locking until it could be acquired.
### Actual behavior

Vagrant failed the moment it was unable to obtain the lock.
### Steps to reproduce
1. Have two Vagrant projects in different directories under the same user.
2. `vagrant up` in each directory to get at least one VM running in each.
3. Attempt to `vagrant snapshot push [vm-name]` a snapshot in both directories at the same time. Watch as one of the pair fails.

These results were obtained running under VirtualBox 5.1. However, the locking code in question does not appear to be provider specific ([shared_exec](https://github.com/mitchellh/vagrant/blob/1f88a9737369eda3dede0d3aeb30928adf82a9f7/plugins/commands/snapshot/command/push_shared.rb#L7) leading to [lock](https://github.com/mitchellh/vagrant/blob/master/lib/vagrant/environment.rb#L523)).

I am aware that setting a separate `VAGRANT_HOME` for each project would workaround this issue, however, that would result in duplication of box images which would be a significant increase in disk space used on things like build boxes.

I believe two improvements can come from this:
1. Vagrant should retry the locking for the `machine-snapshot-stack`.
   - Note that VirtualBox does not seem to mind snapshotting multiple VMs at the same time. So for VirtualBox at least, the locking seems unnecessary. This can be observed by having many VMs with different `VAGRANT_HOME`s running and having them all snapshot around the same time.
2. If the Vagrant boxes path (typically `${VAGRANT_HOME}/boxes`) could be specified through a separate environment variable (`VAGRANT_BOX_STORAGE`?), projects in different directories with different `VAGRANT_HOME`s but that share a common set of box images would not waste disk space.

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
