### ISSUE TITLE
Provisioning shell with upload_path creates RuntimeError (await_response_state)

### ISSUE THREAD

**Issue by Fuzzyma** [mitchellh/vagrant#7678]
### Vagrant version

1.8.5
### Host operating system

Windows 7 64bit
### Guest operating system

Ubuntu 12.04
### Vagrantfile

``` ruby
    config.vm.define "vm1" do |vm1|
        vm1.vm.box = "docker"

        # create docker container
        vm1.vm.provision "shell", path: "someFile.sh", upload_path: "~/someFile.sh", privileged: false
    end
```
### Debug output

https://gist.github.com/Fuzzyma/5fdd8cdd7069e551b0d9e0c867dbcd6c
### Expected behavior

Vagrant should run the script. It should be placed in `~/`
### Actual behavior

See Debug output. When I change `upload_path` to a directory (`~/`) and NOT a filename, i get the opposit error which is: 
`await_response_state: ☺scp: ~/: Is a directory (RuntimeError)`
### Steps to reproduce
1. create shell script
2. vagrant up

**Comment by chrisroberts** [comment]
@Fuzzyma Can you confirm if this behavior persists in the latest Vagrant release, and if so provide a full `--debug` gist? Thanks!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
