### ISSUE TITLE
Error: SMB shares do not remount on chef reboot (remount_synced_folders, hyperv)

### ISSUE THREAD

**Issue by MartinSGill** [mitchellh/vagrant#7722]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!
### Vagrant version

1.8.5
### Host operating system

Windows 10 (HyperV)
### Guest operating system

Windows 2012 R2
### Expected behavior

remount_synced_folders should not produce an error
### Actual behavior

```
==> default: Running provisioner: windows_reboot...
==> default: VM is going to reboot (Chef action)
==> default: Launching remount_synced_folders action...
==> default: Saved client key to *****
Vagrant attempted to call the action 'remount_synced_folders' on the provider
'Hyper-V (b0cbb334-6956-4853-944d-b970af834fe1)', but this provider doesn't support this action. This
is probably a bug in either the provider or the plugin calling this
action, and should be reported.
```
### Steps to reproduce
1. `vagrant up`
2. Use a chef provisioner that reboots the VM

**Comment by MartinSGill** [comment]
This may be related to a plugin, so I'm not sure if this should be fixed in the plugin or in vagrant itself.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
