### ISSUE TITLE
Failed to install vagrant-libvirt plugin in Arch

### ISSUE THREAD

**Issue by tdsparrow** [mitchellh/vagrant#7774]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Archlinux 2016-08-01
### Expected behavior

vagrant plugin install vagrant-libvirt
### Actual behavior

Failed to build ruby-libvirt extlib
### Steps to reproduce
1. vagrant plugin install vagrant-libvirt
### Cause

libvirt.so in Archlinux link against versioned symbol of libcurl, which is overrided by embedded version of Vagrant. On building ruby-libvirt extlib, Linker will report versioned symbol cannot be found in embedded libcurl.so.

**Comment by chrisroberts** [comment]
Hi there,

Thanks for reporting this bug. I'm sure this was a real issue when originally reported (our fault for not looking sooner!) but there have been multiple Vagrant releases since the original report. I'm going to close this issue now and request you reopen the issue if you're still experiencing this problem. I'm sorry this wasn't looked at earlier :frowning_face: 

Cheers!
