### ISSUE TITLE
vagrant snapshots don't have to have unique names

### ISSUE THREAD

**Issue by danielcompton** [mitchellh/vagrant#7810]
### Vagrant version

Vagrant 1.8.5
### Host operating system

Mac OS X 10.12.0 (GM)
### Guest operating system

ubuntu/trusty64
### Expected behavior

Repeated snapshots of a box with the same snapshot name should either fail, or overwrite the previous snapshot
### Actual behavior

Two snapshots were created with the same name
### Steps to reproduce
1. vagrant up # on a box
2. vagrant snapshot mysnap
3. vagrant snapshot mysnap
4. vagrant snapshot list

**Comment by theotherp** [comment]
IIRC the old snapshot plugin overwrite the snapshot with the same name which is what I would prefer. I often save a snapshot like "OK" and everytime I update my box and have a state which is, well, OK I save the snapshot under the same name.

**Comment by grahamlyons** [comment]
Perhaps the default behaviour could be to fail with a warning but a flag e.g. `-f | --force` could give the behaviour you describe, @theotherp?

**Comment by theotherp** [comment]
I'd be fine with that. Reduces the danger of overwriting something by mistake.

**Comment by N3WWN** [comment]
I've encountered this, too, and have found that VirtualBox allows snapshots without unique names.  I have not been able to find where vagrant used to check for uniqueness in the snapshot name.

I've not looked at any other providers, so I'm only talking about VirtualBox at this point.

I see a couple of possible solutions here:

- Enforce snapshot name uniqueness within vagrant.  
  - This would require listing the snapshots from the provider prior to taking the snapshot.
    - If the name is unique, trigger the snapshot.
    - If the name is duplicated and `-f | --force` is not used, fail.
    - If `-f | --force` is used, delete the existing snapshot and then trigger the snapshot.
    - An alternative could be, if `-f | --force` is used, trigger a snapshot with a unique name, ask the user if they want to rename or delete the existing snapshot (or use `-fD | --force-delete` or `-fR | --force-rename`), perform that action and then rename the new snapshot to the requested name.

- Enforce snapshot name uniqueness within the provider.  
  - VirtualBox supports unique snapshot names with the `--uniquename` option, which has parameters of `Number,Timestamp,Space,Force`.  
    - With `Number`, a number (starting with 1) is appended to the name.
    - With `Timestamp`, the current ISO8601 timestamp is appended to the name.
    - I'm not sure what `Space` does - On VirtualBox 5.1.14, this option doesn't appear to do anything.
    - Without `Force`, if the name is unique, the name is used verbatim.  
    - With `Force`, the specified unique value is always appended, even if the name is already unique.

It sounds like the first option is what you guys would prefer so that snapshots don't start piling up.

Personally, I don't have a preference either way.

Thoughts?!

Thanks!

-Rich Alloway (RogueWave)
