### ISSUE TITLE
Link to other Vagrants (Feature request)

### ISSUE THREAD

**Issue by ottosmittenaar** [mitchellh/vagrant#7829]
Hi,

I use Vagrant daily and love it. Use multiple vagrant boxes and would like to use the multi box feature for that. I have only one issue. I would like to use some of the boxes for multiple vagrants. I have tested my required setup and could not achieve this.

**Example:**
We use for example Nexus, SOLR & Oracle XE. We could setup separate vagrant boxes for these engines. But when added to a vagrantfile vagrant will create a box for each vagrant cluster.

Would it be possible to refer for example to another vagrant file to start an additional vagrant as part of a multi vagrant set (cluster). That way we can use one vagrant box for multiple environments.

Cheers,
Otto

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
