### ISSUE TITLE
Inputting bridge interface doesn't work

### ISSUE THREAD

**Issue by ageis** [mitchellh/vagrant#7878]
### Vagrant version
Vagrant 1.8.6

### Host operating system
Debian GNU/Linux stretch/sid (next-stable)

### Guest operating system
debian/jessie64, ubuntu/trusty64

### Vagrantfile
```ruby
    config.vm.network "public_network", ip: "10.0.2.2"
```

Expected behavior: Vagrant accepts the interface to bridge the network to which was input. Instead, it simply keeps prompting forever.

```
==> default: Available bridged network interfaces:
1) eth0
2) docker0
3) eth1
==> default: When choosing an interface, it is usually the one that is
==> default: being used to connect to the internet.
    default: Which interface should the network bridge to? eth0
    default: Which interface should the network bridge to? docker0
    default: Which interface should the network bridge to? eth1
    default: Which interface should the network bridge to? 
```

**Comment by shrmrf** [comment]
Did you try inputting `1` `2` or `3`?

**Comment by chrisroberts** [comment]
@ageis as @shrmrf has pointed out, the prompt is expecting a number, not the actual name of the device. Using `1` instead of `eth0` should get you fixed up. Cheers!

**Comment by ageis** [comment]
Ha, that makes sense. Thanks.

**Comment by ageis** [comment]
@chrisroberts Quick question, if I may. Is there any way to set `public_network` so that it's the address for the Vagrant VM's eth0 instead of an additional interface eth1?

**Comment by robertkabat** [comment]
Hello,

I have got similar problem. I know it is probably due to my lack of networking knowledge. I am  getting this:

**default: Fixed port collision for 22 => 2222. Now on port 2200.
default: Clearing any previously set network interfaces...
default: Available bridged network interfaces:
default: When choosing an interface, it is usually the one that is
default: being used to connect to the internet.
default: Which interface should the network bridge to? 1**

I tried to put number of network interface.

It occurs when I am disconnected from the internet(I did that on purpose to see if I will be able to develop without internet access).

I have default Vagrantfile. Only changes made:

 - config.vm.box_check_update = false
- added provisioning script

I can't pass this issue. Could someone just point me in the right direction here?

Regards,
Rob

**Comment by pineunity** [comment]
I recommend to let users know that they should pass with the number. Currently, it makes users confused

**Comment by cyberlly** [comment]
Enter the number on the left hand side. Such as 1 for eth0 in your example.

**Comment by exokortex** [comment]
This is horrible from a usability standpoint. If you do not tell the user to enter a number and ask for a "network interface" anyone would reasonably expect the name of a network interface to be the correct answer and not a number.
