### ISSUE TITLE
Allow plugins to define their own entry_point

### ISSUE THREAD

**Issue by vStone** [mitchellh/vagrant#7949]
In stead of relying on users to specify the entry point for a plugin, allow the plugin to define what entry point should be used.

This could be useful when a plugin's name does not match whatever should be required.
Plugin name could be: vagrant-foobar while the files are named vagrant_foobar (rubocop demands this)

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
