### ISSUE TITLE
vagrant output JSON with --json (--machine-readable also)

### ISSUE THREAD

**Issue by SamuelMarks** [mitchellh/vagrant#8017]
Rehashing discussion from https://github.com/mitchellh/vagrant/issues/6236

E.g.: I found JSON in "$HOME/.vagrant.d/data/machine-index/index"

**Comment by SamuelMarks** [comment]
In the meantime I've implemented a one-liner (single-pass parser): [vagrant2json](https://pypi.python.org/pypi/vagrant2json):
```
$ python -m vagrant2json -h
usage: E.g.: `vagrant global-status --machine-readable | python -m vagrant2json`

Convert Vagrant `--machine-readable` output to JSON

positional arguments:
  infile      [stdin]
  outfile     [stdout]

optional arguments:
  -h, --help  show this help message and exit
  --ugly      Compress JSON output [False]
  --version   show program's version number and exit
$ vagrant global-status --machine-readable | python -m vagrant2json -
[
    {
        "directory": "/mnt/large_linux/vagrant/edx-fullstack", 
        "id": "e850cc7", 
        "name": "default", 
        "provider": "virtualbox", 
        "state": "saved"
    }, 
    {
        "directory": "/tmp/vagrant", 
        "id": "9cc31c9", 
        "name": "default", 
        "provider": "virtualbox", 
        "state": "running"
    }
]
```

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Comment by SamuelMarks** [comment]
Hmm, well I did end up integrating+extending a Python project and could [without too much effort] push it back into my earlier vagrant2json project.

So this would just parse vagrant output into JSON.

I required this for the Apache Libcloud driver I wrote for Vagrant: https://github.com/offscale/libcloud/blob/vagrant/libcloud/common/vagrant.py
