### ISSUE TITLE
Vagrant.has_plugin? returns false for installed plugins

### ISSUE THREAD

**Issue by tmorton** [mitchellh/vagrant#8063]
### Vagrant version
1.9.0

### Host operating system
OS X 10.11.6 (El Capitan)

### Guest operating system
n/a

### Vagrantfile
```ruby
name = 'vagrant-timezone'
puts name
puts Vagrant.has_plugin?(name) ? 'YES' : 'NO'
puts
```

### Debug output
https://gist.github.com/tmorton/8d87ab8d57a43d7f0e161b657003756c

### Expected behavior
I've installed a plugin with `vagrant install` - in this example, the `vagrant-timezone` plugin.  I expect `Vagrant.has_plugin?` to then return `true` when called with that name.  Instead, it is returning false.  

### Actual behavior
```
~/dev/vagrant_test % vagrant plugin list 
vagrant-timezone
NO

vagrant-berkshelf (5.1.0)
vagrant-hostmanager (1.8.5)
vagrant-share (1.1.6, system)
vagrant-timezone (1.1.0)
vagrant-vmware-fusion (4.0.15)
```

The `Vagrantfile` output shows that `Vagrant.has_plugin?` is returning `false`, but I have the plugin installed.  I haven't found any conditions that make `Vagrant.has_plugin?` return true.

### Steps to reproduce
See above.

### References
#8055 might be the same problem, though it doesn't include enough info.

**Comment by chrisroberts** [comment]
@tmorton Hi! This problem is limited to a small subset of commands that do not load plugins prior to being executed. This includes `vagrant box list` and all the `vagrant plugin` subcommands. There are different reasons for not loading plugins. For the local box listing, it speeds up the listing as plugins are not required. For the plugin subcommands it is done to allow actions to be taken when plugins are in a broken state. 

Things should work as expected outside of those commands. I'll work on addressing how to enable the functionality, or properly warn the user, when plugin loading is disabled.

**Comment by rayward** [comment]
Hit this issue also.

Could vagrant perhaps just ignore the `Vagrantfile` for those commands that don't actually need to be in the context of the Vagrantfile?

**Comment by tmorton** [comment]
Hi Chris - Thanks, that makes sense.  I ran into this problem when onboarding with a new company, and becoming the first developer on vagrant 1.9.  Our Vagrantfiles have some logic to automatically install plugins if they aren't detected.  This worked with 1.8, but it blows up when `Vagrant.has_plugin?` returns false incorrectly.  

As a workaround, I guess the plugin checks should be guarded with `Vagrant.plugins_enabled?`?

**Comment by tmorton** [comment]
I can confirm that this workaround works:

If you do plugin stuff in your Vagrantfile, skip that unless `Vagrant.plugins_enabled?`
