### ISSUE TITLE
vagrant up: shell provisioner display error messages "Could not get lock ..."

### ISSUE THREAD

**Issue by cplerch** [mitchellh/vagrant#8075]
### Vagrant version
1.9.0

### Host operating system
Windows 7 x64

### Guest operating system
Ubuntu server 16.04 x64

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "maier/ubuntu-16.04-x86_64"
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
  end
  config.vm.provision "shell", inline: <<-SHELL
    echo "BEGIN shell provisioning"
    apt-get -y update
    apt-get -y upgrade
    # remove unused kernels
    dpkg --list | awk '{ print $2 }' | grep 'linux-image-*-generic' | grep -v $(uname -r) | xargs apt-get -y purge
    # remove x11
    apt-get -y purge libx11-data xauth libxmuu1 libxcb1 libx11-6 libxext6
    # remove orphaned package
    apt-get -y install deborphan
    while [ -n "$(deborphan --guess-all --libdevel)" ]; do deborphan --guess-all --libdevel | xargs apt-get -y purge; done
    apt-get -y purge deborphan dialog
    # final clean-up
    apt-get -y autoremove --purge
    apt-get -y autoclean
    apt-get -y clean
    echo "END shell provisioning"
  SHELL
end
```

### Debug output
stderr -> https://gist.github.com/cplerch/904d1be6ac987e5d31044138d0f2c1b1
stdout -> https://gist.github.com/cplerch/dda9cc216b32a90b4b7765d008f4f73a

### Expected behavior
successful shell provisioning

### Actual behavior
shell provisioning fails

### Steps to reproduce
1.  vagrant destroy
2.  vagrant up --> errors, see debug output
3.  vagrant provision  --> no errors, everthing works fine !!!

**Comment by chrisroberts** [comment]
The lock error is originating from `apt` on the guest. It looks like unattended updates are enabled on the guest which triggers `apt` commands on boot (and causes locking issues with your provision script). Ideally you'll probably want to repackage the box with unattended updates disabled. Otherwise, adding in some detection on your script or just making it pause a bit before continuing should get things going. Cheers!
