### ISSUE TITLE
Do not set `Compress=yes` for OpenSSH/Windows

### ISSUE THREAD

**Issue by zaufi** [mitchellh/vagrant#8076]
I have a Windows 10 box running latest [OpenSSH-Win32](https://github.com/PowerShell/Win32-OpenSSH). Trying to `vagrant ssh` on it, fails with the following error (found in `sshd.log`):
```
4068 10:37:50 181 Accepted publickey for ci.builder from 10.0.2.2 port 53528 ssh2: RSA SHA256:G0iGIvulDxohcX7uo01Gl+EHfNX+D8G9VGw+YsfEdWY
4068 10:37:50 181 debug1: Entering interactive session for SSH2.
4068 10:37:50 181 debug1: pipe - read end: handle:000000000000022C, io:000002162E21AFF0, fd:5
4068 10:37:50 181 debug1: pipe - write end: handle:0000000000000230, io:000002162E255920, fd:6
4068 10:37:50 181 debug1: server_init_dispatch_20
4068 10:37:50 181 ssh_dispatch_run_fatal: Connection from 10.0.2.2 port 53528: incomplete message
4068 10:37:50 181 debug1: do_cleanup
1240 10:37:50 181 debug1: close - io:000002657E858000, type:2, fd:6, table_index:6
1240 10:37:50 181 debug1: zombie'ing child at index 0, 0 zombies of 1
```

I've discovered a command line `vagrant` uses to contact the host via `VAGRANT_LOG=debug vagrant ssh` and found that removing `Compress=yes` option makes it work. Trying to force `Compression` to `yes` at `sshd` side (via `sshd_config`) do not help...

Digging into `/usr/lib64/ruby/gems/2.3.0/gems/vagrant-1.8.7/lib/vagrant/util/ssh.rb` around line 107:
```ruby
        # Command line options
        command_options = [
          "-p", options[:port].to_s,
          "-o", "Compression=yes",
          "-o", "DSAAuthentication=yes",
          "-o", "LogLevel=#{log_level}"]
```
reveals that there is no way not to use `Compression` -- it is hardcoded :(

**Comment by pvdhoef** [comment]
Compression is currently disabled in [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) (see PowerShell/Win32-OpenSSH#102).

I created a workaround for this issue by packaging a simple shell script with the base box. 
The script is named `ssh-without-compression` and has the following contents:
```shell
#!/bin/bash
ssh -o Compression=no "$@"
```
Together with the following setting in the `Vagrantfile` of the base box:
```ruby
config.ssh.ssh_command = "#{File.dirname(__FILE__)}/ssh-no-compression"
```

With these additions, `vagrant ssh` will execute the above script instead of `ssh` directly. 
The script prepends `-o Compression=no` to the command line and forwards the call to `ssh`. It appears that `ssh` looks only at the first `-o Compression` setting on the command line, so with this script, the `-o Compression=yes` setting that is passed by `vagrant` is effectively ignored.

I also use `config.vm.communicator = "winrm"` because vagrant uses the Ruby `net/ssh` package for the
ssh communicator which doesn't work smoothly with [Win32-OpenSSH](https://github.com/PowerShell/Win32-OpenSSH) either.

By packaging this into the base box, the workaround is transparent to derived boxes.
However, if it is not possible to modify the base box, it is also possible to place the `ssh-without-compression` script in the same directory as the `Vagrantfile` of the derived box and add the `config.ssh.ssh_command` and `config.vm.communicator` settings to that `Vagrantfile`.

**Comment by zaufi** [comment]
>I also use config.vm.communicator = "winrm" because vagrant uses the Ruby net/ssh package for the
>ssh communicator which doesn't work smoothly with Win32-OpenSSH either.

yes, it is [indeed](https://github.com/mitchellh/vagrant/issues/8080)

fortunately I'm a Gentoo user and my current ["workaround"](https://github.com/zaufi/zaufi-overlay/blob/master/app-emulation/vagrant/files/vagrant-1.9.0-do-not-use-ssh-compression-8076.patch) needs less actions for me... ;)

**Comment by chrisroberts** [comment]
Using the latest win32-openssh on win10 I'm able to run `vagrant ssh` and connect without issue. If you still are experiencing this issue after upgrading, please either reopen this issue, or create a new one. Thanks!

**Comment by pvdhoef** [comment]
I can confirm that compression works now with Win32-OpenSSH-0.0.12.0. 
```
ssh -o Compression=yes -p 2222 vagrant@localhost
```
Thanks a lot!

**Comment by manojampalam** [comment]
I don't think it does. Win32 port is built with compression disabled. The command line options is probably getting ignored.

**Comment by chrisroberts** [comment]
@manojampalam that is correct.

**Comment by pvdhoef** [comment]
I see. I jumped to conclusions, apologies for the confusion. 
Anyway, I'm happy to be able to use `vagrant ssh` now without workarounds.
