### ISSUE TITLE
Issue or feature request :: get the name of the provider as a value in Vagrantfile

### ISSUE THREAD

**Issue by stephencooke** [mitchellh/vagrant#8124]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
Run `vagrant -v` to show the version. If you are not running the latest version
of Vagrant, please upgrade before submitting an issue.
Vagrant 1.8.4
### Host operating system
This is the operating system that you run locally.
mac
### Guest operating system
This is the operating system you run in the virtual machine.
many linux
### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
```
not really suitable as mine is a YAML based bespoke thing. 

Please note, if you are using Homestead or a different Vagrantfile format, we
may be unable to assist with your issue. Try to reproduce the issue using a
vanilla Vagrantfile first.

### Debug output
Provide a link to a GitHub Gist containing the complete debug output:
https://www.vagrantup.com/docs/other/debugging.html. The debug output should
be very long. Do NOT paste the debug output in the issue, just paste the
link to the Gist.

### Expected behavior
What should have happened?

Vagrant to give a fact to puppet via the puppet.facter hash.

providor => "name of providor being used for provision"

no suitable hook to confirm the name of the plugin/provider name to use in facter

to know the provider was ssh-managed or libvirt or vbox would be very useful

### Actual behavior
What actually happened?

### Steps to reproduce
1.
2.
3.

### References
Are there any other GitHub issues (open or closed) that should be linked here?

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
