### ISSUE TITLE
Add ask_vault_pass to ansible_local provisioner

### ISSUE THREAD

**Issue by checkphi** [mitchellh/vagrant#8236]
Please add the ask_vault_pass option, which already exists for the ansible provisioner, to the ansible_local provisioner as well.

**Comment by gildegoma** [comment]
I'm closing this, because at the moment the `ansible_local` provisioner is not designed/intended to support any user interactive prompts.

Note that you can use the [`vault_password_file`](https://www.vagrantup.com/docs/provisioning/ansible_common.html#vault_password_file) option.

**Comment by maximd** [comment]
@gildegoma there are lots of use cases where we would like our vagrant machines to be able to use ansible vault variables. And we don't want to use the `vault_password_file` option because we don't want to ship the ansible vault password in a file under version control (those vagrant machines are used by multiple developers).

And it appears that we are not the only ones in this situation because we found a workaround described in [Pass vault password to vagrants ansible_local provisioner](https://stackoverflow.com/a/51226132/576371). It works but it looks like a dirty workaround when the `ansible` provisioner allows to do the same thing in an elegant way with [ask_vault_pass](https://www.vagrantup.com/docs/provisioning/ansible.html#ask_vault_pass) :)

It would be so great if vagrant could offer this natively for the `ansible_local` provisioner too!

**Comment by gildegoma** [comment]
> we don't want to use the vault_password_file option because we don't want to ship the ansible vault password in a file under version control 

@maximd the idea is on the contrary to configure your version control to ignore this vault password file. Each developer will then have to create this password file (as they know the password).

> It would be so great if vagrant could offer this natively for the ansible_local provisioner too!

Of course, I understand it would be handy and "natural". But it would be a very tricky work to find a solution, which is not worth the effort (of development + support). As said before, the vagrant provisioners running on the guest system are not intended to offer any interactive mode.

**Comment by maximd** [comment]
@gildegoma, ok I understand your point of view. We will (re)test the ignored password file, as we better keep it simple :+1:
