### ISSUE TITLE
"snapshot list" should order by creation time (or provide option to)

### ISSUE THREAD

**Issue by theotherp** [mitchellh/vagrant#8307]
Currently vagrant returns the snapshots sorted alphabetically. I often make snapshots of my developer box to store the latest working state before I start experimenting. Then, a couple of days or even weeks later, I may want to restore the latest working state and here it would be helpful if I could see what the last snapshot is. I'm pretty sure the old snapshot plugin did that.

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Comment by theotherp** [comment]
Hey, thanks for the reply. That's unfortunate but understandable.

I have never programmed anything with Ruby and I don't feel like learning a new programming language right now, so I'm afraid I'll have to live without this feature ;-)
