### ISSUE TITLE
Unable to get ssh access / config.ssh does not seem to work.

### ISSUE THREAD

**Issue by ismael-rivera** [mitchellh/vagrant#8320]
### Vagrant version
Vagrant 1.7.4 -- Unable to upgrade past this version.

### Host operating system
Mac OS X 10.6.8 -- Unable to upgrade past this version. 

### Guest operating system
CoreOS

### Vagrantfile
```ruby
# Copy-paste your Vagrantfile here
Vagrant.configure(2) do |config|

  config.vm.provider :virtualbox do |vb|
    vb.gui = true
  end
  config.vm.box = "coreos-alpha"
  
  config.ssh.insert_key = false
  config.ssh.private_key_path = ["~/.ssh/id_boot2docker", "~/.vagrant.d/insecure_private_key"]
  config.vm.provision "file", source: "~/.ssh/id_boot2docker.pub", destination: "~/.ssh/authorized_keys"
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"

end
```

### Debug output
https://gist.github.com/ismael-rivera/81e09882cd35c3e39879a3862abea966

### Expected behavior
Login and password should have worked thanks to the config.ssh settings in Vagrantfile thereby allowing a smooth ssh connection to the coreos box shell. Vagrantfile should have allowed this to work.

### Actual behavior
Fail to login. No Username or passwords work. Lack of authentication prevents ssh connections from allowing access to the shell. Sometimes will register as unable to connect.

### Steps to reproduce
1. Install Vagrant 1.7.4 and all it's dependencies
2. Add Coreos box and test v any version should generate the same results as it did with me. Coreos
3. Vagrant up a new coreos box using the Vagrantfile 

### References
- Insecure key replacement should work better with config.ssh.private_key_path set #4967

**Comment by duffner** [comment]
Are you referring to the inability to get Mac OSX Sierra running with SSH access?

**Comment by chrisroberts** [comment]
Hi there. Without access to the base box used I am unable reproduce this issue. Looking at the logs it shows that initial interactions with the guest SSH service timeout before a valid connection is established. The logs show both private key and password authentication failing. I would suggest checking that the vagrant user is properly setup and configured on the guest, and that ssh login does work. 

At the end of the log this error shows up:

```
Error occurred: The guest machine entered an invalid state while waiting for it
to boot. Valid states are 'starting, running'. The machine is in the
'paused' state. Please verify everything is configured
properly and try again.
```

This state transition can be caused by a variety of reasons, but generally within this scope it is generally due to the unavailability of system resources (like memory). Checking the virtualbox logs for the cause of the `paused` state should point to the cause. 

If you are still having problems with authentication please provide a Vagrantfile using a publicly accessible box that reliably reproduces the issue and either reopen this issue or create a new issue. Without a local reproduction I'm afraid I can't be of any more help than what I can find in the attached log. 

Cheers!
