### ISSUE TITLE
Vagrantfile ~/.vagrant.d ignored

### ISSUE THREAD

**Issue by sphaugh** [mitchellh/vagrant#8342]
### Vagrant version

```
~> vagrant -v
Vagrant 1.9.1
```

### Host operating system
NixOS

### Guest operating system
n/a

### Expected behavior
Vagrant should see the Vagrantfile in `~/.vagrant.d` as documented:

> 
> Note that if a Vagrantfile is not found at any step, Vagrant continues with the next step.
> 
> 1. Vagrantfile packaged with the box that is to be used for a given machine.
> 2. Vagrantfile in your Vagrant home directory (defaults to ~/.vagrant.d). This lets you specify some defaults for your system user.

### Actual behavior
```
~> vagrant up     
A Vagrant environment or target machine is required to run this
command. Run `vagrant init` to create a new Vagrant environment. Or,
get an ID of a target machine from `vagrant global-status` to run
this command on. A final option is to change to a directory with a
Vagrantfile and to try again.
```

### Steps to reproduce
1. Put Vagrantfile in `~/.vagrant.d`.
2. Change to a directory not containing a Vagrantfile.
3. Run `vagrant up` and observe the error.

**Comment by chrisroberts** [comment]
Hi there. The behavior you are experiencing is the expected behavior of Vagrant when loading Vagrantfiles. An initial Vagrantfile must be located within the [lookup path](https://www.vagrantup.com/docs/vagrantfile/#lookup-path). Once this file is located, Vagrant will then move on to the [load order and merging](https://www.vagrantup.com/docs/vagrantfile/#load-order-and-merging) to merge settings. The initial Vagrantfile is _required_ and Vagrant will halt with an error if that file is not located.

The excerpt you have pointed out is true within the context of the section it is located. When Vagrant processes the files located in the load order for merging, if one of those files is not located, it will continue to the next step.

Hope that clears things up. Cheers!
