### ISSUE TITLE
Vagrant up should warn if vagrant reload required to pick up Vagrantfile changes (eg RAM increase)

### ISSUE THREAD

**Issue by edmorley** [mitchellh/vagrant#8343]
### Vagrant version
1.9.2

### Host operating system
Windows 10 Pro

### Guest operating system
Ubuntu 14.04

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
  end
end
```

### Expected behavior
If VM options in the Vagrantfile (eg `vb.memory`) have changed, a notification/warning should be output during `vagrant up` and `vagrant provision` informing the user that they should manually run `vagrant reload` to pick up changes. (Note: the command should still succeed, the notification is for information only.)

### Actual behavior
No notification is given, meaning the user is unaware that they need to run `vagrant reload` to pick up the changes. 

For example:
* I land a new feature in a team repository that needs more RAM, so bump `vb.memory` in the checked-in `Vagrantfile`.
* Other team members pull the repository, do a `vagrant up` that just starts their existing suspended VM.
* They then get confused when they see out of memory errors during normal development, and even try running `vagrant provision`, but that of course doesn't help either.

Currently the workaround is to manually email everyone saying "please re-run vagrant reload" (which doesn't scale well for open source projects) or add manual checks to the provision script that checks the VM environment contains the expected amount of RAM etc.

### Steps to reproduce
1. `vagrant up` to create a new instance
2. `vagrant suspend`
3. Modify Vagrantfile to increase `vb.memory` from `1024` to `2048`
4. `vagrant up`
5. `vagrant provision`

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
