### ISSUE TITLE
Shared boxes

### ISSUE THREAD

**Issue by iainhallam** [mitchellh/vagrant#8413]
### Host operating system Windows 7 Pro

I'm working with Vagrant on a multi-user Windows system, and many users are downloading the same box files into their .vagrant.d folders. I'd set VAGRANT_HOME to a non-writable shared folder, but it seems that Vagrant stores other things in there besides the downloaded boxes.

Is it possible to have a new configuration variable for a shared box cache, or is there a better way of doing this?

**Comment by wiltaylor** [comment]
A work around you could try is use mklink to link each users box folder to a central folder. 

https://technet.microsoft.com/en-us/library/cc753194(v=ws.11).aspx

**Comment by chrisroberts** [comment]
Hi there. After looking through the implications of this I don't think this is something that we can add to Vagrant proper. Vagrant assumes that it has control of the data directory to upgrade boxes and store new boxes as the user requests them. While I do understand the usefulness of the request, I think it is better implemented locally rather than via a feature within Vagrant itself (like using the method mentioned here: https://github.com/mitchellh/vagrant/issues/8413#issuecomment-292511777).

Cheers!
