### ISSUE TITLE
Vagrant + Docker + host_machine_port_checker.rb port_check 

### ISSUE THREAD

**Issue by lookfwd** [mitchellh/vagrant#8423]
Hello, On a customer's PC i.e. I can't fully reproduce. I think this might have to do with Merge pull request #7035 ( @chrisroberts )

vagrant version: Vagrant 1.9.3
I am using ubuntu 16.04.
I am using ubuntu 14.04.

```
==> web: Warning: When using a remote Docker host, forwarded ports will NOT be
==> web: immediately available on your machine. They will still be forwarded on
==> web: the remote machine, however, so if you have a way to access the remote
==> web: machine, then you should be able to access those ports there. This is
==> web: not an error, it is only an informational message.
/opt/vagrant/embedded/gems/gems/vagrant-1.9.3/plugins/providers/docker/action/host_machine_port_checker.rb:24:in `port_check': wrong number of arguments (2 for 1) (ArgumentError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:121:in `[]'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:121:in `block in handle'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:257:in `block in with_forwarded_ports'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.3/lib/vagrant/action/builtin/handle_forwarded_port_collisions.rb:253:in `each'
```

I "fixed" it by patching [`host_machine_port_checker.rb`](https://github.com/mitchellh/vagrant/blob/master/plugins/providers/docker/action/host_machine_port_checker.rb) and adding an extra argument I discard in `port_check`:

```
def port_check(discard_this, port)
  host_machine = @machine.provider.host_vm
  host_machine.guest.capability(:port_open_check, port)
end
```

**Comment by agusti-t** [comment]
Same problem here!

**Comment by laurentperez** [comment]
Same here : Vagrant 1.9.3 on OSX, ubuntu 16.04 VM

**Comment by gjwilk01** [comment]
+1

**Comment by seggen-ibuildings** [comment]
reverting to 1.9.2 seems to fix the problem

see: https://releases.hashicorp.com/vagrant/1.9.2/

**Comment by sandhan26** [comment]
I seem to have the same problem. I am using vagrant 1.9.4 and docker 17.03.1-ce, build c6d412. I tried editing the host_machine_port_checker.rb file. But the problem persists. I have attached my details below.

`$ vagrant --version
Vagrant 1.9.4

$ docker --version
Docker version 17.03.1-ce, build c6d412e

$ vagrant up --no-parallel
Bringing machine 'web' up with 'docker' provider...
Bringing machine 'spark' up with 'docker' provider...
Bringing machine 'es' up with 'docker' provider...
Bringing machine 'redis' up with 'docker' provider...
Bringing machine 'mysql' up with 'docker' provider...
Bringing machine 'scrapyd1' up with 'docker' provider...
Bringing machine 'scrapyd2' up with 'docker' provider...
Bringing machine 'scrapyd3' up with 'docker' provider...
Bringing machine 'dev' up with 'docker' provider...
==> web: Provisioners will not be run since container doesn't support SSH.
==> spark: Provisioners will not be run since container doesn't support SSH.
==> es: Provisioners will not be run since container doesn't support SSH.
==> redis: Provisioners will not be run since container doesn't support SSH.
==> mysql: Provisioners will not be run since container doesn't support SSH.
==> scrapyd1: Provisioners will not be run since container doesn't support SSH.
==> scrapyd2: Provisioners will not be run since container doesn't support SSH.
==> scrapyd3: Provisioners will not be run since container doesn't support SSH.
==> dev: Provisioners will not be run since container doesn't support SSH.

$ vagrant status
Current machine states:

web                       running (docker)
spark                     running (docker)
es                        running (docker)
redis                     running (docker)
mysql                     running (docker)
scrapyd1                  running (docker)
scrapyd2                  running (docker)
scrapyd3                  running (docker)
dev                       running (docker)

This environment represents multiple VMs. The VMs are all listed
above with their current state. For more information about a specific
VM, run `vagrant status NAME`.


$ vagrant ssh
/opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/providers/docker/provider.rb:142:in `ssh_info': undefined method `first' for nil:NilClass (NoMethodError)
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:426:in `ssh_info'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/ssh_exec.rb:26:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/providers/docker/action/prepare_ssh.rb:11:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:95:in `block in finalize_action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builtin/call.rb:53:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/warden.rb:34:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/builder.rb:116:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `block in run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/util/busy.rb:19:in `busy'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/action/runner.rb:66:in `run'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:225:in `action_raw'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:200:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:182:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:182:in `block in action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:186:in `call'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/machine.rb:186:in `action'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/ssh/command.rb:60:in `block in execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/v2/command.rb:235:in `block in with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/v2/command.rb:229:in `each'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/plugin/v2/command.rb:229:in `with_target_vms'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/plugins/commands/ssh/command.rb:41:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/cli.rb:42:in `execute'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/lib/vagrant/environment.rb:308:in `cli'
	from /opt/vagrant/embedded/gems/gems/vagrant-1.9.4/bin/vagrant:127:in `<main>'`
