### ISSUE TITLE
Multi-Machine Vagrantfile works on Linux host, but not Windows host: "Message: NoMethodError: undefined method `access_key_id' for nil:NilClass"

### ISSUE THREAD

**Issue by jonathansd1** [mitchellh/vagrant#8469]
I developed the Vagrantfile on my Linux machine and have no issues providing environment variables and then `vagrant up`. Now when I attempt to ensure it is compatible in Windows, I get a `NoMethodError` regarding `aws.access_key_id`. I'm unsure if this is a direct failing of Vagrant on Windows or perhaps the `vagrant-aws` plugin.

Linux Host
OS: Arch Linux
Vagrant: 1.9.2
Ruby: 2.2.5 (embedded)

Windows Host
OS: Windows Server 2016
Vagrant: 1.9.2 (also tested v1.9.3 with same result)
Ruby: 2.2.5 (embedded)

Vagrantfile: https://gist.github.com/jonathansd1/a7b3186255b68d53f5bb25b1b27c0099
Error: https://gist.github.com/jonathansd1/e1c100f9998fb626433606e25056c9fd

Note for testing purposes, you must provide most of the environment variables listed in the Vagrantfile (e.g., $env:VAGRANT_PROFILE=default in PowerShell).

How to reproduce:
On a Windows Host (Windows Server 2016), provide the required environment variables and then run `vagrant up`.

Expected result:
A new Linux EC2 Instance

Actual result:
See error output above.

**Comment by chrisroberts** [comment]
Hi there. This looks to be a problem with the credentials helper you are attempting to use. Specifically this line here: https://gist.github.com/jonathansd1/a7b3186255b68d53f5bb25b1b27c0099#file-vagrantfile-L196

Please ensure that the credentials are being loaded into the helper and are properly available. If the credentials are available (and `creds.credentials` is not `nil`) then if you can reduce your Vagrantfile down to the smallest version able to reproduce the error, that will help in finding the root cause.

Cheers!

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
