### ISSUE TITLE
Virtualbox 5.1.20 regression - vboxsf failure - Vagrant was unable to mount VirtualBox shared folders

### ISSUE THREAD

**Issue by philippe-granet** [mitchellh/vagrant#8502]
### Vagrant version
1.9.3

### Host operating system
Win7

### Guest operating system
RHEL 6.6

### Debug output
Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=4105,gid=4103 vagrant /vagrant

The error output from the command was:

mount: Protocol error

### References
It's a Virtualbox 5.1.20 regression:
- https://forums.virtualbox.org/viewtopic.php?f=7&t=82741
- https://www.virtualbox.org/ticket/16670

### Workaround
ln -sf /opt/VBoxGuestAdditions-5.1.20/lib/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf

**Comment by njappboy** [comment]
Just updated and I'm seeing similar issue with 5.1.20 using:

### Vagrant version

1.9.2

### Host operating system

macOS Sierra

### Guest operating system

CentOS 7.3

### Debug output

Vagrant was unable to mount VirtualBox shared folders. This is usually
because the filesystem "vboxsf" is not available. This filesystem is
made available via the VirtualBox Guest Additions and kernel module.
Please verify that these guest additions are properly installed in the
guest. This is not a bug in Vagrant and is usually caused by a faulty
Vagrant box. For context, the command attempted was:

mount -t vboxsf -o uid=1000,gid=1000 home_vagrant_.m2 /home/vagrant/.m2

The error output from the command was:

mount: wrong fs type, bad option, bad superblock on home_vagrant_.m2,
       missing codepage or helper program, or other error

       In some cases useful info is found in syslog - try
       dmesg | tail or so.

**Comment by chrisroberts** [comment]
This is an upstream issue as identified in the virtuabox ticket linked in this issues description. It also looks like the latest guest additions fixes the problem: https://www.virtualbox.org/ticket/16670#comment:4

Cheers!

**Comment by tiferrei** [comment]
There's a fix for most debian-based OSs: 
```
ln -sf /usr/lib/x86_64-linux-gnu/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf
```

**Comment by parsemaestro63** [comment]
I tried the suggestion from [https://www.virtualbox.org/ticket/16670#comment:3](https://www.virtualbox.org/ticket/16670#comment:3), installing the latest test build. Then, I rebuilt the Vagrant box (ubuntu/xenial64), but getting the same mount error.

**Comment by nachopants** [comment]
Can confirm the command

ln -sf /opt/VBoxGuestAdditions-5.1.20/lib/VBoxGuestAdditions/mount.vboxsf /sbin/mount.vboxsf

Also fixed CentOS/7 VM on Vagrant 1.9.4, Virtualbox 5.1.20.

Installing the latest GuestAdditions did not resolve the issue. The symlink did.

**Comment by aljoscha2512** [comment]
Can confirm for Ubuntu 16.04, VirtualBox 5.1.20, Vagrant 1.9.4: symlink has resolved the issue.

**Comment by Jayflux** [comment]
has been referenced here too: http://stackoverflow.com/questions/42074246/vagrant-error-unable-to-mount-virtualbox-shared-folders-guest-additions-vboxs

**Comment by anashamdaoui** [comment]
you just need to install vagrant-vbguest plugin:
vagrant plugin install vagrant-vbguest
