### ISSUE TITLE
Vagrant failed to install plugin

### ISSUE THREAD

**Issue by mbelang** [mitchellh/vagrant#8538]
Vagrant failed to install plugin because xmlrpc 0.3 requires ruby 2.3 and vagrant is bundled with latest ruby 2.2.x

### Vagrant version
1.9.4 (also tried with 1.7.4 and 1.8.1 and 1.8.5 same behavior)
### Host operating system
- Ubuntu 16.04.2
- Mac Os Sierra

### Debug output
```
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

xmlrpc requires Ruby version >= 2.3.
```

### Expected behavior
Plugin should have been installed correctly

### Actual behavior
Error while installing any vagrant plugin

### Steps to reproduce
1. `vagrant plugin install <plugin_name>`

**Comment by lindycoder** [comment]
Additional note, seems to be a new issue as of **today**.

Thank you

**Comment by mbelang** [comment]
We finally found that fog-core swith to xmlrpc 0.3.0 which is only compatible with ruby 2.3. We will pin our fog dependency for the moment.

**Comment by dtilchin** [comment]
Issue on vagrant-aws: https://github.com/mitchellh/vagrant-aws/issues/510

> To workaround, I installed fog-core first with the last compatible gem:
> `vagrant plugin install --plugin-version 1.43 fog-core`

**Comment by KrE80r** [comment]
and it bites libvirt as well :

~~~
Installing the 'vagrant-libvirt' plugin. This can take a few minutes...
Bundler, the underlying system Vagrant uses to install plugins,
reported an error. The error is shown below. These errors are usually
caused by misconfigured plugin installations or transient network
issues. The error from Bundler is:

conflicting dependencies excon (~> 0.25.0) and excon (~> 0.49)
  Activated excon-0.49.0
  which does not match conflicting dependency (~> 0.25.0)

  Conflicting dependency chains:
    fog-core (= 1.43), 1.43.0 activated, depends on
    excon (~> 0.49), 0.49.0 activated

  versus:
    vagrant-libvirt (> 0), 0.0.23 activated, depends on
    fog (= 1.15), 1.15.0 activated, depends on
    excon (~> 0.25.0)
~~~

**Comment by mbelang** [comment]
Yeah I figured it out a couple hours after opening the issue. Would be great that Vagrant support Ruby 2.3 though...

**Comment by dtilchin** [comment]
Root issue resolved: https://github.com/fog/fog-core/issues/206
