### ISSUE TITLE
Error VM not created. Move on... When run vagrant package on .vbox file.

### ISSUE THREAD

**Issue by nezaboravi** [mitchellh/vagrant#8549]
I did this package few months ago on same vbox file and it was working. Now it is not working. I have tried and googled but nothing helps.

### Vagrant version
Vagrant 1.9.4

### Virtual Box version
Version 5.1.22 r115126 (Qt5.6.2)

### Host operating system
Mac OS

### Debug output
https://gist.github.com/nezaboravi/c41dccb590a9d3721a1328f192181594

### Expected behavior
it should work

### Actual behavior
Error - VM not created. Move on...
### Steps to reproduce
1. run vagrant package --base pilot-vm-300 --output admin.box

**Comment by kikitux** [comment]
@nezaboravi 

Please update vagrant

and share the output of

vagrant global-status
vagrant box list

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
