### ISSUE TITLE
sfc103 demo.sh not working

### ISSUE THREAD

**Issue by moquita** [mitchellh/vagrant#8578]
I am using Vagrant1.9.3 and I am trying to run the demo.sh of sfc103-demo stable/boron, and between many small errors i receive this in the end

classifier1: dpkg: error processing archive ../openvswitch-datapath-dkms* (--install):
==> classifier1:  cannot access archive: No such file or directory
==> classifier1: Errors were encountered while processing:
==> classifier1:  ../openvswitch-datapath-dkms*
==> classifier1: ERROR:Installing openvswitch kernel module failed.
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.

**Comment by chrisroberts** [comment]
Hi there,

Thank you for opening an issue! We do our best to keep the issue tracker reserved for bug reports and feature requests. For general usage questions or instructions, we ask users to utilize the community resources like the [Vagrant mailing list](https://groups.google.com/forum/#!forum/vagrant-up). There are many more people who will be able to get you a faster answer there. 

The error you are encountering is due to a failure while running a provisioner. You may also want to report the issue to the source of the Vagrantfile in use as they are likely to have the best answer for why this error is occurring.

Thank you and have a great day! 😄
