### ISSUE TITLE
`vagrant up` and `vagrant reload` with different behaviours when there is a file provisioner

### ISSUE THREAD

**Issue by shbmira** [mitchellh/vagrant#8603]
Hello all!

I'm not sure about the error I'm just about to show to you, I don't know if it is because of my unknowledge or if it is a real bug... but when it comes to report it, it's because I was not able to fix it.

### Vagrant version
1.9.5

### Host operating system
Windows 10

### Guest operating system
CentOS 7

### Vagrantfile
```
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.provision "file", run: "always", source: "example_directory", destination: "/home/vagrant/destination/"

  config.vm.provider "virtualbox" do |v|
    v.memory = 512
    v.cpus = 1
  end
end

```

### Expected behavior
When I run `vagrant up`, that file provisioner copies everything inside `example_directory` to `/home/vagrant/destination`. So if there is a directory `example_directory/test`, it goes to machine like `/home/vagrant/destination/test`. It means that `example_directory` disappears with this configuration.
But, if I run, immediately after `vagrant up`, a `vagrant reload` command, it creates a `example_directory` among with other files that was already copied. It means that what was done before does not change, but it appears a `example_direcory` with everything that meant to apper before, with `vagrant up`. Now, there's a `/home/vagrant/destination/example_directory/test` directory too.

### Steps to reproduce
1. Create a vagrantfile like showed above
2. `vagrant up`
3. Check destination directory
4. `vagrant reload`
5. Check destination directory

**Comment by TonyApuzzo** [comment]
I am experiencing the same problem.  I think it is a bug in the file provisioner.  When the source folder is a directory there is different behavior when the target folder already exists or not.  It also happens when using `vagrant provision` after `vagrant up`

I have kluged this by using bash script provisioner to move the nested folder contents up a level:
```
Vagrant.configure(2) do |config|
  config.vm.provision "file", source: "./config/", destination: ".vagrant-config/"
  config.vm.provision "shell", inline: <<-SHELL
	vgConfigDir=/home/vagrant/.vagrant-config
	if [[ -d "${vgConfigDir}/config" ]]; then
		echo "workaround bug https://github.com/mitchellh/vagrant/issues/8603"
		mv -- "${vgConfigDir}/config"/* "${vgConfigDir}/config/.."
		rmdir -- "${vgConfigDir}/config"
	fi
  SHELL
end
```

**Comment by briancain** [comment]
Hello @TonyApuzzo @shbmira - What you found was actually a bug (feature??) of the `scp` tool. When you scp a folder to a remote host the first time, the folder is copied and placed on the guests file system. However the second time this is ran, that folder already exists, and because of how `scp` works, it instead copies the original source folder into the remote folder thus nesting that folder. You can see the same behavior by running the scp tool yourself:

```
brian@localghost:vagrant-sandbox % scp -P 2222 -r scripts vagrant@127.0.0.1:/home/vagrant/scripts       ±[●●][master]
vagrant@127.0.0.1's password:
hello.sh                                                                            100%   15    33.6KB/s   00:00
brian@localghost:vagrant-sandbox % scp -P 2222 -r scripts vagrant@127.0.0.1:/home/vagrant/scripts       ±[●●][master]
vagrant@127.0.0.1's password:
hello.sh
```

```
vagrant@precise64:~$ tree scripts/
scripts/
`-- hello.sh

0 directories, 1 file
vagrant@precise64:~$ tree scripts/
scripts/
|-- hello.sh
`-- scripts
    `-- hello.sh

1 directory, 2 files
```

That being said, I think this is fairly confusing behavior in Vagrant, and I've made a pull request to fix this. Thanks! #8880

**Comment by shbmira** [comment]
Thank you, @briancain and @TonyApuzzo!
