### ISSUE TITLE
Set StrictHostKeyChecking in autogenerated ansible inventory file 

### ISSUE THREAD

**Issue by mhuth** [mitchellh/vagrant#8628]
vagrant ansible provisioning with ansible.host_key_checking = false works fine and doesn't stop and prompt to accept the host key during playbook execution.  However running an ansible-playbook command (using the vagrant generated ansible inventory file) the playbook execution stops to ask to accept the host key.  

Using ansible.host_key_checking = false sets an environment variable - ANSIBLE_HOST_KEY_CHECKING=False - that allows the vagrant playbook execution to work without asking. This environment variable isn't available outside vagrant and the ansible-playbook command environment doesn't inherit it.

Instead the option "ansible_ssh_common_args='-o StrictHostKeyChecking=no'" can be added to the vagrant generated ansible inventory file to allow the ansible-command to execute without asking about the host key.

This is the current auto-generated vagrant generated inventory file:
~~~
$ cat .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
rhel7 ansible_ssh_host=192.168.121.97 ansible_ssh_port=22 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/home/mhuth/.vagrant.d/insecure_private_key'
~~~

This is the proposed auto-generated inventory file (with ansible.host_key_checking = false)
~~~
$ cat .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory
rhel7 ansible_ssh_host=192.168.121.97 ansible_ssh_port=22 ansible_ssh_user='vagrant' ansible_ssh_private_key_file='/home/mhuth/.vagrant.d/insecure_private_key' ansible_ssh_common_args='-o StrictHostKeyChecking=no'
~~~

That will allow the ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory playbook.yml command to run without prompting about the host key.

### Vagrant version
Vagrant 1.9.5

### Host operating system
RHEL7.3

### Guest operating system
RHEL7

### Vagrantfile
```ruby
Vagrant.configure(2) do |config|
  config.vm.box = "rhel7-box"

  # Ansible playbook provisioning
  config.vm.provision "ansible", run: "always" do |ansible|
    # ansible.verbose = "vvv"
    ansible.host_key_checking = false
    ansible.extra_vars = { HOSTS: "rhel7" }
    ansible.playbook = "fixit.yml"
  end
end
```

### Expected behavior
ansible-playbook - <vagrant-inventory> playbook.yml doesn't prompt about the host key if ansible.host_key_checking = false is set in the Vagrantfile (false is the default anyway)

### Actual behavior
Currently ansible-playbook - <vagrant-inventory> playbook.yml , the playbook execution will halt to prompt to accept the host key

### Steps to reproduce
1.  Vagrantfile with ansible provisioning and ansible.host_key_checking = false (this is the default anyway)
2. Run vagrant up or vagrant provision to run the playbook without host key prompts
3. Run ansible-playbook -i <vagrant-inventory> and get prompted about the host key

vagrant up executes the playbook without being prompted about the host key ...
~~~
$ vagrant up
Bringing machine 'rhel7' up with 'libvirt' provider...
==> rhel7: Creating image (snapshot of base box volume).
==> rhel7: Creating domain with the following settings...
...
==> rhel7: Running provisioner: ansible...
       rhel7: Running ansible-playbook...

PLAY [Update kernel, irqbalance package, and reboot system] ********************

TASK [Gathering Facts] *********************************************************
ok: [rhel7]

TASK [Update kernel to latest] *************************************************
...
~~~

But running ansible-playbook against the vagrant guest we are prompted about the host key ...
~~~
$ ansible-playbook -i .vagrant/provisioners/ansible/inventory/vagrant_ansible_inventory -e HOSTS=rhel7 fixit.yml 

PLAY [Update kernel, irqbalance package, and reboot system] *******************************************************************************************************************************************************

TASK [Gathering Facts] ********************************************************************************************************************************************************************************************
The authenticity of host '192.168.121.229 (192.168.121.229)' can't be established.
ECDSA key fingerprint is 48:d1:09:c7:a6:ae:b8:7f:dc:2b:08:0f:98:5a:81:51.
Are you sure you want to continue connecting (yes/no)? 
~~~

**Comment by mhuth** [comment]
vagrant up debug output: https://gist.github.com/mhuth/5d27bdf992559f302bacaa5434837c7c

**Comment by gildegoma** [comment]
@mhuth Thank you for your interest in Vagrant and its Ansible provisioner. I am quite sorry to respond so late, especially because I am not in favour to accept this change request and you certainly invested some precious time in building a PR.

Here are my arguments for not going forward with this request:

* Vagrant Ansible provisioner doesn't aim at providing **official** support for external/ad-hoc Ansible usage. The provisioner goal consists in providing a solid and stable integration within Vagrant context, but with limitations (see https://github.com/mitchellh/vagrant/issues/3396#issuecomment-66905405 for more details about these guidelines). The added value is quite indirect, and low in comparison to the additional maintenance costs.
* Setting `StrictHostKeyChecking=no` in the inventory [is *not enough*](https://groups.google.com/d/msg/ansible-devel/iuoZs1oImNs/6xrj5oa1CmoJ) if you want to keep your `~/.ssh/known_hosts` file clean from any temporary/vagrant hosts. For that, you also need to set `UserKnownHostsFile=/dev/null`
* By enabling the provisioner `verbose` option, all the `ansible-playbook` and `ansible-galaxy` commands executed under the hood are displayed, which allows to quickly copy-paste-adapt them and execute from a shell.

So far the Vagrant provisioner relies on `ANSIBLE_HOST_KEY_CHECKING=false` and ` ANSIBLE_SSH_ARGS='-o UserKnownHostsFile=/dev/null` to provide the expected behaviour with any kind of inventories (generated or provided via `inventory_path` option).

I do hope you understand my position and I apologise again for the response delay.
