### ISSUE TITLE
Vagrant command not found

### ISSUE THREAD

**Issue by lukaisailovic** [mitchellh/vagrant#8744]
I just installed vagrant on windows 10 and i'm getting command not found when I try to add the box. I added it to my environment variables but still the same

**Comment by chrisroberts** [comment]
Have you restarted Windows? Does it continue to show the same behavior?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄
