### ISSUE TITLE
startvm error

### ISSUE THREAD

**Issue by alindima** [mitchellh/vagrant#8748]
### Vagrant version
Vagrant 1.9.6

### Host operating system
Linux mint Cinnamon

### Guest operating system
Ubuntu

### Vagrantfile
```ruby
Vagrant.configure("2") do |config|
  
  config.vm.box = "hashicorp/precise32"

end

```

### Debug output
https://gist.github.com/alindima/ca8890de04008dc8ef54857bbd9549c0

### Expected behavior
Vagrant should have booted the vm

### Actual behavior
Vagrant attempted booting the vm but failed

### Steps to reproduce
1.vagrant init hashicorp/precise32
2.vagrant up

**Comment by chrisroberts** [comment]
Hi there. This can be caused by insufficient resources (lack of CPU or memory resources requested) or other system related things. Checking the VirtualBox logs will generally point to the cause of the issue. This post contains information on where VirtualBox logs can be found: https://blogs.oracle.com/scoter/virtualbox-log-files-v2

Cheers!
