### ISSUE TITLE
Vagrant CLI spits out escape sequences when TERM is "dumb"

### ISSUE THREAD

**Issue by janssen** [mitchellh/vagrant#8800]
Please note that the Vagrant issue tracker is reserved for bug reports and
enhancements. For general usage questions, please use the Vagrant mailing list:
https://groups.google.com/forum/#!forum/vagrant-up. Thank you!

### Vagrant version
1.9.7

### Host operating system
MacOS Sierra

### Guest operating system
N/A

### Vagrantfile
N/A

### Expected behavior
% vagrant box list
test (parallels, 0)
%

### Actual behavior
% echo $TERM
dumb
% vagrant box list
[0mtest (parallels, 0)[0m
% 

### Steps to reproduce
1.  Fire up an Emacs.
2. Type M-x shell
3. List your boxes.

### References
Unknown.

**Comment by briancain** [comment]
@janssen - If you run vagrant with the `--no-color` option, or enable the environment variable `VAGRANT_NO_COLOR` does it remove those characters in your shell?

**Comment by chrisroberts** [comment]
Hey there,

I am going to close this due to lack of response. If this is still occurring, please open a [_new issue_](https://github.com/mitchellh/vagrant/issues/new) and follow the provided issue template that appears when you click the "New Issue" button. This will help us in getting a reproduction and fix. Thanks! 😄

**Comment by janssen** [comment]
You might consider that it's July, and people go on vacation in July.  Why not leave it open for a few weeks and give a guy a chance to get back to his computer?
