### ISSUE TITLE
Advanced command to refresh ports

### ISSUE THREAD

**Issue by evaryont** [mitchellh/vagrant#8815]
Vagrant 1.9.7 on Arch Linux

It would be very handy if there was a command to refresh the forwarded ports defined in the Vagrantfile. In my case, I am playing with a variety of software and making roles to deploy them with Ansible. It's fairly time consuming to reboot the VM with all of the setup each software does, waiting for things to finish spinning up. Especially when all I want to do is start exposing different ports from when it was booted last. It'd speed up my particular use case tremendously.

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!

**Comment by evaryont** [comment]
Sure, makes sense. To start with, where should I look? I noticed that there is a `clear_forwarded_ports` action for Virtualbox, but I don't see similar methods for other providers.

**Comment by chrisroberts** [comment]
There is a chance the functionality may not translate well to other providers. For adding a vbox specific extension (as well as introducing the functionality) it might not be bad to isolate the functionality into a Vagrant plugin that can be installed as needed.

**Comment by evaryont** [comment]
That's true, but I would imagine that the functionality would be appreciated across all providers. (Though it's true I personally only care about Virtualbox at the moment.) It's entirely possible that an API needs to be designed and implemented for this idea, and it's changes propagated to the providers. I'll play with this as a plugin for now, and see how far I can get.
