### ISSUE TITLE
`--no-provision` should not show any errors relating to provisioning

### ISSUE THREAD

**Issue by DavidSimner** [mitchellh/vagrant#8909]
### Vagrant version
Vagrant 1.9.7

### Host operating system
Windows 10 Version 1703 (OS Build 15063.413)

### Vagrantfile
```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.define "vs2015" do |vs2015|
    vs2015.vm.box = "red-gate/windows-10-vs2015"
    vs2015.vm.box_version = ">= 2017.04.19"

    vs2015.vm.provision "install", type: "shell", powershell_elevated_interactive: true, path: "vagrant/install-exe.ps1"
    vs2015.vm.provision "run-tests", type: "shell", powershell_elevated_interactive: true, path: "vagrant/run-gui-tests.ps1", args: "-VisualStudioVersion 2015"
  end
```

### Expected behavior
The command line argument `--no-provision` should not show any errors relating to provisioning because I've explicitly asked for no provisioning.

### Actual behavior
```
C:\directory\subdirectory>vagrant up --no-provision vs2015
Bringing machine 'vs2015' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

shell provisioner:
* `path` for shell provisioner does not exist on the host system: C:/directory/subdirectory/vagrant/install-exe.ps1
* `path` for shell provisioner does not exist on the host system: C:/directory/subdirectory/vagrant/run-gui-tests.ps1
```

### Steps to reproduce
1. Have a `Vagrantfile` with `.vm.provision` to a `path` that doesn't exist.
2. `vagrant up --no-provision vs2015`

**Comment by briancain** [comment]
Hi there @DavidSimner - thank you for opening an issue! However, due to how Vagrant works, this would not be possible. Technically your Vagrantfile is invalid if the shell scripts do not exist on the host. Before vagrant runs any actions, it goes to validate each machines config (which doesn't have any awareness to the passed in cli flag used). If the shell scripts don't exist, you can get around this by just commenting them out in your Vagrantfile. I hope this helps, thank you!
