### ISSUE TITLE
Consider using pbzip2

### ISSUE THREAD

**Issue by gitfoxi** [mitchellh/vagrant#8936]
One thing that's a little slow is packing and unpacking boxes. pbzip2's performance scales with the number of cores, so if you have 8 cores, it's 8x faster.

There's also pigz (parallel gzip) and pxz (parallel xz) to consider, but my experience is pbzip2 is the best combination of fast, stable and good compression.

http://compression.ca/pbzip2/

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
