### ISSUE TITLE
Consider closing 34 NFS-related issues today by shipping unfs3 instead

### ISSUE THREAD

**Issue by gitfoxi** [mitchellh/vagrant#8937]
http://unfs3.sourceforge.net/

Problem: VirtualBox shared drive sucks but NFS sucks worse. There's too many variations to ever get it right.

UNFS3 doesn't need sudo and just works. Configure it with a simple `vagrant-exports` file like:

    "/nfs/path/that/nfs/refuses/to/re-export" 192.168.50.4(rw)

Run

    unfsd -e vagrant-exports

Mount the same way you do now.

One issue is that, since it uses the same port as nfsd, you may have to use the `-n` option to assign a different port, and mount it with `port=n`.

**Comment by chrisroberts** [comment]
This sounds like a reasonable idea, but this has low chance of being a priority for us anytime soon, so we'd rather close this issue than have it stagnate into the foreseeable future. The best way to get this implemented would be to submit a PR. If you do so, we'd welcome this work. If you want to discuss how to go about doing this, I'd be happy to help with that.

Again, thank you for suggesting this and it _is_ a reasonable idea. But, since this is a feature request, it requires some work to add it to the project and we don't plan on doing that soon. But as this is also an open source project we welcome contributions. Thanks!
